import type { DemoRecipe } from "./types";

export const americanRecipes: DemoRecipe[] = [
  {
    slug: "classic-bbq-pulled-pork",
    cuisineSlug: "american",
    prepTime: 270,
    calories: 520,
    difficulty: "medium",
    servings: 8,
    title: "Classic BBQ Pulled Pork",
    description:
      "Slow-roasted pork shoulder with a paprika-brown sugar dry rub, shredded and tossed in a tangy cider vinegar barbecue sauce, piled on soft buns.",
    tags: ["pork", "bbq", "sandwich", "comfort"],
    chefTips: [
      "Cook the shoulder until a fork twists freely — about 90°C in the thickest part — then rest 20 minutes so the juices stay in the meat.",
      "Hold back some vinegar sauce and dress the pork at the table so the buns do not go soggy.",
    ],
    nutrition: {
      protein: 38,
      carbs: 38,
      fat: 22,
      fiber: 2,
      sugar: 12,
      sodium: 890,
      saturatedFat: 8,
      cholesterol: 115,
    },
    ingredients: [
      { name: "Pork shoulder", amount: "1.8", unit: "kg" },
      { name: "Paprika", amount: "2", unit: "tbsp" },
      { name: "Brown sugar", amount: "3", unit: "tbsp" },
      { name: "Chili powder", amount: "1", unit: "tbsp" },
      { name: "Ground cumin", amount: "2", unit: "tsp" },
      { name: "Apple cider vinegar", amount: "80", unit: "ml" },
      { name: "Ketchup", amount: "120", unit: "ml" },
      { name: "Hamburger buns", amount: "8", unit: "pcs" },
      { name: "Kosher salt", amount: "2", unit: "tsp" },
      { name: "Black pepper", amount: "1", unit: "tsp" },
      { name: "Garlic powder", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Rub the shoulder",
        durationMin: 15,
        text: "Pat the pork shoulder dry. Mix paprika, brown sugar, chili powder, cumin, garlic powder, salt, and pepper. Massage the rub over every surface and into any seams in the fat cap.",
      },
      {
        order: 2,
        title: "Slow-roast",
        durationMin: 210,
        text: "Set the shoulder fat-side up in a roasting pan. Cover tightly and roast at 150°C until the meat yields to a fork, 3 to 3.5 hours. Uncover for the last 30 minutes to deepen the bark.",
      },
      {
        order: 3,
        title: "Make the sauce",
        durationMin: 10,
        text: "Simmer ketchup, cider vinegar, 1 tablespoon of the remaining rub or a pinch of brown sugar, and a splash of pan juices until glossy and sharp.",
      },
      {
        order: 4,
        title: "Pull and dress",
        durationMin: 25,
        text: "Rest the pork 20 minutes. Shred with two forks, discarding large pockets of fat. Toss with enough vinegar sauce to coat. Pile onto toasted buns and serve the rest of the sauce on the side.",
      },
    ],
  },
  {
    slug: "chicken-pot-pie",
    cuisineSlug: "american",
    prepTime: 70,
    calories: 510,
    difficulty: "medium",
    servings: 6,
    title: "Chicken Pot Pie",
    description:
      "A creamy filling of chicken, peas, carrots, celery, and onion under a flaky pie crust, baked until the gravy bubbles at the edges.",
    tags: ["chicken", "baked", "comfort", "dinner"],
    chefTips: [
      "Cut a few steam vents in the top crust so the gravy thickens instead of bursting out the sides.",
      "Use leftover roast chicken or poach thighs in the stock, then reduce that stock for a deeper filling.",
    ],
    nutrition: {
      protein: 28,
      carbs: 36,
      fat: 28,
      fiber: 3,
      sugar: 5,
      sodium: 780,
      saturatedFat: 14,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Cooked chicken", amount: "450", unit: "g" },
      { name: "Frozen peas", amount: "150", unit: "g" },
      { name: "Carrots", amount: "2", unit: "pcs" },
      { name: "Celery", amount: "2", unit: "stalks" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Unsalted butter", amount: "60", unit: "g" },
      { name: "All-purpose flour", amount: "40", unit: "g" },
      { name: "Chicken stock", amount: "400", unit: "ml" },
      { name: "Heavy cream", amount: "80", unit: "ml" },
      { name: "Pie crust", amount: "1", unit: "pcs" },
      { name: "Fresh thyme", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Sweat the vegetables",
        durationMin: 12,
        text: "Dice the onion, carrots, and celery. Melt the butter in a saucepan and cook the vegetables with a pinch of salt until the onion is translucent and the carrot is just tender, about 8 minutes.",
      },
      {
        order: 2,
        title: "Make the gravy",
        durationMin: 12,
        text: "Sprinkle in the flour and cook 2 minutes, stirring. Whisk in the chicken stock, then the cream and thyme. Simmer until the gravy coats a spoon. Fold in shredded chicken and peas. Taste for salt.",
      },
      {
        order: 3,
        title: "Fill and cover",
        durationMin: 10,
        text: "Pour the filling into a 23 cm pie dish. Drape the pie crust over the top, trim and crimp the edge, and cut three steam vents. Brush with a little cream if you like a deeper color.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 36,
        text: "Bake at 200°C until the crust is golden and the filling bubbles through the vents, 30 to 35 minutes. Rest 10 minutes so the gravy sets before slicing.",
      },
    ],
  },
  {
    slug: "beef-pot-roast",
    cuisineSlug: "american",
    prepTime: 210,
    calories: 500,
    difficulty: "medium",
    servings: 6,
    title: "Beef Pot Roast",
    description:
      "Chuck roast braised with onion, carrot, potato, tomato paste, thyme, and bay until the beef slices in ribbons and the vegetables soak up the stock.",
    tags: ["beef", "braise", "comfort", "sunday"],
    chefTips: [
      "Brown the roast hard on all sides before any liquid goes in — that crust is the backbone of the gravy.",
      "If the sauce is thin at the end, simmer it uncovered 10 minutes or mash a few potatoes into the pot.",
    ],
    nutrition: {
      protein: 42,
      carbs: 28,
      fat: 24,
      fiber: 4,
      sugar: 6,
      sodium: 720,
      saturatedFat: 9,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Beef chuck roast", amount: "1.5", unit: "kg" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Carrots", amount: "4", unit: "pcs" },
      { name: "Yukon Gold potatoes", amount: "600", unit: "g" },
      { name: "Beef stock", amount: "500", unit: "ml" },
      { name: "Tomato paste", amount: "2", unit: "tbsp" },
      { name: "Fresh thyme", amount: "4", unit: "sprigs" },
      { name: "Bay leaves", amount: "2", unit: "pcs" },
      { name: "Kosher salt", amount: "2", unit: "tsp" },
      { name: "Black pepper", amount: "1", unit: "tsp" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Sear the roast",
        durationMin: 15,
        text: "Season the chuck roast with salt and pepper. Heat the oil in a heavy Dutch oven and brown the meat on all sides until a deep crust forms, 10 to 12 minutes. Transfer to a plate.",
      },
      {
        order: 2,
        title: "Build the braise",
        durationMin: 10,
        text: "Cook the quartered onions in the pot drippings until they take on color. Stir in tomato paste for 1 minute, then pour in the beef stock and scrape up the browned bits. Return the roast. Add thyme and bay.",
      },
      {
        order: 3,
        title: "Braise",
        durationMin: 150,
        text: "Cover and cook at 160°C (or at a bare simmer on the stove) for 2 hours. Add the carrots and potatoes, nestling them in the liquid, and cook until the beef is fork-tender, about 45 minutes more.",
      },
      {
        order: 4,
        title: "Rest and serve",
        durationMin: 35,
        text: "Discard the thyme and bay. Rest the roast 15 minutes, then slice or pull into chunks. Spoon the vegetables and reduced gravy over the beef.",
      },
    ],
  },
  {
    slug: "southern-biscuits-and-gravy",
    cuisineSlug: "american",
    prepTime: 45,
    calories: 580,
    difficulty: "medium",
    servings: 4,
    title: "Southern Biscuits and Gravy",
    description:
      "Flaky buttermilk biscuits split and drowned in a black-pepper sausage gravy made from pork sausage drippings, flour, and milk.",
    tags: ["breakfast", "pork", "bread", "southern"],
    chefTips: [
      "Keep the butter in the biscuit dough in pea-size pieces and handle it as little as possible so the biscuits rise in layers.",
      "Season the gravy aggressively with coarse black pepper — it should taste like a diner plate, not a white sauce.",
    ],
    nutrition: {
      protein: 18,
      carbs: 42,
      fat: 38,
      fiber: 1,
      sugar: 6,
      sodium: 980,
      saturatedFat: 18,
      cholesterol: 75,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "320", unit: "g" },
      { name: "Unsalted butter", amount: "90", unit: "g" },
      { name: "Buttermilk", amount: "180", unit: "ml" },
      { name: "Baking powder", amount: "1", unit: "tbsp" },
      { name: "Pork sausage", amount: "350", unit: "g" },
      { name: "Whole milk", amount: "480", unit: "ml" },
      { name: "Black pepper", amount: "1.5", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Baking soda", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cut the biscuit dough",
        durationMin: 12,
        text: "Heat the oven to 220°C. Whisk 250 g of the flour with baking powder, baking soda, and 0.5 teaspoon salt. Cut in cold cubed butter until the mix looks like coarse crumbs with some pea-size bits. Stir in buttermilk just until a shaggy dough forms.",
      },
      {
        order: 2,
        title: "Bake the biscuits",
        durationMin: 15,
        text: "Pat the dough 2 cm thick, fold it once, and cut 6 to 8 rounds. Bake on a sheet until tall and golden, 12 to 14 minutes.",
      },
      {
        order: 3,
        title: "Brown the sausage",
        durationMin: 8,
        text: "Crumble the pork sausage in a skillet over medium heat. Cook until browned and the fat renders. Sprinkle the remaining 70 g flour over the meat and cook 1 minute.",
      },
      {
        order: 4,
        title: "Finish the gravy",
        durationMin: 10,
        text: "Whisk in the milk in a slow stream. Simmer until the gravy is thick enough to coat a biscuit. Stir in plenty of black pepper and salt to taste. Split warm biscuits and ladle the gravy over the cut sides.",
      },
    ],
  },
  {
    slug: "new-york-cheesecake",
    cuisineSlug: "american",
    prepTime: 90,
    calories: 450,
    difficulty: "medium",
    servings: 12,
    title: "New York Cheesecake",
    description:
      "A tall, dense cream-cheese cake on a graham-cracker crust, baked with sour cream and vanilla until just set, then chilled overnight.",
    tags: ["dessert", "baked", "cheesecake", "classic"],
    chefTips: [
      "Beat the cream cheese completely smooth before adding sugar or eggs — lumps will not disappear in the oven.",
      "A water bath and a slow cool in the oven keep the top from cracking.",
    ],
    nutrition: {
      protein: 8,
      carbs: 32,
      fat: 32,
      fiber: 0,
      sugar: 26,
      sodium: 320,
      saturatedFat: 18,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Cream cheese", amount: "900", unit: "g" },
      { name: "Granulated sugar", amount: "200", unit: "g" },
      { name: "Eggs", amount: "4", unit: "pcs" },
      { name: "Sour cream", amount: "240", unit: "g" },
      { name: "Graham crackers", amount: "150", unit: "g" },
      { name: "Unsalted butter", amount: "70", unit: "g" },
      { name: "Vanilla extract", amount: "2", unit: "tsp" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the crust",
        durationMin: 15,
        text: "Crush the graham crackers to fine crumbs and mix with melted butter and a pinch of sugar. Press into the base of a 23 cm springform pan. Bake at 175°C for 8 minutes, then cool.",
      },
      {
        order: 2,
        title: "Beat the filling",
        durationMin: 15,
        text: "Beat room-temperature cream cheese until perfectly smooth. Add sugar and salt, then the eggs one at a time. Blend in sour cream and vanilla on low speed so you do not whip in air.",
      },
      {
        order: 3,
        title: "Bake",
        durationMin: 50,
        text: "Pour the filling over the crust. Bake in a water bath at 160°C until the edges are set and the center still wobbles like gelatin, 50 to 60 minutes.",
      },
      {
        order: 4,
        title: "Cool and chill",
        durationMin: 10,
        text: "Turn off the oven, crack the door, and let the cake sit 1 hour. Cool on a rack, then refrigerate at least 6 hours. Run a knife around the ring before unmolding.",
      },
    ],
  },
  {
    slug: "classic-meatballs",
    cuisineSlug: "american",
    prepTime: 50,
    calories: 470,
    difficulty: "easy",
    servings: 4,
    title: "Classic Meatballs",
    description:
      "Tender beef-and-pork meatballs bound with breadcrumbs, Parmesan, egg, and garlic, simmered in marinara and finished with parsley.",
    tags: ["beef", "pork", "pasta", "dinner"],
    chefTips: [
      "Soak the breadcrumbs in a splash of milk before mixing so the meatballs stay moist instead of dense.",
      "Brown in batches and finish in the sauce — boiling raw balls in marinara works, but the sear adds flavor.",
    ],
    nutrition: {
      protein: 32,
      carbs: 22,
      fat: 28,
      fiber: 3,
      sugar: 8,
      sodium: 840,
      saturatedFat: 10,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Ground beef", amount: "350", unit: "g" },
      { name: "Ground pork", amount: "250", unit: "g" },
      { name: "Breadcrumbs", amount: "60", unit: "g" },
      { name: "Parmesan", amount: "40", unit: "g" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Marinara sauce", amount: "700", unit: "ml" },
      { name: "Flat-leaf parsley", amount: "15", unit: "g" },
      { name: "Whole milk", amount: "40", unit: "ml" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the meat",
        durationMin: 10,
        text: "Soak the breadcrumbs in milk. Combine ground beef, ground pork, squeezed breadcrumbs, grated Parmesan, beaten egg, minced garlic, chopped parsley, and salt. Mix with a light hand until just combined.",
      },
      {
        order: 2,
        title: "Shape and brown",
        durationMin: 15,
        text: "Roll into 16 golf-ball meatballs. Brown them in olive oil over medium-high heat, turning so they color on most sides, about 8 minutes. They do not need to cook through.",
      },
      {
        order: 3,
        title: "Simmer in marinara",
        durationMin: 20,
        text: "Pour the marinara into the pan and nestle the meatballs in the sauce. Simmer gently, covered, until cooked through and tender, 15 to 18 minutes.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 5,
        text: "Taste the sauce for salt. Shower with more parsley and Parmesan. Serve over spaghetti or stuffed into a hoagie.",
      },
    ],
  },
  {
    slug: "chicken-and-waffles",
    cuisineSlug: "american",
    prepTime: 55,
    calories: 640,
    difficulty: "medium",
    servings: 4,
    title: "Chicken and Waffles",
    description:
      "Buttermilk-brined fried chicken with a paprika flour crust, served on crisp waffles with maple syrup and a dash of hot sauce.",
    tags: ["chicken", "breakfast", "fried", "southern"],
    chefTips: [
      "Rest the dredged chicken 10 minutes before frying so the crust adheres, and hold finished pieces in a 95°C oven while you cook the waffles.",
      "A few drops of hot sauce in the maple syrup is the diner move — sweet heat against the crunch.",
    ],
    nutrition: {
      protein: 36,
      carbs: 52,
      fat: 32,
      fiber: 2,
      sugar: 18,
      sodium: 920,
      saturatedFat: 8,
      cholesterol: 165,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "800", unit: "g" },
      { name: "Buttermilk", amount: "360", unit: "ml" },
      { name: "All-purpose flour", amount: "280", unit: "g" },
      { name: "Paprika", amount: "2", unit: "tsp" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Whole milk", amount: "240", unit: "ml" },
      { name: "Baking powder", amount: "2", unit: "tsp" },
      { name: "Maple syrup", amount: "80", unit: "ml" },
      { name: "Hot sauce", amount: "2", unit: "tbsp" },
      { name: "Vegetable oil", amount: "1", unit: "L" },
      { name: "Kosher salt", amount: "2", unit: "tsp" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Brine the chicken",
        durationMin: 10,
        text: "Toss the chicken with buttermilk, 1 teaspoon salt, and half the paprika. If you have time, refrigerate 2 hours; otherwise rest 20 minutes on the counter.",
      },
      {
        order: 2,
        title: "Dredge and fry",
        durationMin: 25,
        text: "Mix 180 g flour with the remaining paprika and 1 teaspoon salt. Dredge the chicken, pressing the flour on. Fry in 175°C oil until the crust is deep gold and the meat reaches 74°C, 12 to 14 minutes. Drain on a rack.",
      },
      {
        order: 3,
        title: "Mix the waffle batter",
        durationMin: 8,
        text: "Whisk the remaining flour with baking powder. In another bowl whisk eggs, milk, and melted butter. Combine just until the dry streaks disappear.",
      },
      {
        order: 4,
        title: "Cook and plate",
        durationMin: 12,
        text: "Cook waffles until crisp. Plate a waffle, top with fried chicken, and pour maple syrup mixed with hot sauce over everything.",
      },
    ],
  },
  {
    slug: "sloppy-joe-sandwich",
    cuisineSlug: "american",
    prepTime: 30,
    calories: 480,
    difficulty: "easy",
    servings: 4,
    title: "Sloppy Joe Sandwich",
    description:
      "Loose ground-beef filling cooked with onion, ketchup, Worcestershire, mustard, and brown sugar, spooned onto toasted hamburger buns.",
    tags: ["beef", "sandwich", "weeknight", "kid-friendly"],
    chefTips: [
      "Let the sauce reduce until it mounds on a spoon — watery Sloppy Joes soak the bun before you sit down.",
      "Toast the cut sides of the buns in the skillet drippings for a little extra flavor.",
    ],
    nutrition: {
      protein: 28,
      carbs: 42,
      fat: 22,
      fiber: 2,
      sugar: 16,
      sodium: 880,
      saturatedFat: 8,
      cholesterol: 80,
    },
    ingredients: [
      { name: "Ground beef", amount: "500", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Ketchup", amount: "160", unit: "ml" },
      { name: "Worcestershire sauce", amount: "1", unit: "tbsp" },
      { name: "Yellow mustard", amount: "1", unit: "tbsp" },
      { name: "Brown sugar", amount: "1", unit: "tbsp" },
      { name: "Hamburger buns", amount: "4", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Vegetable oil", amount: "1", unit: "tbsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Brown the beef",
        durationMin: 10,
        text: "Heat the oil in a skillet. Cook the ground beef with salt, breaking it into small crumbles, until no pink remains. Spoon off excess fat if the pan is swimming.",
      },
      {
        order: 2,
        title: "Soften the onion",
        durationMin: 6,
        text: "Add finely chopped onion and minced garlic. Cook until the onion is soft and sweet, about 5 minutes.",
      },
      {
        order: 3,
        title: "Simmer the sauce",
        durationMin: 10,
        text: "Stir in ketchup, Worcestershire, mustard, and brown sugar. Simmer until thick and glossy, 8 to 10 minutes. Taste and add a pinch more salt or sugar.",
      },
      {
        order: 4,
        title: "Pile onto buns",
        durationMin: 4,
        text: "Toast the buns. Spoon the filling generously onto the bottoms, cap with the lids, and serve immediately with plenty of napkins.",
      },
    ],
  },
  {
    slug: "corn-dogs",
    cuisineSlug: "american",
    prepTime: 35,
    calories: 340,
    difficulty: "easy",
    servings: 6,
    title: "Corn Dogs",
    description:
      "Hot dogs on wooden sticks, dipped in a slightly sweet cornmeal-buttermilk batter and fried until the coating is puffed and golden.",
    tags: ["fair-food", "fried", "snack", "kid-friendly"],
    chefTips: [
      "Pat the hot dogs dry and dust them with a little flour so the batter clings instead of sliding off in the oil.",
      "Keep the batter thick like pancake batter — if it runs, add a spoon of cornmeal.",
    ],
    nutrition: {
      protein: 12,
      carbs: 28,
      fat: 20,
      fiber: 1,
      sugar: 6,
      sodium: 780,
      saturatedFat: 6,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Hot dogs", amount: "6", unit: "pcs" },
      { name: "Yellow cornmeal", amount: "120", unit: "g" },
      { name: "All-purpose flour", amount: "80", unit: "g" },
      { name: "Buttermilk", amount: "180", unit: "ml" },
      { name: "Baking powder", amount: "1.5", unit: "tsp" },
      { name: "Granulated sugar", amount: "1", unit: "tbsp" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Vegetable oil", amount: "1", unit: "L" },
      { name: "Wooden sticks", amount: "6", unit: "pcs" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Skewer the dogs",
        durationMin: 5,
        text: "Pat the hot dogs dry. Push a wooden stick two-thirds of the way into each one. Dust lightly with a pinch of the flour.",
      },
      {
        order: 2,
        title: "Mix the batter",
        durationMin: 8,
        text: "Whisk cornmeal, remaining flour, baking powder, sugar, and salt. In another bowl whisk buttermilk and egg. Combine into a thick batter. Pour it into a tall glass for easy dipping.",
      },
      {
        order: 3,
        title: "Heat the oil",
        durationMin: 8,
        text: "Heat 5 cm of oil in a deep pot to 180°C. A drip of batter should sizzle and rise immediately.",
      },
      {
        order: 4,
        title: "Dip and fry",
        durationMin: 14,
        text: "Dip each hot dog in the batter, twisting to coat, and lower into the oil. Fry 3 to 4 minutes until deep gold, turning once. Drain on a rack and serve hot with mustard or ketchup.",
      },
    ],
  },
  {
    slug: "loaded-baked-potato",
    cuisineSlug: "american",
    prepTime: 70,
    calories: 450,
    difficulty: "easy",
    servings: 4,
    title: "Loaded Baked Potato",
    description:
      "Russet potatoes baked until the skins crisp, then split and piled with cheddar, sour cream, crisp bacon, chives, and butter.",
    tags: ["potato", "side", "comfort", "weeknight"],
    chefTips: [
      "Rub the skins with a little oil and salt before baking so they blister instead of turning leathery.",
      "Fluff the flesh with a fork and mash in the butter before the toppings so every bite is seasoned.",
    ],
    nutrition: {
      protein: 16,
      carbs: 48,
      fat: 22,
      fiber: 5,
      sugar: 4,
      sodium: 620,
      saturatedFat: 12,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Russet potatoes", amount: "4", unit: "pcs" },
      { name: "Cheddar", amount: "120", unit: "g" },
      { name: "Sour cream", amount: "120", unit: "g" },
      { name: "Bacon", amount: "6", unit: "slices" },
      { name: "Chives", amount: "15", unit: "g" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Vegetable oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the potatoes",
        durationMin: 8,
        text: "Heat the oven to 200°C. Scrub the russets, pierce them a few times, and rub with oil and salt.",
      },
      {
        order: 2,
        title: "Bake",
        durationMin: 55,
        text: "Bake directly on the rack until a skewer slides through with no resistance, 50 to 60 minutes. Meanwhile, cook the bacon until crisp and crumble it. Grate the cheddar and snip the chives.",
      },
      {
        order: 3,
        title: "Split and butter",
        durationMin: 4,
        text: "Cut a deep cross in each potato and squeeze the ends to open. Fluff the flesh and mash in the butter, salt, and pepper.",
      },
      {
        order: 4,
        title: "Load",
        durationMin: 3,
        text: "Top with cheddar so it melts, then sour cream, bacon, and chives. Serve immediately.",
      },
    ],
  },
  {
    slug: "new-york-style-pizza",
    cuisineSlug: "american",
    prepTime: 45,
    calories: 330,
    difficulty: "medium",
    servings: 8,
    title: "New York Style Pizza",
    description:
      "A thin, foldable pie with a high-gluten dough, crushed-tomato sauce, low-moisture mozzarella, olive oil, and oregano.",
    tags: ["pizza", "baked", "dinner", "classic"],
    chefTips: [
      "For true New York chew, cold-ferment the dough 24 to 72 hours; the long rest builds flavor and a blistered crust.",
      "Use a steel or stone preheated at least 45 minutes, and go light on sauce so the center stays crisp.",
    ],
    nutrition: {
      protein: 14,
      carbs: 42,
      fat: 12,
      fiber: 2,
      sugar: 3,
      sodium: 680,
      saturatedFat: 5,
      cholesterol: 25,
    },
    ingredients: [
      { name: "Bread flour", amount: "400", unit: "g" },
      { name: "Instant yeast", amount: "4", unit: "g" },
      { name: "Crushed tomatoes", amount: "250", unit: "g" },
      { name: "Low-moisture mozzarella", amount: "250", unit: "g" },
      { name: "Extra virgin olive oil", amount: "2", unit: "tbsp" },
      { name: "Dried oregano", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "10", unit: "g" },
      { name: "Granulated sugar", amount: "1", unit: "tsp" },
      { name: "Warm water", amount: "260", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the dough",
        durationMin: 15,
        text: "Stir yeast and sugar into the warm water. Add bread flour and salt and knead until smooth and slightly tacky, 8 to 10 minutes. Work in 1 tablespoon olive oil. Rest 20 minutes if using the same day, or refrigerate overnight.",
      },
      {
        order: 2,
        title: "Make the sauce",
        durationMin: 5,
        text: "Season crushed tomatoes with remaining olive oil, oregano, and a pinch of salt. Do not cook — New York sauce goes on raw and finishes in the oven.",
      },
      {
        order: 3,
        title: "Stretch the pie",
        durationMin: 10,
        text: "Heat a stone or steel at 260°C. Stretch the dough into a 35 cm round, leaving a slightly thicker rim. Keep the center thin enough to fold.",
      },
      {
        order: 4,
        title: "Top and bake",
        durationMin: 15,
        text: "Spread a thin layer of sauce, scatter shredded low-moisture mozzarella, and bake until the cheese browns in spots and the rim blisters, 7 to 10 minutes. Slice into 8 triangles.",
      },
    ],
  },
  {
    slug: "cobb-salad",
    cuisineSlug: "american",
    prepTime: 35,
    calories: 500,
    difficulty: "easy",
    servings: 4,
    title: "Cobb Salad",
    description:
      "Chopped romaine lined with rows of chicken, bacon, egg, avocado, tomato, and blue cheese, dressed with a sharp red-wine vinaigrette.",
    tags: ["salad", "chicken", "lunch", "classic"],
    chefTips: [
      "Keep the toppings in neat rows for the classic Hollywood look, then toss at the table so the blue cheese and vinaigrette coat everything.",
      "Cook the bacon first and use a spoon of the warm fat in the vinaigrette if you want extra richness.",
    ],
    nutrition: {
      protein: 32,
      carbs: 12,
      fat: 36,
      fiber: 6,
      sugar: 4,
      sodium: 720,
      saturatedFat: 12,
      cholesterol: 220,
    },
    ingredients: [
      { name: "Romaine lettuce", amount: "2", unit: "heads" },
      { name: "Cooked chicken breast", amount: "300", unit: "g" },
      { name: "Bacon", amount: "6", unit: "slices" },
      { name: "Eggs", amount: "4", unit: "pcs" },
      { name: "Avocado", amount: "1", unit: "pcs" },
      { name: "Tomatoes", amount: "2", unit: "pcs" },
      { name: "Blue cheese", amount: "80", unit: "g" },
      { name: "Red wine vinegar", amount: "3", unit: "tbsp" },
      { name: "Extra virgin olive oil", amount: "80", unit: "ml" },
      { name: "Dijon mustard", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the bacon and eggs",
        durationMin: 15,
        text: "Fry the bacon until crisp and drain. Boil the eggs 9 minutes, then ice and peel. Chop both.",
      },
      {
        order: 2,
        title: "Prep the produce",
        durationMin: 10,
        text: "Chop the romaine. Dice the chicken, tomato, and avocado. Crumble the blue cheese.",
      },
      {
        order: 3,
        title: "Shake the vinaigrette",
        durationMin: 5,
        text: "Whisk red wine vinegar with Dijon, a pinch of salt, and olive oil until emulsified.",
      },
      {
        order: 4,
        title: "Compose the salad",
        durationMin: 5,
        text: "Arrange romaine on a platter. Line up chicken, bacon, egg, avocado, tomato, and blue cheese in rows. Drizzle with vinaigrette and toss just before serving.",
      },
    ],
  },
  {
    slug: "tuna-melt-sandwich",
    cuisineSlug: "american",
    prepTime: 20,
    calories: 430,
    difficulty: "easy",
    servings: 4,
    title: "Tuna Melt Sandwich",
    description:
      "Tuna salad with mayonnaise and celery, piled on rye or sourdough, topped with cheddar, and griddled in butter until the cheese runs.",
    tags: ["sandwich", "fish", "lunch", "quick"],
    chefTips: [
      "Drain the tuna very well so the salad does not steam the bread and turn the sandwich soggy.",
      "Cover the skillet for the last minute so the cheddar melts before the bread gets too dark.",
    ],
    nutrition: {
      protein: 26,
      carbs: 28,
      fat: 24,
      fiber: 2,
      sugar: 3,
      sodium: 780,
      saturatedFat: 10,
      cholesterol: 65,
    },
    ingredients: [
      { name: "Canned tuna", amount: "340", unit: "g" },
      { name: "Mayonnaise", amount: "80", unit: "g" },
      { name: "Celery", amount: "1", unit: "stalk" },
      { name: "Cheddar", amount: "120", unit: "g" },
      { name: "Rye bread", amount: "8", unit: "slices" },
      { name: "Unsalted butter", amount: "30", unit: "g" },
      { name: "Red onion", amount: "0.25", unit: "pcs" },
      { name: "Lemon juice", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the tuna salad",
        durationMin: 8,
        text: "Drain the tuna thoroughly and flake it. Fold in mayonnaise, finely diced celery, minced red onion, lemon juice, and black pepper.",
      },
      {
        order: 2,
        title: "Assemble",
        durationMin: 4,
        text: "Butter one side of each rye slice. On the unbuttered sides, spread tuna salad and cover with sliced cheddar. Close the sandwiches butter-side out.",
      },
      {
        order: 3,
        title: "Griddle",
        durationMin: 8,
        text: "Cook in a skillet over medium at 4 minutes per side until the bread is mahogany and the cheddar melts. Tent with a lid if the cheese needs help.",
      },
      {
        order: 4,
        title: "Slice",
        durationMin: 1,
        text: "Rest 1 minute, cut on the diagonal, and serve hot.",
      },
    ],
  },
  {
    slug: "banana-bread",
    cuisineSlug: "american",
    prepTime: 70,
    calories: 280,
    difficulty: "easy",
    servings: 10,
    title: "Banana Bread",
    description:
      "A moist loaf of very ripe bananas, butter, sugar, and vanilla, with optional walnuts, baked until the crumb is tender and the top splits.",
    tags: ["bread", "baked", "dessert", "snack"],
    chefTips: [
      "Use bananas that are heavily speckled or black — underripe fruit makes a dry, bland loaf.",
      "A toothpick should come out with a few moist crumbs, not wet batter; overbaking dries the edges.",
    ],
    nutrition: {
      protein: 4,
      carbs: 38,
      fat: 12,
      fiber: 2,
      sugar: 20,
      sodium: 240,
      saturatedFat: 6,
      cholesterol: 50,
    },
    ingredients: [
      { name: "Ripe bananas", amount: "3", unit: "pcs" },
      { name: "All-purpose flour", amount: "220", unit: "g" },
      { name: "Granulated sugar", amount: "150", unit: "g" },
      { name: "Unsalted butter", amount: "85", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Baking soda", amount: "1", unit: "tsp" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
      { name: "Walnuts", amount: "80", unit: "g" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mash the bananas",
        durationMin: 8,
        text: "Heat the oven to 175°C and grease a 23 by 13 cm loaf pan. Mash the bananas until mostly smooth with a few lumps.",
      },
      {
        order: 2,
        title: "Mix the batter",
        durationMin: 8,
        text: "Beat melted butter with sugar, then the eggs and vanilla. Stir in the bananas. Fold in flour, baking soda, and salt just until combined. Fold in chopped walnuts if using.",
      },
      {
        order: 3,
        title: "Bake",
        durationMin: 52,
        text: "Scrape into the pan and bake until a tester comes out with a few crumbs, 50 to 58 minutes. Tent with foil if the top browns too fast.",
      },
      {
        order: 4,
        title: "Cool",
        durationMin: 2,
        text: "Cool in the pan 10 minutes, then turn out onto a rack. Slice when just warm or fully cool.",
      },
    ],
  },
  {
    slug: "peanut-butter-cookies",
    cuisineSlug: "american",
    prepTime: 30,
    calories: 130,
    difficulty: "easy",
    servings: 24,
    title: "Peanut Butter Cookies",
    description:
      "Tender peanut-butter cookies sweetened with sugar, bound with egg and a little flour, stamped with the classic fork crisscross.",
    tags: ["cookies", "baked", "dessert", "snack"],
    chefTips: [
      "The dough should be soft but not sticky; chill 15 minutes if it smears instead of holding a crisscross.",
      "Pull the cookies when the edges are set and the centers still look slightly underdone — they firm as they cool.",
    ],
    nutrition: {
      protein: 3,
      carbs: 12,
      fat: 7,
      fiber: 1,
      sugar: 8,
      sodium: 95,
      saturatedFat: 1.5,
      cholesterol: 10,
    },
    ingredients: [
      { name: "Peanut butter", amount: "250", unit: "g" },
      { name: "Granulated sugar", amount: "150", unit: "g" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "All-purpose flour", amount: "60", unit: "g" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
      { name: "Baking soda", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the dough",
        durationMin: 8,
        text: "Heat the oven to 175°C. Beat peanut butter and sugar until creamy. Beat in the egg and vanilla, then flour, baking soda, and salt.",
      },
      {
        order: 2,
        title: "Shape",
        durationMin: 8,
        text: "Roll tablespoons of dough into 24 balls and space them on two lined sheets.",
      },
      {
        order: 3,
        title: "Crisscross",
        durationMin: 4,
        text: "Press each ball with a fork, then again at a right angle, to make the classic grid. Dip the fork in sugar if it sticks.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 10,
        text: "Bake 9 to 11 minutes until the edges are lightly colored. Cool on the sheet 5 minutes, then move to a rack.",
      },
    ],
  },
];
