import type { DemoRecipe } from "./types";

export const chineseRecipes: DemoRecipe[] = [
  {
    slug: "beef-and-broccoli-stir-fry",
    cuisineSlug: "chinese",
    prepTime: 30,
    calories: 390,
    difficulty: "easy",
    servings: 4,
    title: "Beef and Broccoli Stir Fry",
    description:
      "Cantonese-style velveted flank steak and crisp broccoli in a glossy oyster-soy sauce finished with Shaoxing wine.",
    tags: ["beef", "stir-fry", "weeknight", "cantonese"],
    chefTips: [
      "Slice the flank against the grain and toss it with cornstarch and a splash of Shaoxing so it stays tender in the hot wok.",
      "Blanch the broccoli just until bright green, then stir-fry briefly so the florets stay crisp, not soggy.",
    ],
    nutrition: {
      protein: 32,
      carbs: 18,
      fat: 20,
      fiber: 4,
      sugar: 6,
      sodium: 920,
      saturatedFat: 6,
      cholesterol: 75,
    },
    ingredients: [
      { name: "Flank steak", amount: "450", unit: "g" },
      { name: "Broccoli florets", amount: "400", unit: "g" },
      { name: "Oyster sauce", amount: "2", unit: "tbsp" },
      { name: "Light soy sauce", amount: "1.5", unit: "tbsp" },
      { name: "Dark soy sauce", amount: "1", unit: "tsp" },
      { name: "Shaoxing wine", amount: "1", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Fresh ginger", amount: "15", unit: "g" },
      { name: "Cornstarch", amount: "1.5", unit: "tbsp" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Velvet the beef",
        durationMin: 10,
        text: "Slice the flank steak thin against the grain. Toss with 1 tablespoon cornstarch, Shaoxing wine, 1 teaspoon light soy, and a pinch of salt. Rest 10 minutes while you prep the sauce.",
      },
      {
        order: 2,
        title: "Blanch the broccoli",
        durationMin: 4,
        text: "Boil a pot of salted water. Blanch the broccoli 90 seconds until bright green, then drain and shock under cold water so it stays crisp.",
      },
      {
        order: 3,
        title: "Sear the beef",
        durationMin: 6,
        text: "Heat a wok until smoking. Add 2 tablespoons oil and sear the beef in a single layer until just browned, 1 to 2 minutes. Remove to a plate.",
      },
      {
        order: 4,
        title: "Sauce and toss",
        durationMin: 6,
        text: "Add remaining oil, minced garlic, and grated ginger. Stir 15 seconds. Return beef and broccoli. Stir oyster sauce, remaining light soy, dark soy, and 1 teaspoon cornstarch mixed with 60 ml water. Toss until the sauce turns glossy and coats everything. Serve at once over rice.",
      },
    ],
  },
  {
    slug: "honey-garlic-chicken",
    cuisineSlug: "chinese",
    prepTime: 35,
    calories: 430,
    difficulty: "easy",
    servings: 4,
    title: "Honey Garlic Chicken",
    description:
      "Crisp-edged chicken thighs glazed in a sticky honey-soy sauce with plenty of garlic, ginger, and a finish of sesame oil.",
    tags: ["chicken", "stir-fry", "weeknight", "sweet"],
    chefTips: [
      "Pat the thighs very dry and dust them with cornstarch so the honey glaze clings instead of sliding off.",
      "Add the honey off the highest heat so it caramelizes without scorching.",
    ],
    nutrition: {
      protein: 34,
      carbs: 28,
      fat: 20,
      fiber: 1,
      sugar: 22,
      sodium: 780,
      saturatedFat: 5,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "700", unit: "g" },
      { name: "Honey", amount: "60", unit: "ml" },
      { name: "Light soy sauce", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "5", unit: "cloves" },
      { name: "Fresh ginger", amount: "15", unit: "g" },
      { name: "Cornstarch", amount: "2", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Rice vinegar", amount: "1", unit: "tbsp" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
      { name: "Scallions", amount: "2", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Coat the chicken",
        durationMin: 8,
        text: "Cut the thighs into bite-size pieces and pat dry. Toss with cornstarch, a pinch of salt, and 1 teaspoon light soy until every piece is lightly coated.",
      },
      {
        order: 2,
        title: "Mix the glaze",
        durationMin: 3,
        text: "Stir honey, remaining soy, rice vinegar, minced garlic, and grated ginger in a small bowl until the honey dissolves.",
      },
      {
        order: 3,
        title: "Brown the chicken",
        durationMin: 12,
        text: "Heat oil in a wide skillet over medium-high heat. Cook the chicken in a single layer until deep gold on both sides and cooked through, about 10 minutes. Do not crowd the pan.",
      },
      {
        order: 4,
        title: "Glaze",
        durationMin: 5,
        text: "Pour in the honey-garlic mixture and toss over medium heat until it thickens and lacquer the chicken, 2 to 3 minutes. Finish with sesame oil and sliced scallions.",
      },
    ],
  },
  {
    slug: "orange-chicken",
    cuisineSlug: "chinese",
    prepTime: 40,
    calories: 490,
    difficulty: "medium",
    servings: 4,
    title: "Orange Chicken",
    description:
      "Crisp cornstarch-fried chicken tossed in a bright sauce of fresh orange juice and zest, soy, rice vinegar, ginger, and chili flake.",
    tags: ["chicken", "fried", "citrus", "takeout"],
    chefTips: [
      "Zest the orange before juicing it; the oils in the peel give the sauce its perfume, not just sweetness.",
      "Fry the chicken in two batches so the oil stays hot and the crust stays shatter-crisp.",
    ],
    nutrition: {
      protein: 32,
      carbs: 42,
      fat: 22,
      fiber: 1,
      sugar: 20,
      sodium: 840,
      saturatedFat: 4,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "650", unit: "g" },
      { name: "Fresh orange juice", amount: "120", unit: "ml" },
      { name: "Orange zest", amount: "2", unit: "tsp" },
      { name: "Light soy sauce", amount: "2", unit: "tbsp" },
      { name: "Rice vinegar", amount: "1.5", unit: "tbsp" },
      { name: "Fresh ginger", amount: "12", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Cornstarch", amount: "80", unit: "g" },
      { name: "Dried chili flakes", amount: "0.5", unit: "tsp" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Neutral oil", amount: "400", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Coat the chicken",
        durationMin: 8,
        text: "Cut the chicken into 3 cm pieces. Toss with a pinch of salt and 60 g cornstarch until every surface is dry and dusty.",
      },
      {
        order: 2,
        title: "Make the orange sauce",
        durationMin: 5,
        text: "Whisk orange juice, zest, soy, rice vinegar, sugar, minced garlic, grated ginger, chili flake, and remaining cornstarch mixed with 2 tablespoons water.",
      },
      {
        order: 3,
        title: "Fry until crisp",
        durationMin: 14,
        text: "Heat oil to 180 C. Fry the chicken in two batches until deep gold and cooked through, 5 to 6 minutes per batch. Drain on a rack.",
      },
      {
        order: 4,
        title: "Glaze",
        durationMin: 5,
        text: "Pour off all but 1 tablespoon oil. Add the sauce and simmer until glossy and thick. Toss in the fried chicken so every piece is coated. Serve immediately.",
      },
    ],
  },
  {
    slug: "kung-pao-shrimp",
    cuisineSlug: "chinese",
    prepTime: 30,
    calories: 340,
    difficulty: "medium",
    servings: 4,
    title: "Kung Pao Shrimp",
    description:
      "Authentic Sichuan gong bao shrimp with dried red chilies, toasted Sichuan peppercorns, Chinkiang vinegar, peanuts, and scallion — savory, numbing, and sharp, not American-sweet.",
    tags: ["shrimp", "sichuan", "spicy", "stir-fry"],
    chefTips: [
      "Bloom the dried chilies and Sichuan peppercorns in oil just until fragrant; burnt peppercorns turn bitter and lose their mala tingle.",
      "The sauce should taste sharp from Chinkiang vinegar and savory from soy, with only a pinch of sugar to round it — never sticky-sweet.",
    ],
    nutrition: {
      protein: 28,
      carbs: 12,
      fat: 18,
      fiber: 3,
      sugar: 4,
      sodium: 890,
      saturatedFat: 3,
      cholesterol: 185,
    },
    ingredients: [
      { name: "Large shrimp, peeled and deveined", amount: "500", unit: "g" },
      { name: "Dried red chilies", amount: "12", unit: "pcs" },
      { name: "Sichuan peppercorns", amount: "1", unit: "tsp" },
      { name: "Chinkiang vinegar", amount: "1.5", unit: "tbsp" },
      { name: "Light soy sauce", amount: "1.5", unit: "tbsp" },
      { name: "Dark soy sauce", amount: "0.5", unit: "tsp" },
      { name: "Shaoxing wine", amount: "1", unit: "tbsp" },
      { name: "Roasted peanuts", amount: "50", unit: "g" },
      { name: "Scallions", amount: "4", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Fresh ginger", amount: "12", unit: "g" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the shrimp",
        durationMin: 8,
        text: "Pat the shrimp dry. Toss with a pinch of salt and Shaoxing wine. Cut scallions into 3 cm lengths, keeping white and green parts separate. Snip the dried chilies in half and shake out most of the seeds.",
      },
      {
        order: 2,
        title: "Mix the gong bao sauce",
        durationMin: 3,
        text: "Stir Chinkiang vinegar, light soy, dark soy, and 1 teaspoon sugar with 1 teaspoon cornstarch and 2 tablespoons water. The mix should smell sharp and savory, not sweet.",
      },
      {
        order: 3,
        title: "Bloom chili and peppercorn",
        durationMin: 6,
        text: "Heat oil in a wok until shimmering. Add Sichuan peppercorns and dried chilies and stir 20 seconds until the oil is fragrant and the chilies darken but do not blacken. Add minced garlic, ginger, and scallion whites.",
      },
      {
        order: 4,
        title: "Stir-fry and finish",
        durationMin: 6,
        text: "Add the shrimp and stir-fry until they just turn pink, about 2 minutes. Pour in the sauce and toss until it clings. Fold in peanuts and scallion greens. Serve at once.",
      },
    ],
  },
  {
    slug: "beef-chow-fun",
    cuisineSlug: "chinese",
    prepTime: 35,
    calories: 540,
    difficulty: "hard",
    servings: 4,
    title: "Beef Chow Fun",
    description:
      "Wok-hei dry-fried ho fun with velveted flank steak, bean sprouts, Chinese chives, and a dark soy-Shaoxing seasoning — a Cantonese classic.",
    tags: ["beef", "noodles", "cantonese", "wok"],
    chefTips: [
      "Velvet the beef with baking soda and cornstarch for 15 minutes so it stays silky against the hot wok.",
      "If the fresh ho fun are stuck together, loosen them with your hands and a drizzle of oil before they hit the wok so they sear instead of steam.",
    ],
    nutrition: {
      protein: 30,
      carbs: 62,
      fat: 18,
      fiber: 3,
      sugar: 5,
      sodium: 980,
      saturatedFat: 5,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Flank steak", amount: "350", unit: "g" },
      { name: "Fresh wide ho fun (sa-ho fun)", amount: "500", unit: "g" },
      { name: "Bean sprouts", amount: "200", unit: "g" },
      { name: "Chinese chives", amount: "80", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Light soy sauce", amount: "2", unit: "tbsp" },
      { name: "Dark soy sauce", amount: "1.5", unit: "tbsp" },
      { name: "Shaoxing wine", amount: "1", unit: "tbsp" },
      { name: "Baking soda", amount: "0.25", unit: "tsp" },
      { name: "Cornstarch", amount: "1", unit: "tsp" },
      { name: "Neutral oil", amount: "4", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Velvet the beef",
        durationMin: 15,
        text: "Slice the flank thin against the grain. Toss with baking soda, cornstarch, 1 teaspoon light soy, and 1 teaspoon oil. Rest 15 minutes, then rinse briefly and pat dry if you want a cleaner flavor.",
      },
      {
        order: 2,
        title: "Loosen the noodles",
        durationMin: 4,
        text: "Gently separate the fresh ho fun by hand. If they are cold and stiff, microwave 30 seconds. Toss with 1 teaspoon oil so the strands do not clump.",
      },
      {
        order: 3,
        title: "Sear beef and noodles",
        durationMin: 8,
        text: "Heat a wok until smoking. Add 2 tablespoons oil and sear the beef 60 seconds; remove. Add remaining oil and the ho fun. Let them sit 20 seconds to pick up wok hei, then flip. Add onion slivers.",
      },
      {
        order: 4,
        title: "Season and toss",
        durationMin: 5,
        text: "Return the beef. Add remaining light soy, dark soy, and Shaoxing. Toss hard. Add bean sprouts and cut chives and toss 30 seconds more so the sprouts stay crisp. Serve immediately.",
      },
    ],
  },
  {
    slug: "chicken-lo-mein",
    cuisineSlug: "chinese",
    prepTime: 30,
    calories: 470,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Lo Mein",
    description:
      "Soft egg noodles tossed with sliced chicken, cabbage, carrot, and scallion in a savory soy-oyster sauce finished with sesame oil.",
    tags: ["chicken", "noodles", "weeknight", "cantonese"],
    chefTips: [
      "Boil the egg noodles just until they loosen, then rinse and toss with a little oil so they do not stick before the stir-fry.",
      "Keep the vegetables moving; lo mein should be glossy and savory, never soupy.",
    ],
    nutrition: {
      protein: 28,
      carbs: 52,
      fat: 16,
      fiber: 4,
      sugar: 6,
      sodium: 910,
      saturatedFat: 3,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Fresh egg noodles", amount: "400", unit: "g" },
      { name: "Boneless chicken breast", amount: "350", unit: "g" },
      { name: "Napa cabbage", amount: "200", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Scallions", amount: "3", unit: "pcs" },
      { name: "Light soy sauce", amount: "2", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1.5", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Fresh ginger", amount: "10", unit: "g" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Boil the noodles",
        durationMin: 6,
        text: "Cook the egg noodles in boiling water until just tender, 2 to 3 minutes. Drain, rinse under cold water, and toss with a few drops of sesame oil.",
      },
      {
        order: 2,
        title: "Slice and velvet",
        durationMin: 6,
        text: "Slice the chicken thin. Toss with 1 teaspoon soy and a pinch of cornstarch. Shred the cabbage, julienne the carrot, and cut the scallions into 4 cm lengths.",
      },
      {
        order: 3,
        title: "Stir-fry the chicken",
        durationMin: 8,
        text: "Heat oil in a wok. Stir-fry the chicken until just cooked, then add minced garlic and ginger. Add cabbage and carrot and toss until the cabbage wilts but still has bite.",
      },
      {
        order: 4,
        title: "Toss with noodles",
        durationMin: 5,
        text: "Add the noodles, remaining soy, oyster sauce, and sesame oil. Toss until every strand is coated and hot. Fold in the scallions and serve.",
      },
    ],
  },
  {
    slug: "shanghai-fried-noodles",
    cuisineSlug: "chinese",
    prepTime: 30,
    calories: 510,
    difficulty: "medium",
    servings: 4,
    title: "Shanghai Fried Noodles",
    description:
      "Thick Shanghai wheat noodles wok-fried with pork, napa cabbage, and a dark soy glaze until the strands are savory and slightly chewy.",
    tags: ["noodles", "pork", "shanghai", "stir-fry"],
    chefTips: [
      "Shanghai noodles are thicker than lo mein; if you cannot find them, use fresh udon and do not overcook them.",
      "Dark soy is for color and malted depth here — add it first so the noodles stain evenly before the light soy goes in.",
    ],
    nutrition: {
      protein: 26,
      carbs: 58,
      fat: 18,
      fiber: 4,
      sugar: 7,
      sodium: 1040,
      saturatedFat: 5,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Thick Shanghai wheat noodles", amount: "450", unit: "g" },
      { name: "Pork loin, thinly sliced", amount: "250", unit: "g" },
      { name: "Napa cabbage", amount: "300", unit: "g" },
      { name: "Dark soy sauce", amount: "2", unit: "tbsp" },
      { name: "Light soy sauce", amount: "1", unit: "tbsp" },
      { name: "Scallions", amount: "3", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Shaoxing wine", amount: "1", unit: "tbsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Parboil the noodles",
        durationMin: 6,
        text: "Boil the Shanghai noodles until just pliable, about 3 minutes. Drain well and toss with 1 teaspoon oil so they do not clump.",
      },
      {
        order: 2,
        title: "Prep pork and cabbage",
        durationMin: 6,
        text: "Slice the pork thin and toss with Shaoxing wine and a pinch of salt. Cut the napa into 3 cm ribbons and the scallions into 4 cm lengths.",
      },
      {
        order: 3,
        title: "Stir-fry",
        durationMin: 8,
        text: "Heat a wok until smoking. Add oil and sear the pork until it loses its pink. Add minced garlic and napa cabbage and toss until the cabbage wilts and gives off a little moisture.",
      },
      {
        order: 4,
        title: "Dark-soy the noodles",
        durationMin: 6,
        text: "Add the noodles, dark soy, light soy, and sugar. Toss until every strand is mahogany and the sauce is absorbed, not pooling. Finish with scallions.",
      },
    ],
  },
  {
    slug: "scallion-pancakes",
    cuisineSlug: "chinese",
    prepTime: 50,
    calories: 290,
    difficulty: "medium",
    servings: 4,
    title: "Scallion Pancakes",
    description:
      "Flaky, laminated Chinese cong you bing made from a hot-water dough rolled with sesame oil, salt, and a thick layer of scallions, then pan-fried until blistered.",
    tags: ["bread", "vegetarian", "snack", "street-food"],
    chefTips: [
      "Pour boiling water over the flour and stir with chopsticks; the hot water gelatinizes some starch so the pancakes stay chewy, not cracker-dry.",
      "Coil each rolled disc into a snail and rest 10 minutes before the final roll — that is what builds the layers.",
    ],
    nutrition: {
      protein: 6,
      carbs: 38,
      fat: 13,
      fiber: 2,
      sugar: 1,
      sodium: 420,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "300", unit: "g" },
      { name: "Boiling water", amount: "180", unit: "ml" },
      { name: "Scallions", amount: "6", unit: "pcs" },
      { name: "Sesame oil", amount: "3", unit: "tbsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Neutral oil", amount: "4", unit: "tbsp" },
      { name: "Cold water", amount: "30", unit: "ml" },
      { name: "White pepper", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the hot-water dough",
        durationMin: 12,
        text: "Put the flour in a bowl. Pour in the boiling water while stirring with chopsticks, then add the cold water. Knead into a smooth dough, cover, and rest 20 minutes.",
      },
      {
        order: 2,
        title: "Roll and fill",
        durationMin: 12,
        text: "Divide into 4 balls. Roll each into a thin rectangle. Brush with sesame oil, sprinkle salt, white pepper, and finely sliced scallions. Roll up into a tight log, coil into a snail, and rest 10 minutes.",
      },
      {
        order: 3,
        title: "Flatten",
        durationMin: 6,
        text: "Gently roll each coil into a 18 cm disc. Do not press so hard that the scallions tear through.",
      },
      {
        order: 4,
        title: "Pan-fry",
        durationMin: 12,
        text: "Heat 1 tablespoon neutral oil in a skillet over medium heat. Fry each pancake 2 to 3 minutes per side until blistered and gold, pressing lightly so the layers steam. Cut into wedges and serve hot.",
      },
    ],
  },
  {
    slug: "steamed-fish-with-ginger",
    cuisineSlug: "chinese",
    prepTime: 25,
    calories: 240,
    difficulty: "easy",
    servings: 4,
    title: "Steamed Fish with Ginger",
    description:
      "Cantonese steamed white fish blanketed in ginger julienne and scallion, finished with hot oil and a light soy-Shaoxing dressing.",
    tags: ["fish", "steamed", "cantonese", "light"],
    chefTips: [
      "The fish is done when a chopstick slides easily into the thickest part and the flesh is pearly, not opaque-dry — usually 8 to 10 minutes.",
      "Pour smoking-hot oil over the ginger and scallion at the table so they sizzle and perfume the fish.",
    ],
    nutrition: {
      protein: 32,
      carbs: 4,
      fat: 10,
      fiber: 1,
      sugar: 2,
      sodium: 720,
      saturatedFat: 2,
      cholesterol: 70,
    },
    ingredients: [
      { name: "White fish fillets (sea bass or cod)", amount: "700", unit: "g" },
      { name: "Fresh ginger", amount: "40", unit: "g" },
      { name: "Scallions", amount: "4", unit: "pcs" },
      { name: "Light soy sauce", amount: "2.5", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Shaoxing wine", amount: "1", unit: "tbsp" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
      { name: "Sugar", amount: "0.5", unit: "tsp" },
      { name: "Cilantro", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the fish",
        durationMin: 8,
        text: "Pat the fillets dry and lay them on a heatproof plate. Julienne the ginger and scallions into fine threads. Scatter half the ginger over the fish and splash with Shaoxing wine.",
      },
      {
        order: 2,
        title: "Steam",
        durationMin: 10,
        text: "Bring a wok or steamer to a hard boil. Steam the fish over high heat 8 to 10 minutes, until the flesh flakes. Pour off any watery juices on the plate.",
      },
      {
        order: 3,
        title: "Dress",
        durationMin: 3,
        text: "Stir light soy, sugar, and sesame oil. Pour over the fish. Pile the remaining ginger and all the scallion on top.",
      },
      {
        order: 4,
        title: "Sizzle with hot oil",
        durationMin: 2,
        text: "Heat the neutral oil until it just smokes. Pour it over the ginger and scallion so they wilt and crackle. Garnish with cilantro and serve immediately.",
      },
    ],
  },
  {
    slug: "hot-and-sour-soup",
    cuisineSlug: "chinese",
    prepTime: 35,
    calories: 190,
    difficulty: "medium",
    servings: 4,
    title: "Hot and Sour Soup",
    description:
      "A Sichuan-style suan la tang of pork, wood ear, lily flowers, tofu, and egg in a broth sharpened with Chinkiang vinegar and a heavy hand of white pepper.",
    tags: ["soup", "pork", "sichuan", "spicy"],
    chefTips: [
      "White pepper, not chili oil, is the heat in a proper hot and sour soup — add it at the end so it stays aromatic.",
      "Stream the beaten egg in a thin ribbon while you stir the soup in one direction for long, silky threads.",
    ],
    nutrition: {
      protein: 16,
      carbs: 10,
      fat: 9,
      fiber: 2,
      sugar: 2,
      sodium: 980,
      saturatedFat: 2,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Pork loin, julienned", amount: "150", unit: "g" },
      { name: "Firm tofu", amount: "200", unit: "g" },
      { name: "Dried wood ear mushrooms", amount: "15", unit: "g" },
      { name: "Dried lily flowers", amount: "15", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "White pepper", amount: "1.5", unit: "tsp" },
      { name: "Chinkiang vinegar", amount: "3", unit: "tbsp" },
      { name: "Cornstarch", amount: "2", unit: "tbsp" },
      { name: "Chicken broth", amount: "1.2", unit: "l" },
      { name: "Light soy sauce", amount: "2", unit: "tbsp" },
      { name: "Bamboo shoots", amount: "80", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak the dried goods",
        durationMin: 12,
        text: "Cover wood ear and lily flowers with hot water and soak 15 minutes. Trim tough ends from the lily flowers, slice the wood ear thin, and julienne the tofu and bamboo shoots.",
      },
      {
        order: 2,
        title: "Simmer the broth",
        durationMin: 8,
        text: "Bring the chicken broth to a boil. Add pork, wood ear, lily flowers, bamboo, and tofu. Season with soy. Simmer 5 minutes.",
      },
      {
        order: 3,
        title: "Thicken",
        durationMin: 4,
        text: "Stir cornstarch with 60 ml cold water and drizzle it into the simmering soup while stirring. The broth should turn lightly glossy, not gluey.",
      },
      {
        order: 4,
        title: "Egg, vinegar, and pepper",
        durationMin: 5,
        text: "Beat the eggs and stream them in while stirring slowly. Turn off the heat. Stir in Chinkiang vinegar and white pepper. Taste — it should be sharply sour and tingling-hot. Serve at once.",
      },
    ],
  },
  {
    slug: "egg-drop-soup",
    cuisineSlug: "chinese",
    prepTime: 15,
    calories: 95,
    difficulty: "easy",
    servings: 4,
    title: "Egg Drop Soup",
    description:
      "A clear chicken broth thickened just enough to hold silky egg ribbons, seasoned with white pepper, sesame oil, and scallion.",
    tags: ["soup", "egg", "quick", "light"],
    chefTips: [
      "Stir the broth in one direction and pour the egg from a height in a thin stream so you get ribbons, not scrambled clumps.",
      "White pepper is the classic seasoning; black pepper will taste wrong here.",
    ],
    nutrition: {
      protein: 7,
      carbs: 4,
      fat: 5,
      fiber: 0,
      sugar: 1,
      sodium: 640,
      saturatedFat: 1,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Chicken broth", amount: "1", unit: "l" },
      { name: "Eggs", amount: "3", unit: "pcs" },
      { name: "White pepper", amount: "0.5", unit: "tsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Cornstarch", amount: "1.5", unit: "tbsp" },
      { name: "Scallions", amount: "2", unit: "pcs" },
      { name: "Light soy sauce", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Heat the broth",
        durationMin: 5,
        text: "Bring the chicken broth to a gentle simmer. Season with salt, soy, and white pepper.",
      },
      {
        order: 2,
        title: "Thicken lightly",
        durationMin: 3,
        text: "Stir cornstarch with 40 ml cold water and drizzle it into the broth. Simmer 1 minute until the soup is barely silky.",
      },
      {
        order: 3,
        title: "Ribbon the eggs",
        durationMin: 3,
        text: "Beat the eggs. Stir the soup in one direction and pour the eggs in a thin stream. Stop stirring and let the ribbons set 20 seconds.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Turn off the heat. Stir in sesame oil and finely sliced scallions. Serve immediately.",
      },
    ],
  },
  {
    slug: "chinese-bbq-pork-buns",
    cuisineSlug: "chinese",
    prepTime: 150,
    calories: 310,
    difficulty: "hard",
    servings: 8,
    title: "Chinese BBQ Pork Buns",
    description:
      "Soft steamed yeast buns filled with diced char siu pork in a hoisin-oyster sauce, a Cantonese dim sum classic.",
    tags: ["pork", "dim-sum", "steamed", "bao"],
    chefTips: [
      "The dough should be slightly tacky and well-kneaded so the bao bake up snowy and smooth, not wrinkly.",
      "Cool the filling completely before wrapping or the steam will make the dough soggy and it will tear.",
    ],
    nutrition: {
      protein: 14,
      carbs: 42,
      fat: 9,
      fiber: 2,
      sugar: 10,
      sodium: 520,
      saturatedFat: 3,
      cholesterol: 30,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "400", unit: "g" },
      { name: "Instant yeast", amount: "7", unit: "g" },
      { name: "Sugar", amount: "50", unit: "g" },
      { name: "Char siu pork, diced", amount: "300", unit: "g" },
      { name: "Hoisin sauce", amount: "2", unit: "tbsp" },
      { name: "Char siu sauce", amount: "1", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Warm water", amount: "200", unit: "ml" },
      { name: "Cornstarch", amount: "1", unit: "tbsp" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the yeast dough",
        durationMin: 15,
        text: "Mix flour, yeast, 40 g sugar, and a pinch of salt. Add warm water and oil and knead 8 minutes until smooth. Cover and rise until doubled, about 1 hour.",
      },
      {
        order: 2,
        title: "Cook the filling",
        durationMin: 10,
        text: "Stir diced char siu with hoisin, char siu sauce, oyster sauce, remaining sugar, sesame oil, and cornstarch mixed with 60 ml water. Simmer until thick and glossy. Cool completely.",
      },
      {
        order: 3,
        title: "Shape the buns",
        durationMin: 20,
        text: "Punch down the dough and divide into 8 pieces. Roll each into a 10 cm disc, thicker in the center. Spoon 2 tablespoons filling into the middle, pleat the edges, and pinch closed.",
      },
      {
        order: 4,
        title: "Proof",
        durationMin: 20,
        text: "Set each bun on a square of parchment. Cover and proof 20 minutes until slightly puffy.",
      },
      {
        order: 5,
        title: "Steam",
        durationMin: 15,
        text: "Steam over high heat 12 minutes. Turn off the heat and rest 2 minutes before lifting the lid so the buns do not collapse. Serve hot.",
      },
    ],
  },
  {
    slug: "sesame-chicken",
    cuisineSlug: "chinese",
    prepTime: 40,
    calories: 460,
    difficulty: "medium",
    servings: 4,
    title: "Sesame Chicken",
    description:
      "Crisp fried chicken tossed in a honey-soy-rice vinegar glaze and finished with toasted sesame seeds and garlic.",
    tags: ["chicken", "fried", "sesame", "takeout"],
    chefTips: [
      "Toast the sesame seeds in a dry pan until they smell nutty; raw seeds taste flat on the glaze.",
      "The sauce should be glossy and just thick enough to coat — if it sits and turns gummy, loosen it with a splash of water.",
    ],
    nutrition: {
      protein: 33,
      carbs: 36,
      fat: 20,
      fiber: 1,
      sugar: 18,
      sodium: 800,
      saturatedFat: 4,
      cholesterol: 125,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "650", unit: "g" },
      { name: "Light soy sauce", amount: "3", unit: "tbsp" },
      { name: "Rice vinegar", amount: "1.5", unit: "tbsp" },
      { name: "Honey", amount: "50", unit: "ml" },
      { name: "Sesame seeds", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Cornstarch", amount: "70", unit: "g" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Neutral oil", amount: "400", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Batter the chicken",
        durationMin: 8,
        text: "Cut the chicken into bite-size pieces. Toss with the beaten egg, 1 tablespoon soy, and cornstarch until a thin batter clings.",
      },
      {
        order: 2,
        title: "Mix the glaze",
        durationMin: 3,
        text: "Stir remaining soy, rice vinegar, honey, minced garlic, and 1 teaspoon cornstarch mixed with 2 tablespoons water.",
      },
      {
        order: 3,
        title: "Fry",
        durationMin: 14,
        text: "Heat oil to 180 C. Fry the chicken in batches until deep gold and cooked through, 5 to 6 minutes. Drain. Toast the sesame seeds in a dry pan until fragrant.",
      },
      {
        order: 4,
        title: "Toss and seed",
        durationMin: 5,
        text: "Pour off the oil. Simmer the glaze until glossy, toss in the chicken, and finish with sesame oil and the toasted seeds. Serve immediately.",
      },
    ],
  },
  {
    slug: "salt-and-pepper-shrimp",
    cuisineSlug: "chinese",
    prepTime: 25,
    calories: 330,
    difficulty: "medium",
    servings: 4,
    title: "Salt and Pepper Shrimp",
    description:
      "Shell-on shrimp dusted in cornstarch and flash-fried, then tossed with garlic, chili, and toasted Sichuan pepper-salt.",
    tags: ["shrimp", "fried", "sichuan", "spicy"],
    chefTips: [
      "Leave the shells on; they crisp like chips and keep the meat juicy. Diners can eat the shells or peel as they go.",
      "Toast Sichuan peppercorns and salt together, then grind — pre-ground pepper loses the citrus-numbing aroma.",
    ],
    nutrition: {
      protein: 26,
      carbs: 10,
      fat: 18,
      fiber: 1,
      sugar: 1,
      sodium: 780,
      saturatedFat: 3,
      cholesterol: 190,
    },
    ingredients: [
      { name: "Large shrimp, shell-on", amount: "600", unit: "g" },
      { name: "Sichuan peppercorns", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Garlic", amount: "5", unit: "cloves" },
      { name: "Fresh red chili", amount: "2", unit: "pcs" },
      { name: "Cornstarch", amount: "50", unit: "g" },
      { name: "Neutral oil", amount: "400", unit: "ml" },
      { name: "Scallions", amount: "2", unit: "pcs" },
      { name: "White pepper", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make pepper-salt",
        durationMin: 5,
        text: "Toast Sichuan peppercorns in a dry pan 1 minute until fragrant. Grind with the salt and white pepper. Devein the shrimp but keep the shells on. Pat very dry.",
      },
      {
        order: 2,
        title: "Dust",
        durationMin: 3,
        text: "Toss the shrimp with cornstarch so a thin, even coat sticks. Shake off the excess.",
      },
      {
        order: 3,
        title: "Flash-fry",
        durationMin: 8,
        text: "Heat oil to 190 C. Fry the shrimp 2 minutes until the shells blister and turn coral. Drain on a rack.",
      },
      {
        order: 4,
        title: "Toss with garlic and chili",
        durationMin: 4,
        text: "Pour off all but 1 tablespoon oil. Stir-fry minced garlic, sliced chili, and scallion 20 seconds. Return the shrimp, shower with pepper-salt, and toss hard. Serve at once.",
      },
    ],
  },
  {
    slug: "cucumber-garlic-salad",
    cuisineSlug: "chinese",
    prepTime: 20,
    calories: 85,
    difficulty: "easy",
    servings: 4,
    title: "Cucumber Garlic Salad",
    description:
      "Smashed cucumbers in a sharp dressing of garlic, Chinkiang vinegar, soy, sesame oil, sugar, and chili oil — a cold northern Chinese starter.",
    tags: ["salad", "vegetarian", "cold", "appetizer"],
    chefTips: [
      "Smash the cucumbers with the side of a cleaver so they split and drink the dressing; sliced rounds stay watery and bland.",
      "Salt the smashed pieces 10 minutes and pour off the liquid or the salad will dilute itself.",
    ],
    nutrition: {
      protein: 2,
      carbs: 8,
      fat: 6,
      fiber: 1,
      sugar: 5,
      sodium: 480,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Persian or English cucumbers", amount: "600", unit: "g" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Chinkiang vinegar", amount: "2", unit: "tbsp" },
      { name: "Light soy sauce", amount: "1", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tbsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Chili oil", amount: "1", unit: "tbsp" },
      { name: "Kosher salt", amount: "0.75", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Smash the cucumbers",
        durationMin: 5,
        text: "Trim the ends. Lay each cucumber on a board and smash with the side of a cleaver until it splits. Break into bite-size chunks.",
      },
      {
        order: 2,
        title: "Salt and drain",
        durationMin: 10,
        text: "Toss with the salt and rest 10 minutes. Pour off the released liquid and pat the pieces dry.",
      },
      {
        order: 3,
        title: "Make the dressing",
        durationMin: 3,
        text: "Mince the garlic to a paste. Stir with Chinkiang vinegar, soy, sugar, sesame oil, and chili oil until the sugar dissolves.",
      },
      {
        order: 4,
        title: "Toss and rest",
        durationMin: 2,
        text: "Toss the cucumbers in the dressing. Taste for salt and vinegar. Serve immediately or chill 10 minutes so the garlic blooms.",
      },
    ],
  },
];
