import type { DemoRecipe } from "./types";

export const frenchRecipes: DemoRecipe[] = [
  {
    slug: "chicken-fricassee",
    cuisineSlug: "french",
    prepTime: 75,
    calories: 520,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Fricassée",
    description:
      "A classic French fricassée of chicken and mushrooms in a white-wine cream sauce finished with egg yolks and tarragon.",
    tags: ["chicken", "stew", "french", "comfort"],
    chefTips: [
      "Keep the chicken pale — a fricassée is a white stew, so brown only lightly.",
      "Temper the egg yolks with hot sauce before adding them so the liaison does not scramble.",
    ],
    nutrition: {
      protein: 38,
      carbs: 12,
      fat: 34,
      fiber: 2,
      sugar: 4,
      sodium: 720,
      saturatedFat: 16,
      cholesterol: 210,
    },
    ingredients: [
      { name: "Bone-in chicken pieces", amount: "1.5", unit: "kg" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
      { name: "Onion", amount: "1", unit: "pcs" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Celery", amount: "1", unit: "stalk" },
      { name: "Cremini mushrooms", amount: "250", unit: "g" },
      { name: "All-purpose flour", amount: "2", unit: "tbsp" },
      { name: "Dry white wine", amount: "160", unit: "ml" },
      { name: "Chicken broth", amount: "500", unit: "ml" },
      { name: "Heavy cream", amount: "80", unit: "ml" },
      { name: "Egg yolks", amount: "2", unit: "pcs" },
      { name: "Fresh tarragon", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Sear the chicken",
        durationMin: 12,
        text: "Season the chicken. Melt butter with a splash of oil in a Dutch oven and cook the pieces until pale gold on both sides. Transfer to a plate.",
      },
      {
        order: 2,
        title: "Cook the vegetables",
        durationMin: 10,
        text: "Sweat diced onion, carrot, and celery in the same pot. Add quartered mushrooms and cook until they give off their moisture. Sprinkle in the flour and stir for 1 minute.",
      },
      {
        order: 3,
        title: "Braise",
        durationMin: 35,
        text: "Deglaze with white wine, add broth, thyme, and a bay leaf. Return the chicken, cover, and simmer gently until the meat is tender.",
      },
      {
        order: 4,
        title: "Finish the liaison",
        durationMin: 8,
        text: "Whisk cream with egg yolks. Temper with a ladle of hot sauce, then stir back into the pot off the heat. Add lemon juice and chopped tarragon. Do not boil.",
      },
    ],
  },
  {
    slug: "duck-a-lorange",
    cuisineSlug: "french",
    prepTime: 50,
    calories: 610,
    difficulty: "hard",
    servings: 4,
    title: "Duck à l’Orange",
    description:
      "Crisp duck with a bittersweet orange sauce of stock, marmalade, vinegar, and a splash of orange liqueur.",
    tags: ["duck", "french", "dinner", "classic"],
    chefTips: [
      "Score the skin in a crosshatch and start the duck skin-side down so the fat renders slowly.",
      "Seville orange marmalade gives the sauce its traditional bitter edge.",
    ],
    nutrition: {
      protein: 36,
      carbs: 18,
      fat: 42,
      fiber: 1,
      sugar: 14,
      sodium: 640,
      saturatedFat: 14,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Duck breasts", amount: "4", unit: "pcs" },
      { name: "Chicken or duck stock", amount: "240", unit: "ml" },
      { name: "Orange liqueur", amount: "2", unit: "tbsp" },
      { name: "Sherry vinegar", amount: "1", unit: "tbsp" },
      { name: "Seville orange marmalade", amount: "2", unit: "tbsp" },
      { name: "Orange zest", amount: "2", unit: "tsp" },
      { name: "Orange juice", amount: "80", unit: "ml" },
      { name: "All-purpose flour", amount: "1", unit: "tsp" },
      { name: "Unsalted butter", amount: "15", unit: "g" },
      { name: "Salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Score and season",
        durationMin: 15,
        text: "Score the duck skin in a crosshatch without cutting the meat. Salt generously and rest at room temperature for 15 minutes.",
      },
      {
        order: 2,
        title: "Render the duck",
        durationMin: 14,
        text: "Cook skin-side down over medium heat until the fat renders and the skin is deep gold, about 8 minutes. Flip and cook to medium, then rest.",
      },
      {
        order: 3,
        title: "Make the orange sauce",
        durationMin: 8,
        text: "Pour off most of the fat. Whisk flour into the pan, then add stock, orange juice, liqueur, vinegar, marmalade, and zest. Reduce until glossy.",
      },
      {
        order: 4,
        title: "Mount with butter",
        durationMin: 3,
        text: "Take the sauce off the heat and swirl in butter. Slice the duck and spoon the orange sauce over the top.",
      },
    ],
  },
  {
    slug: "beef-daube",
    cuisineSlug: "french",
    prepTime: 210,
    calories: 580,
    difficulty: "medium",
    servings: 6,
    title: "Beef Daube",
    description:
      "A Provençal beef stew marinated in red wine with orange peel, olives, thyme, and garlic, then slowly braised.",
    tags: ["beef", "stew", "provencal", "make-ahead"],
    chefTips: [
      "Marinate the beef overnight in the wine, orange peel, and herbs for a deeper Provençal flavor.",
      "Stir in the olives near the end so they stay briny rather than mushy.",
    ],
    nutrition: {
      protein: 42,
      carbs: 16,
      fat: 32,
      fiber: 3,
      sugar: 6,
      sodium: 890,
      saturatedFat: 11,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Beef chuck", amount: "1.2", unit: "kg" },
      { name: "Red wine", amount: "750", unit: "ml" },
      { name: "Bacon or salt pork", amount: "100", unit: "g" },
      { name: "Carrots", amount: "3", unit: "pcs" },
      { name: "Onions", amount: "2", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Tomato paste", amount: "1", unit: "tbsp" },
      { name: "Orange peel", amount: "3", unit: "strips" },
      { name: "Niçoise olives", amount: "80", unit: "g" },
      { name: "Fresh thyme", amount: "4", unit: "sprigs" },
      { name: "Bay leaves", amount: "2", unit: "pcs" },
      { name: "Juniper berries", amount: "4", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate the beef",
        durationMin: 20,
        text: "Cube the chuck and toss with wine, orange peel, thyme, bay, garlic, and juniper. Refrigerate several hours or overnight, then drain and pat dry, reserving the marinade.",
      },
      {
        order: 2,
        title: "Brown the meat",
        durationMin: 15,
        text: "Render the bacon, then brown the beef in batches. Sweat the onions and carrots and stir in tomato paste.",
      },
      {
        order: 3,
        title: "Braise",
        durationMin: 150,
        text: "Return the beef, pour in the reserved marinade, and add a little stock if needed. Cover and cook in a 160°C oven until fork-tender, about 2½ hours.",
      },
      {
        order: 4,
        title: "Finish with olives",
        durationMin: 10,
        text: "Stir in the olives and simmer 10 minutes. Skim fat, season, and serve with mashed potatoes or crusty bread.",
      },
    ],
  },
  {
    slug: "chicken-provencal",
    cuisineSlug: "french",
    prepTime: 60,
    calories: 470,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Provençal",
    description:
      "Braised chicken with tomatoes, olives, garlic, peppers, and herbes de Provence in a light white-wine sauce.",
    tags: ["chicken", "provencal", "olives", "weeknight"],
    chefTips: [
      "Use bone-in thighs so the sauce stays moist while the skin crisps first.",
      "A handful of niçoise olives is enough — they should punctuate the sauce, not dominate it.",
    ],
    nutrition: {
      protein: 36,
      carbs: 14,
      fat: 28,
      fiber: 3,
      sugar: 7,
      sodium: 780,
      saturatedFat: 7,
      cholesterol: 140,
    },
    ingredients: [
      { name: "Chicken thighs", amount: "8", unit: "pcs" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "6", unit: "cloves" },
      { name: "Ripe tomatoes", amount: "400", unit: "g" },
      { name: "Red bell pepper", amount: "1", unit: "pcs" },
      { name: "Dry white wine", amount: "120", unit: "ml" },
      { name: "Niçoise olives", amount: "60", unit: "g" },
      { name: "Herbes de Provence", amount: "2", unit: "tsp" },
      { name: "Fresh thyme", amount: "4", unit: "sprigs" },
      { name: "Capers", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Brown the chicken",
        durationMin: 12,
        text: "Season the thighs and brown them skin-side down in olive oil until the skin is crisp. Transfer to a plate.",
      },
      {
        order: 2,
        title: "Build the sauce",
        durationMin: 8,
        text: "Sauté sliced garlic and pepper strips. Add chopped tomatoes, wine, herbes de Provence, and thyme. Simmer 3 minutes.",
      },
      {
        order: 3,
        title: "Braise",
        durationMin: 30,
        text: "Nestle the chicken back into the sauce, cover, and cook until the meat is tender and the sauce has thickened.",
      },
      {
        order: 4,
        title: "Add olives",
        durationMin: 5,
        text: "Stir in olives and capers. Taste for salt and serve with rice or roasted potatoes.",
      },
    ],
  },
  {
    slug: "french-crepes",
    cuisineSlug: "french",
    prepTime: 40,
    calories: 280,
    difficulty: "easy",
    servings: 6,
    title: "French Crepes",
    description:
      "Thin sweet crêpes made with flour, eggs, milk, and butter, ready for sugar, jam, or Nutella.",
    tags: ["dessert", "breakfast", "crepes", "easy"],
    chefTips: [
      "Rest the batter at least 30 minutes so the flour hydrates and the crêpes stay tender.",
      "The first crêpe is the test — adjust the pan heat until it sets in about a minute.",
    ],
    nutrition: {
      protein: 8,
      carbs: 34,
      fat: 12,
      fiber: 1,
      sugar: 10,
      sodium: 180,
      saturatedFat: 7,
      cholesterol: 95,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "150", unit: "g" },
      { name: "Eggs", amount: "3", unit: "pcs" },
      { name: "Whole milk", amount: "350", unit: "ml" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
      { name: "Salt", amount: "1", unit: "pinch" },
      { name: "Lemon", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Blend the batter",
        durationMin: 5,
        text: "Whisk flour, sugar, and salt. Add eggs, then gradually whisk in milk, melted butter, and vanilla until smooth. Rest 30 minutes.",
      },
      {
        order: 2,
        title: "Heat the pan",
        durationMin: 2,
        text: "Warm a lightly buttered crêpe pan over medium heat until a drop of batter sizzles.",
      },
      {
        order: 3,
        title: "Cook the crêpes",
        durationMin: 20,
        text: "Pour a thin ladle of batter, swirl, and cook until the edges lift. Flip and cook 20 seconds more. Stack on a plate.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 3,
        text: "Fold or roll with sugar and lemon, jam, or chocolate. Serve warm.",
      },
    ],
  },
  {
    slug: "galette-bretonne",
    cuisineSlug: "french",
    prepTime: 35,
    calories: 420,
    difficulty: "medium",
    servings: 4,
    title: "Galette Bretonne",
    description:
      "A savory buckwheat galette from Brittany, classically filled with ham, cheese, and a fried egg.",
    tags: ["buckwheat", "savory", "breton", "lunch"],
    chefTips: [
      "Buckwheat batter should be thin and rest so the galette stays lacy and crisp.",
      "Crack the egg into the center and fold the four sides in to make the classic square.",
    ],
    nutrition: {
      protein: 22,
      carbs: 28,
      fat: 24,
      fiber: 4,
      sugar: 2,
      sodium: 860,
      saturatedFat: 10,
      cholesterol: 230,
    },
    ingredients: [
      { name: "Buckwheat flour", amount: "150", unit: "g" },
      { name: "Water", amount: "350", unit: "ml" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Salt", amount: "1", unit: "tsp" },
      { name: "Unsalted butter", amount: "30", unit: "g" },
      { name: "Ham slices", amount: "4", unit: "pcs" },
      { name: "Gruyère", amount: "80", unit: "g" },
      { name: "Eggs for filling", amount: "4", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the batter",
        durationMin: 5,
        text: "Whisk buckwheat flour, water, one egg, and salt until smooth. Rest 20 minutes. The batter should pour like heavy cream.",
      },
      {
        order: 2,
        title: "Cook the galette",
        durationMin: 4,
        text: "Heat a well-buttered crepe pan. Pour a thin layer of batter and cook until the surface looks dry and the edges crisp.",
      },
      {
        order: 3,
        title: "Fill",
        durationMin: 4,
        text: "Lay ham and grated Gruyère in the center, crack an egg on top, and fold in the four sides. Cover briefly so the white sets and the yolk stays runny.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Slide onto a plate and serve immediately, one galette per person.",
      },
    ],
  },
  {
    slug: "potato-gratin",
    cuisineSlug: "french",
    prepTime: 75,
    calories: 390,
    difficulty: "easy",
    servings: 6,
    title: "Potato Gratin",
    description:
      "Sliced potatoes baked in cream and garlic under a golden blanket of Gruyère.",
    tags: ["potato", "side", "gratin", "comfort"],
    chefTips: [
      "Slice the potatoes evenly, about 3 mm, so they cook at the same pace.",
      "Let the gratin rest 10 minutes before cutting so the cream sets.",
    ],
    nutrition: {
      protein: 12,
      carbs: 32,
      fat: 24,
      fiber: 3,
      sugar: 3,
      sodium: 420,
      saturatedFat: 15,
      cholesterol: 75,
    },
    ingredients: [
      { name: "Yukon Gold potatoes", amount: "1.2", unit: "kg" },
      { name: "Heavy cream", amount: "400", unit: "ml" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Gruyère", amount: "120", unit: "g" },
      { name: "Unsalted butter", amount: "20", unit: "g" },
      { name: "Nutmeg", amount: "1", unit: "pinch" },
      { name: "Salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the dish",
        durationMin: 10,
        text: "Heat the oven to 180°C. Rub a baking dish with butter and a cut garlic clove. Slice the potatoes thinly.",
      },
      {
        order: 2,
        title: "Layer",
        durationMin: 10,
        text: "Layer potatoes with salt, pepper, nutmeg, and most of the Gruyère. Pour over cream until the slices are just covered.",
      },
      {
        order: 3,
        title: "Bake",
        durationMin: 50,
        text: "Top with remaining cheese and bake until the potatoes are tender and the top is deeply golden.",
      },
      {
        order: 4,
        title: "Rest",
        durationMin: 10,
        text: "Rest 10 minutes so the cream thickens, then serve.",
      },
    ],
  },
  {
    slug: "gratin-dauphinois",
    cuisineSlug: "french",
    prepTime: 80,
    calories: 360,
    difficulty: "medium",
    servings: 6,
    title: "Gratin Dauphinois",
    description:
      "The traditional Dauphiné gratin of potatoes baked slowly in garlic-scented cream and milk, without a heavy cheese crust.",
    tags: ["potato", "classic", "side", "dauphine"],
    chefTips: [
      "Authentic gratin dauphinois uses cream and milk, not a béchamel, and traditionally little or no cheese.",
      "Do not rinse the sliced potatoes — the surface starch helps the cream set.",
    ],
    nutrition: {
      protein: 8,
      carbs: 34,
      fat: 22,
      fiber: 3,
      sugar: 4,
      sodium: 380,
      saturatedFat: 14,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Waxy potatoes", amount: "1.2", unit: "kg" },
      { name: "Heavy cream", amount: "300", unit: "ml" },
      { name: "Whole milk", amount: "200", unit: "ml" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Unsalted butter", amount: "20", unit: "g" },
      { name: "Nutmeg", amount: "1", unit: "pinch" },
      { name: "Fresh thyme", amount: "2", unit: "sprigs" },
      { name: "Salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Infuse the cream",
        durationMin: 10,
        text: "Warm cream and milk with smashed garlic, thyme, nutmeg, and salt. Rub a gratin dish with butter and garlic.",
      },
      {
        order: 2,
        title: "Slice and layer",
        durationMin: 10,
        text: "Slice potatoes 3 mm thick and arrange in overlapping layers. Do not rinse them.",
      },
      {
        order: 3,
        title: "Bake slowly",
        durationMin: 55,
        text: "Pour the warm cream over the potatoes. Bake at 160°C until a knife slides through and the top is lightly browned.",
      },
      {
        order: 4,
        title: "Rest",
        durationMin: 10,
        text: "Rest 10 minutes before serving so the cream sets into a silky custard.",
      },
    ],
  },
  {
    slug: "ratatouille-tart",
    cuisineSlug: "french",
    prepTime: 70,
    calories: 340,
    difficulty: "medium",
    servings: 6,
    title: "Ratatouille Tart",
    description:
      "Puff pastry topped with a Provençal ratatouille of eggplant, zucchini, peppers, and tomato.",
    tags: ["vegetarian", "tart", "provencal", "dinner"],
    chefTips: [
      "Cook the vegetables separately first so they roast instead of steaming into mush.",
      "Score a border on the pastry and dock the center so the edges puff.",
    ],
    nutrition: {
      protein: 7,
      carbs: 32,
      fat: 20,
      fiber: 5,
      sugar: 8,
      sodium: 420,
      saturatedFat: 8,
      cholesterol: 15,
    },
    ingredients: [
      { name: "Puff pastry", amount: "1", unit: "sheet" },
      { name: "Eggplant", amount: "1", unit: "pcs" },
      { name: "Zucchini", amount: "1", unit: "pcs" },
      { name: "Red bell pepper", amount: "1", unit: "pcs" },
      { name: "Ripe tomatoes", amount: "3", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Olive oil", amount: "4", unit: "tbsp" },
      { name: "Fresh thyme", amount: "1", unit: "tsp" },
      { name: "Egg", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Roast the vegetables",
        durationMin: 25,
        text: "Toss cubed eggplant, zucchini, and pepper with olive oil, garlic, and thyme. Roast at 200°C until browned. Stir in chopped tomato.",
      },
      {
        order: 2,
        title: "Prep the pastry",
        durationMin: 8,
        text: "Roll the puff pastry onto a tray. Score a 2 cm border and prick the center with a fork. Brush the border with beaten egg.",
      },
      {
        order: 3,
        title: "Fill and bake",
        durationMin: 25,
        text: "Spoon the ratatouille inside the border. Bake until the pastry is puffed and deep gold.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 5,
        text: "Cool 5 minutes, then slice. A drizzle of olive oil and extra thyme finishes it.",
      },
    ],
  },
  {
    slug: "french-lentil-salad",
    cuisineSlug: "french",
    prepTime: 40,
    calories: 310,
    difficulty: "easy",
    servings: 4,
    title: "French Lentil Salad",
    description:
      "Warm Puy lentils dressed with Dijon, shallot, parsley, and red-wine vinegar.",
    tags: ["lentils", "salad", "vegetarian", "make-ahead"],
    chefTips: [
      "Use French green Puy lentils — they hold their shape and stay peppery.",
      "Dress the lentils while they are still warm so they absorb the vinaigrette.",
    ],
    nutrition: {
      protein: 14,
      carbs: 36,
      fat: 12,
      fiber: 10,
      sugar: 4,
      sodium: 380,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Puy lentils", amount: "250", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Bay leaf", amount: "1", unit: "pcs" },
      { name: "Shallot", amount: "1", unit: "pcs" },
      { name: "Dijon mustard", amount: "1", unit: "tbsp" },
      { name: "Red wine vinegar", amount: "2", unit: "tbsp" },
      { name: "Extra virgin olive oil", amount: "4", unit: "tbsp" },
      { name: "Flat-leaf parsley", amount: "20", unit: "g" },
      { name: "Salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the lentils",
        durationMin: 25,
        text: "Simmer Puy lentils with a carrot and bay leaf in salted water until tender but still intact, 20 to 25 minutes. Drain.",
      },
      {
        order: 2,
        title: "Make the vinaigrette",
        durationMin: 5,
        text: "Whisk Dijon, vinegar, minced shallot, olive oil, salt, and pepper.",
      },
      {
        order: 3,
        title: "Dress while warm",
        durationMin: 5,
        text: "Toss the drained lentils with the vinaigrette and chopped parsley.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Serve warm or at room temperature. It keeps well for lunch the next day.",
      },
    ],
  },
  {
    slug: "salmon-en-papillote",
    cuisineSlug: "french",
    prepTime: 30,
    calories: 380,
    difficulty: "easy",
    servings: 4,
    title: "Salmon en Papillote",
    description:
      "Salmon steamed in parchment with lemon, fennel, white wine, and herbs.",
    tags: ["salmon", "healthy", "quick", "french"],
    chefTips: [
      "Seal the parchment tightly so the packet puffs with steam.",
      "Open the packets at the table — the aroma is half the dish.",
    ],
    nutrition: {
      protein: 32,
      carbs: 6,
      fat: 24,
      fiber: 2,
      sugar: 3,
      sodium: 420,
      saturatedFat: 5,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Salmon fillets", amount: "4", unit: "pcs" },
      { name: "Fennel bulb", amount: "1", unit: "pcs" },
      { name: "Lemon", amount: "1", unit: "pcs" },
      { name: "Dry white wine", amount: "80", unit: "ml" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
      { name: "Fresh dill", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Salt", amount: "1", unit: "tsp" },
      { name: "Parchment paper", amount: "4", unit: "sheets" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the packets",
        durationMin: 10,
        text: "Heat the oven to 200°C. Thinly slice fennel and lemon. Place a bed of fennel on each parchment heart.",
      },
      {
        order: 2,
        title: "Season the salmon",
        durationMin: 5,
        text: "Set a fillet on the fennel. Add lemon slices, garlic, dill, olive oil, wine, salt, and pepper.",
      },
      {
        order: 3,
        title: "Seal and bake",
        durationMin: 14,
        text: "Fold and crimp the parchment tightly. Bake 12 to 14 minutes until the packets puff and the salmon is just opaque.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Transfer packets to plates and slit them open at the table.",
      },
    ],
  },
  {
    slug: "moules-marinieres",
    cuisineSlug: "french",
    prepTime: 25,
    calories: 290,
    difficulty: "easy",
    servings: 4,
    title: "Moules Marinières",
    description:
      "Mussels steamed with shallot, white wine, butter, parsley, and thyme — the classic mariner's pot.",
    tags: ["mussels", "seafood", "quick", "french"],
    chefTips: [
      "Discard any mussels that stay open before cooking or stay closed after steaming.",
      "Serve with plenty of bread or frites to soak up the wine broth.",
    ],
    nutrition: {
      protein: 24,
      carbs: 10,
      fat: 14,
      fiber: 0,
      sugar: 2,
      sodium: 780,
      saturatedFat: 7,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Mussels", amount: "2", unit: "kg" },
      { name: "Shallots", amount: "3", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Dry white wine", amount: "250", unit: "ml" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
      { name: "Fresh parsley", amount: "20", unit: "g" },
      { name: "Fresh thyme", amount: "2", unit: "sprigs" },
      { name: "Bay leaf", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Clean the mussels",
        durationMin: 8,
        text: "Scrub the mussels, pull the beards, and discard any that stay open when tapped.",
      },
      {
        order: 2,
        title: "Sweat the shallots",
        durationMin: 4,
        text: "Melt butter in a wide pot. Cook minced shallot and garlic until soft. Add thyme and bay.",
      },
      {
        order: 3,
        title: "Steam",
        durationMin: 6,
        text: "Add the wine and mussels, cover, and steam over high heat, shaking the pot, until the shells open, 4 to 6 minutes.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Discard unopened mussels. Toss with chopped parsley and serve in bowls with the broth.",
      },
    ],
  },
  {
    slug: "pissaladiere",
    cuisineSlug: "french",
    prepTime: 90,
    calories: 360,
    difficulty: "medium",
    servings: 8,
    title: "Pissaladière",
    description:
      "A Niçoise onion tart on bread dough, topped with slowly caramelized onions, anchovies, and niçoise olives.",
    tags: ["onion", "anchovy", "provencal", "tart"],
    chefTips: [
      "Cook the onions low and slow for 40 minutes — they should be jammy, not browned hard.",
      "Arrange the anchovies in a lattice and place an olive in each diamond.",
    ],
    nutrition: {
      protein: 10,
      carbs: 42,
      fat: 16,
      fiber: 3,
      sugar: 8,
      sodium: 780,
      saturatedFat: 3,
      cholesterol: 12,
    },
    ingredients: [
      { name: "Bread flour", amount: "300", unit: "g" },
      { name: "Instant yeast", amount: "7", unit: "g" },
      { name: "Olive oil", amount: "5", unit: "tbsp" },
      { name: "Yellow onions", amount: "1.2", unit: "kg" },
      { name: "Anchovy fillets", amount: "12", unit: "pcs" },
      { name: "Niçoise olives", amount: "40", unit: "g" },
      { name: "Fresh thyme", amount: "1", unit: "tsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the dough",
        durationMin: 15,
        text: "Mix flour, yeast, salt, water, and 2 tablespoons olive oil. Knead until smooth and let rise until doubled.",
      },
      {
        order: 2,
        title: "Caramelize the onions",
        durationMin: 40,
        text: "Cook thinly sliced onions in olive oil with a pinch of sugar and thyme over low heat until soft, sweet, and golden, about 40 minutes.",
      },
      {
        order: 3,
        title: "Assemble",
        durationMin: 10,
        text: "Press the dough into an oiled tray. Spread the onions, lattice the anchovies, and stud with olives.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 25,
        text: "Bake at 220°C until the crust is golden. Cool slightly and cut into squares.",
      },
    ],
  },
  {
    slug: "madeleines",
    cuisineSlug: "french",
    prepTime: 45,
    calories: 140,
    difficulty: "medium",
    servings: 8,
    title: "Madeleines",
    description:
      "Small scallop-shaped sponge cakes scented with lemon and browned butter.",
    tags: ["cake", "dessert", "tea", "french"],
    chefTips: [
      "Chill the batter so the cakes rise into the classic hump.",
      "Butter and flour the madeleine molds generously so they release cleanly.",
    ],
    nutrition: {
      protein: 3,
      carbs: 16,
      fat: 7,
      fiber: 0,
      sugar: 10,
      sodium: 70,
      saturatedFat: 4,
      cholesterol: 45,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "110", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Sugar", amount: "100", unit: "g" },
      { name: "Unsalted butter", amount: "100", unit: "g" },
      { name: "Lemon zest", amount: "1", unit: "tsp" },
      { name: "Baking powder", amount: "1", unit: "tsp" },
      { name: "Vanilla extract", amount: "0.5", unit: "tsp" },
      { name: "Salt", amount: "1", unit: "pinch" },
    ],
    steps: [
      {
        order: 1,
        title: "Brown the butter",
        durationMin: 6,
        text: "Melt the butter until it smells nutty and the milk solids turn gold. Cool slightly.",
      },
      {
        order: 2,
        title: "Make the batter",
        durationMin: 8,
        text: "Whisk eggs and sugar until pale. Fold in flour, baking powder, salt, lemon zest, vanilla, and the browned butter. Chill 30 minutes.",
      },
      {
        order: 3,
        title: "Bake",
        durationMin: 12,
        text: "Butter and flour madeleine molds. Fill each well two-thirds full. Bake at 190°C until the humps are set and the edges are golden, 10 to 12 minutes.",
      },
      {
        order: 4,
        title: "Unmold",
        durationMin: 3,
        text: "Tap out while warm and dust with sugar if you like. Best eaten the same day.",
      },
    ],
  },
  {
    slug: "profiteroles",
    cuisineSlug: "french",
    prepTime: 55,
    calories: 320,
    difficulty: "medium",
    servings: 8,
    title: "Profiteroles",
    description:
      "Crisp choux puffs filled with vanilla ice cream and napped with warm dark-chocolate sauce.",
    tags: ["dessert", "choux", "chocolate", "french"],
    chefTips: [
      "Dry the choux dough in the pan until it leaves a film, then beat in eggs one at a time.",
      "Poke a small hole in baked puffs so steam escapes and they stay crisp.",
    ],
    nutrition: {
      protein: 6,
      carbs: 32,
      fat: 18,
      fiber: 2,
      sugar: 20,
      sodium: 140,
      saturatedFat: 10,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Water", amount: "125", unit: "ml" },
      { name: "Whole milk", amount: "125", unit: "ml" },
      { name: "Unsalted butter", amount: "100", unit: "g" },
      { name: "All-purpose flour", amount: "140", unit: "g" },
      { name: "Eggs", amount: "4", unit: "pcs" },
      { name: "Vanilla ice cream", amount: "500", unit: "ml" },
      { name: "Dark chocolate", amount: "150", unit: "g" },
      { name: "Heavy cream", amount: "150", unit: "ml" },
      { name: "Sugar", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the panade",
        durationMin: 8,
        text: "Bring water, milk, butter, sugar, and a pinch of salt to a boil. Add the flour all at once and stir over the heat until the dough pulls away from the pan.",
      },
      {
        order: 2,
        title: "Add the eggs",
        durationMin: 8,
        text: "Cool 2 minutes, then beat in eggs one at a time until the dough is glossy and holds a soft peak.",
      },
      {
        order: 3,
        title: "Bake the puffs",
        durationMin: 25,
        text: "Pipe small mounds onto a tray. Bake at 200°C until puffed and deep gold. Pierce and dry 5 minutes more.",
      },
      {
        order: 4,
        title: "Fill and sauce",
        durationMin: 8,
        text: "Melt chocolate with cream for the sauce. Split the puffs, fill with vanilla ice cream, and pour the warm chocolate over the top.",
      },
    ],
  },
];
