import type { DemoRecipe } from "./types";

export const indianRecipes: DemoRecipe[] = [
  {
    slug: "chicken-tikka-masala",
    cuisineSlug: "indian",
    prepTime: 70,
    calories: 520,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Tikka Masala",
    description:
      "Tandoori-style yogurt-marinated chicken in a buttery tomato-cream gravy finished with kasuri methi and garam masala.",
    tags: ["chicken", "curry", "dinner", "north-indian"],
    chefTips: [
      "Char the marinated chicken under a hot broiler or in a cast-iron pan so you get smoky tikka edges before it goes into the gravy.",
      "Crush kasuri methi between your palms as you add it; the heat wakes the fenugreek aroma.",
    ],
    nutrition: {
      protein: 38,
      carbs: 14,
      fat: 34,
      fiber: 3,
      sugar: 8,
      sodium: 780,
      saturatedFat: 16,
      cholesterol: 155,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "700", unit: "g" },
      { name: "Plain yogurt", amount: "150", unit: "g" },
      { name: "Garam masala", amount: "2", unit: "tsp" },
      { name: "Kashmiri chili powder", amount: "2", unit: "tsp" },
      { name: "Ginger-garlic paste", amount: "2", unit: "tbsp" },
      { name: "Canned tomatoes", amount: "400", unit: "g" },
      { name: "Heavy cream", amount: "120", unit: "ml" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
      { name: "Kasuri methi", amount: "1", unit: "tbsp" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate the chicken",
        durationMin: 15,
        text: "Toss the chicken with yogurt, 1 teaspoon garam masala, 1 teaspoon Kashmiri chili, half the ginger-garlic paste, and a pinch of salt. Rest at least 30 minutes, or overnight in the fridge.",
      },
      {
        order: 2,
        title: "Char the tikka",
        durationMin: 12,
        text: "Broil or pan-sear the marinated chicken until the edges are charred and it is just cooked through. Set aside.",
      },
      {
        order: 3,
        title: "Cook the gravy",
        durationMin: 20,
        text: "Melt butter and cook finely chopped onion until golden. Add the remaining ginger-garlic paste, cumin, and remaining Kashmiri chili. Stir in crushed tomatoes and simmer until the oil separates and the sauce is thick.",
      },
      {
        order: 4,
        title: "Finish with cream",
        durationMin: 10,
        text: "Stir in cream, remaining garam masala, and crushed kasuri methi. Add the chicken and simmer 8 minutes so the tikka drinks the gravy. Taste for salt and serve with naan or rice.",
      },
    ],
  },
  {
    slug: "chicken-korma",
    cuisineSlug: "indian",
    prepTime: 65,
    calories: 560,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Korma",
    description:
      "A pale ivory Mughlai curry of chicken simmered in fried-onion birista, yogurt, and cashew-almond paste, finished with ghee and garam masala. No tomato.",
    tags: ["chicken", "curry", "mughlai", "mild"],
    chefTips: [
      "Blend the birista with a splash of water until completely smooth; any onion bits will muddy the ivory gravy.",
      "Whisk the yogurt before it hits the pan and keep the heat low so it does not split.",
    ],
    nutrition: {
      protein: 36,
      carbs: 12,
      fat: 40,
      fiber: 2,
      sugar: 5,
      sodium: 640,
      saturatedFat: 14,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Bone-in chicken pieces", amount: "800", unit: "g" },
      { name: "Fried onions (birista)", amount: "80", unit: "g" },
      { name: "Plain yogurt", amount: "200", unit: "g" },
      { name: "Cashews", amount: "40", unit: "g" },
      { name: "Blanched almonds", amount: "30", unit: "g" },
      { name: "Garam masala", amount: "1", unit: "tsp" },
      { name: "Green chili", amount: "2", unit: "pcs" },
      { name: "Ghee", amount: "40", unit: "g" },
      { name: "Ginger-garlic paste", amount: "1.5", unit: "tbsp" },
      { name: "Green cardamom", amount: "4", unit: "pcs" },
      { name: "Cinnamon stick", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the nut paste",
        durationMin: 10,
        text: "Soak cashews and almonds in hot water 10 minutes, then grind with the birista and a little water to a pale, silky paste.",
      },
      {
        order: 2,
        title: "Seal the chicken",
        durationMin: 12,
        text: "Heat ghee and bloom cardamom and cinnamon. Add the chicken and ginger-garlic paste and sauté until the chicken turns white and the raw smell is gone. Slit the green chilies and add them.",
      },
      {
        order: 3,
        title: "Build the korma",
        durationMin: 25,
        text: "Lower the heat. Stir in whisked yogurt a spoonful at a time, then the nut-onion paste. Add a splash of water, cover, and simmer until the chicken is tender and the gravy is pale ivory.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 5,
        text: "Stir in garam masala and a last teaspoon of ghee. The gravy should be thick enough to coat a spoon, never red. Rest 5 minutes before serving.",
      },
    ],
  },
  {
    slug: "lamb-vindaloo",
    cuisineSlug: "indian",
    prepTime: 100,
    calories: 540,
    difficulty: "hard",
    servings: 4,
    title: "Lamb Vindaloo",
    description:
      "A Goan vindaloo of lamb shoulder in a sharp, deep-red masala of dried chilies, vinegar, garlic, ginger, and warm whole spices.",
    tags: ["lamb", "goan", "spicy", "curry"],
    chefTips: [
      "Marinate the lamb in the ground chili-vinegar paste overnight; the acid tenderizes the shoulder and builds the classic sour heat.",
    ],
    nutrition: {
      protein: 40,
      carbs: 8,
      fat: 38,
      fiber: 2,
      sugar: 2,
      sodium: 720,
      saturatedFat: 14,
      cholesterol: 140,
    },
    ingredients: [
      { name: "Lamb shoulder", amount: "800", unit: "g" },
      { name: "Dried Kashmiri red chilies", amount: "12", unit: "pcs" },
      { name: "White vinegar", amount: "80", unit: "ml" },
      { name: "Garlic", amount: "8", unit: "cloves" },
      { name: "Fresh ginger", amount: "30", unit: "g" },
      { name: "Cumin seeds", amount: "2", unit: "tsp" },
      { name: "Black mustard seeds", amount: "1", unit: "tsp" },
      { name: "Whole cloves", amount: "6", unit: "pcs" },
      { name: "Cinnamon stick", amount: "1", unit: "pcs" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Coconut oil", amount: "40", unit: "ml" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Grind the masala",
        durationMin: 15,
        text: "Soak the dried red chilies in warm water 10 minutes. Grind them with vinegar, garlic, ginger, cumin, mustard seeds, cloves, cinnamon, and turmeric to a thick, pungent paste.",
      },
      {
        order: 2,
        title: "Marinate the lamb",
        durationMin: 10,
        text: "Cut the lamb shoulder into 4 cm cubes. Coat thoroughly with the masala and salt. Rest at least 1 hour, preferably overnight.",
      },
      {
        order: 3,
        title: "Sear and braise",
        durationMin: 70,
        text: "Heat coconut oil in a heavy pot. Brown the marinated lamb in batches, then return it all with any remaining paste and a splash of water. Cover and braise on low heat until the meat is fork-tender, 60 to 70 minutes.",
      },
      {
        order: 4,
        title: "Reduce the gravy",
        durationMin: 8,
        text: "Uncover and cook until the oil rises and the gravy is dark, sharp, and clinging. Taste; add a splash more vinegar if you want extra tang. Rest 10 minutes before serving.",
      },
    ],
  },
  {
    slug: "matar-paneer",
    cuisineSlug: "indian",
    prepTime: 40,
    calories: 420,
    difficulty: "medium",
    servings: 4,
    title: "Matar Paneer",
    description:
      "Soft paneer and sweet green peas in a home-style onion-tomato masala with cumin, ginger-garlic, and garam masala.",
    tags: ["paneer", "vegetarian", "curry", "north-indian"],
    chefTips: [
      "Soak store-bought paneer in warm salted water for 10 minutes so it stays soft in the gravy.",
    ],
    nutrition: {
      protein: 20,
      carbs: 18,
      fat: 28,
      fiber: 5,
      sugar: 8,
      sodium: 680,
      saturatedFat: 14,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Paneer", amount: "400", unit: "g" },
      { name: "Green peas", amount: "200", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Ripe tomatoes", amount: "3", unit: "pcs" },
      { name: "Cumin seeds", amount: "1", unit: "tsp" },
      { name: "Garam masala", amount: "1", unit: "tsp" },
      { name: "Ginger-garlic paste", amount: "1", unit: "tbsp" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Kashmiri chili powder", amount: "1", unit: "tsp" },
      { name: "Mustard oil", amount: "30", unit: "ml" },
      { name: "Cilantro", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the masala",
        durationMin: 15,
        text: "Heat mustard oil until it smokes lightly, then cool a moment. Bloom cumin seeds, add finely chopped onion, and cook until golden. Stir in ginger-garlic paste, turmeric, and chili powder.",
      },
      {
        order: 2,
        title: "Cook the tomatoes",
        durationMin: 10,
        text: "Add chopped tomatoes and salt. Cook until they break down and the oil separates from the masala.",
      },
      {
        order: 3,
        title: "Add peas and paneer",
        durationMin: 10,
        text: "Stir in the green peas and a splash of water. Simmer 5 minutes, then add cubed paneer and garam masala. Cook gently 4 minutes so the paneer absorbs the sauce.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Scatter chopped cilantro over the top. Serve with roti or jeera rice.",
      },
    ],
  },
  {
    slug: "shahi-paneer",
    cuisineSlug: "indian",
    prepTime: 45,
    calories: 510,
    difficulty: "medium",
    servings: 4,
    title: "Shahi Paneer",
    description:
      "A royal Mughlai paneer curry in a silky tomato-cashew gravy enriched with cream, ghee, cardamom, and a drop of kewra.",
    tags: ["paneer", "vegetarian", "mughlai", "rich"],
    chefTips: [
      "Blend the tomato-cashew base until completely smooth, then strain for the restaurant-style velvet texture.",
    ],
    nutrition: {
      protein: 18,
      carbs: 16,
      fat: 40,
      fiber: 2,
      sugar: 8,
      sodium: 620,
      saturatedFat: 18,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Paneer", amount: "400", unit: "g" },
      { name: "Ripe tomatoes", amount: "3", unit: "pcs" },
      { name: "Cashews", amount: "50", unit: "g" },
      { name: "Heavy cream", amount: "100", unit: "ml" },
      { name: "Ghee", amount: "30", unit: "g" },
      { name: "Green cardamom", amount: "4", unit: "pcs" },
      { name: "Kewra water", amount: "0.5", unit: "tsp" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Ginger-garlic paste", amount: "1", unit: "tbsp" },
      { name: "Kashmiri chili powder", amount: "1", unit: "tsp" },
      { name: "Garam masala", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the base",
        durationMin: 15,
        text: "Heat ghee and bloom crushed cardamom. Soften chopped onion, then add ginger-garlic paste and chili powder. Add chopped tomatoes and soaked cashews and cook until the tomatoes collapse.",
      },
      {
        order: 2,
        title: "Blend the gravy",
        durationMin: 8,
        text: "Cool slightly, blend until velvet-smooth, and strain back into the pan. Simmer 5 minutes with a splash of water.",
      },
      {
        order: 3,
        title: "Add paneer and cream",
        durationMin: 8,
        text: "Slide in the paneer cubes and simmer gently 5 minutes. Stir in cream and garam masala; do not boil hard.",
      },
      {
        order: 4,
        title: "Perfume and serve",
        durationMin: 2,
        text: "Turn off the heat and add kewra water. Rest 3 minutes so the floral note settles, then serve.",
      },
    ],
  },
  {
    slug: "rajma-masala",
    cuisineSlug: "indian",
    prepTime: 90,
    calories: 380,
    difficulty: "medium",
    servings: 4,
    title: "Rajma Masala",
    description:
      "Punjabi kidney beans in a thick onion-tomato gravy with cumin, coriander, garam masala, and kasuri methi.",
    tags: ["beans", "vegetarian", "punjabi", "comfort"],
    chefTips: [
      "Mash a ladle of beans into the gravy near the end; that is what makes Punjabi rajma thick and clinging.",
    ],
    nutrition: {
      protein: 18,
      carbs: 48,
      fat: 12,
      fiber: 14,
      sugar: 7,
      sodium: 640,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Dried red kidney beans", amount: "300", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Ripe tomatoes", amount: "3", unit: "pcs" },
      { name: "Ginger-garlic paste", amount: "1.5", unit: "tbsp" },
      { name: "Cumin seeds", amount: "1", unit: "tsp" },
      { name: "Ground coriander", amount: "2", unit: "tsp" },
      { name: "Garam masala", amount: "1", unit: "tsp" },
      { name: "Kasuri methi", amount: "1", unit: "tbsp" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Kashmiri chili powder", amount: "1", unit: "tsp" },
      { name: "Mustard oil", amount: "30", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak and boil the beans",
        durationMin: 50,
        text: "Soak the kidney beans overnight. Pressure-cook with salt and a pinch of turmeric until completely soft, about 25 minutes under pressure, then keep the cooking liquid.",
      },
      {
        order: 2,
        title: "Fry the masala",
        durationMin: 18,
        text: "Heat mustard oil, bloom cumin seeds, and fry finely chopped onion until deep brown. Add ginger-garlic paste, coriander, chili powder, and turmeric. Stir in chopped tomatoes and cook until the oil separates.",
      },
      {
        order: 3,
        title: "Simmer the rajma",
        durationMin: 18,
        text: "Add the beans and enough cooking liquid to make a thick gravy. Simmer 15 minutes. Mash some beans against the side of the pot.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 4,
        text: "Stir in garam masala and crushed kasuri methi. Rest 5 minutes. Serve with steamed rice.",
      },
    ],
  },
  {
    slug: "baingan-bharta",
    cuisineSlug: "indian",
    prepTime: 50,
    calories: 220,
    difficulty: "medium",
    servings: 4,
    title: "Baingan Bharta",
    description:
      "Fire-roasted eggplant mashed with onion, tomato, ginger-garlic, cumin seeds, turmeric, and garam masala, finished with cilantro.",
    tags: ["eggplant", "vegetarian", "punjabi", "smoky"],
    chefTips: [
      "Roast the eggplant directly over a gas flame or under a broiler until the skin is black and the flesh collapses; that smoke is the dish.",
    ],
    nutrition: {
      protein: 5,
      carbs: 20,
      fat: 14,
      fiber: 8,
      sugar: 10,
      sodium: 520,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Large globe eggplant", amount: "800", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Ripe tomato", amount: "2", unit: "pcs" },
      { name: "Ginger-garlic paste", amount: "1", unit: "tbsp" },
      { name: "Cumin seeds", amount: "1", unit: "tsp" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Garam masala", amount: "1", unit: "tsp" },
      { name: "Cilantro", amount: "15", unit: "g" },
      { name: "Green chili", amount: "2", unit: "pcs" },
      { name: "Mustard oil", amount: "30", unit: "ml" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Fire-roast the eggplant",
        durationMin: 20,
        text: "Prick the eggplant and roast over an open flame or under a hot broiler, turning, until the skin is charred and the flesh is soft, 15 to 20 minutes. Cool, peel, and mash roughly. Keep a few charred bits.",
      },
      {
        order: 2,
        title: "Temper the spices",
        durationMin: 8,
        text: "Heat mustard oil and bloom cumin seeds. Add chopped onion and green chili and cook until the onion is golden. Stir in ginger-garlic paste and turmeric.",
      },
      {
        order: 3,
        title: "Cook the tomato",
        durationMin: 8,
        text: "Add chopped tomato and salt. Cook until the tomato is jammy and the oil shows at the edges.",
      },
      {
        order: 4,
        title: "Mash and finish",
        durationMin: 8,
        text: "Add the mashed eggplant and cook, stirring, until it dries a little and takes on the masala, 6 to 8 minutes. Stir in garam masala and chopped cilantro.",
      },
    ],
  },
  {
    slug: "jeera-rice",
    cuisineSlug: "indian",
    prepTime: 30,
    calories: 280,
    difficulty: "easy",
    servings: 4,
    title: "Jeera Rice",
    description:
      "Fluffy aged basmati tempered in ghee with cumin seeds, bay leaf, and a few whole spices.",
    tags: ["rice", "side", "vegetarian", "quick"],
    chefTips: [
      "Rinse the basmati until the water runs clear, then soak 20 minutes so the grains cook long and separate.",
    ],
    nutrition: {
      protein: 5,
      carbs: 48,
      fat: 8,
      fiber: 1,
      sugar: 0,
      sodium: 380,
      saturatedFat: 4,
      cholesterol: 15,
    },
    ingredients: [
      { name: "Aged basmati rice", amount: "300", unit: "g" },
      { name: "Cumin seeds", amount: "2", unit: "tsp" },
      { name: "Ghee", amount: "30", unit: "g" },
      { name: "Bay leaf", amount: "2", unit: "pcs" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Green cardamom", amount: "3", unit: "pcs" },
      { name: "Whole cloves", amount: "3", unit: "pcs" },
      { name: "Black peppercorns", amount: "6", unit: "pcs" },
      { name: "Water", amount: "540", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Rinse and soak",
        durationMin: 5,
        text: "Rinse the basmati until the water is clear. Soak 20 minutes, then drain well.",
      },
      {
        order: 2,
        title: "Temper the jeera",
        durationMin: 4,
        text: "Heat ghee in a heavy pot. Add cumin seeds, bay leaf, cardamom, cloves, and peppercorns. When the cumin darkens and smells toasty, about 30 seconds, you are ready.",
      },
      {
        order: 3,
        title: "Toast the rice",
        durationMin: 3,
        text: "Add the drained rice and salt. Stir gently 1 to 2 minutes so every grain is coated in ghee.",
      },
      {
        order: 4,
        title: "Steam",
        durationMin: 18,
        text: "Pour in the water, bring to a boil, then cover and cook on the lowest heat 12 minutes. Rest off the heat 5 minutes, then fluff with a fork.",
      },
    ],
  },
  {
    slug: "vegetable-pulao",
    cuisineSlug: "indian",
    prepTime: 40,
    calories: 340,
    difficulty: "easy",
    servings: 4,
    title: "Vegetable Pulao",
    description:
      "One-pot basmati cooked with mixed vegetables and whole spices — bay, cinnamon, cloves, and cardamom — in ghee.",
    tags: ["rice", "vegetarian", "one-pot", "weeknight"],
    chefTips: [
      "Fry the whole spices in ghee until they crackle before adding onion; that bloom is what makes pulao smell like a feast.",
    ],
    nutrition: {
      protein: 7,
      carbs: 54,
      fat: 10,
      fiber: 4,
      sugar: 4,
      sodium: 420,
      saturatedFat: 5,
      cholesterol: 15,
    },
    ingredients: [
      { name: "Aged basmati rice", amount: "300", unit: "g" },
      { name: "Mixed vegetables", amount: "250", unit: "g" },
      { name: "Bay leaf", amount: "2", unit: "pcs" },
      { name: "Cinnamon stick", amount: "1", unit: "pcs" },
      { name: "Whole cloves", amount: "4", unit: "pcs" },
      { name: "Green cardamom", amount: "4", unit: "pcs" },
      { name: "Ghee", amount: "30", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Fresh ginger", amount: "15", unit: "g" },
      { name: "Cumin seeds", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the rice",
        durationMin: 5,
        text: "Rinse and soak the basmati 20 minutes. Drain. Cut the mixed vegetables into even 1 cm pieces.",
      },
      {
        order: 2,
        title: "Bloom the spices",
        durationMin: 8,
        text: "Heat ghee and add bay leaf, cinnamon, cloves, cardamom, and cumin seeds. When they crackle, add sliced onion and julienned ginger and cook until the onion is light gold.",
      },
      {
        order: 3,
        title: "Add vegetables and rice",
        durationMin: 5,
        text: "Stir in the vegetables for 2 minutes, then the drained rice and salt. Toast 1 minute.",
      },
      {
        order: 4,
        title: "Cook",
        durationMin: 18,
        text: "Add 540 ml water, bring to a boil, cover, and cook on low 12 minutes. Rest 5 minutes, fluff, and serve.",
      },
    ],
  },
  {
    slug: "pani-puri",
    cuisineSlug: "indian",
    prepTime: 45,
    calories: 210,
    difficulty: "medium",
    servings: 6,
    title: "Pani Puri",
    description:
      "Crisp puris filled with spiced potato and chickpeas, dunked in mint-coriander pani and a sweet-sour tamarind chutney.",
    tags: ["chaat", "street-food", "snack", "vegetarian"],
    chefTips: [
      "Chill the pani with ice and a pinch of black salt just before serving; cold, sharp water is what makes pani puri addictive.",
    ],
    nutrition: {
      protein: 6,
      carbs: 36,
      fat: 6,
      fiber: 4,
      sugar: 8,
      sodium: 540,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Pani puri shells", amount: "30", unit: "pcs" },
      { name: "Boiled potato", amount: "3", unit: "pcs" },
      { name: "Cooked chickpeas", amount: "200", unit: "g" },
      { name: "Seedless tamarind", amount: "40", unit: "g" },
      { name: "Fresh mint leaves", amount: "30", unit: "g" },
      { name: "Cilantro", amount: "30", unit: "g" },
      { name: "Chaat masala", amount: "2", unit: "tsp" },
      { name: "Black salt", amount: "1", unit: "tsp" },
      { name: "Green chili", amount: "2", unit: "pcs" },
      { name: "Roasted cumin powder", amount: "1", unit: "tsp" },
      { name: "Jaggery", amount: "20", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the tamarind chutney",
        durationMin: 12,
        text: "Soak the tamarind in hot water, mash, and strain. Simmer the pulp with jaggery, a pinch of cumin, and salt until syrupy. Cool.",
      },
      {
        order: 2,
        title: "Blend the pani",
        durationMin: 10,
        text: "Blend mint, cilantro, green chili, chaat masala, black salt, and roasted cumin with 400 ml cold water. Strain. Taste; it should be sharp, herby, and a little salty.",
      },
      {
        order: 3,
        title: "Make the filling",
        durationMin: 8,
        text: "Mash the boiled potatoes roughly and mix with chickpeas, a pinch of chaat masala, and salt.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 10,
        text: "Crack a hole in each puri, spoon in potato-chickpea filling, add a drop of tamarind chutney, and fill with chilled pani. Eat immediately.",
      },
    ],
  },
  {
    slug: "pakora-platter",
    cuisineSlug: "indian",
    prepTime: 35,
    calories: 320,
    difficulty: "easy",
    servings: 6,
    title: "Pakora Platter",
    description:
      "A mixed platter of onion, potato, and spinach fritters in a gram-flour batter scented with ajwain and green chili.",
    tags: ["snack", "fried", "vegetarian", "monsoon"],
    chefTips: [
      "Keep the batter thick enough to cling, and fry at 175°C so the pakoras stay crisp instead of greasy.",
    ],
    nutrition: {
      protein: 8,
      carbs: 32,
      fat: 18,
      fiber: 5,
      sugar: 5,
      sodium: 480,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Gram flour (besan)", amount: "200", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Potato", amount: "2", unit: "pcs" },
      { name: "Fresh spinach", amount: "80", unit: "g" },
      { name: "Ajwain (carom seeds)", amount: "1", unit: "tsp" },
      { name: "Green chili", amount: "2", unit: "pcs" },
      { name: "Mustard oil", amount: "600", unit: "ml" },
      { name: "Kashmiri chili powder", amount: "1", unit: "tsp" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Cold water", amount: "140", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Slice the vegetables",
        durationMin: 10,
        text: "Thinly slice the onions, cut the potatoes into 3 mm rounds, and roughly chop the spinach. Finely chop the green chilies.",
      },
      {
        order: 2,
        title: "Make the batter",
        durationMin: 5,
        text: "Whisk gram flour with ajwain, chili powder, turmeric, salt, and enough cold water to make a thick batter that coats a spoon. Fold in the onions, spinach, and chili for mixed pakoras; dip potato slices separately.",
      },
      {
        order: 3,
        title: "Fry",
        durationMin: 15,
        text: "Heat mustard oil to 175°C. Drop spoonfuls of the mixed batter and the coated potato slices. Fry until deep gold and crisp, 3 to 4 minutes per batch. Drain on a rack.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Sprinkle with chaat masala if you have it and serve hot with mint chutney.",
      },
    ],
  },
  {
    slug: "dhokla",
    cuisineSlug: "indian",
    prepTime: 40,
    calories: 180,
    difficulty: "medium",
    servings: 8,
    title: "Dhokla",
    description:
      "A Gujarati steamed gram-flour cake leavened with yogurt and Eno, tempered with mustard seeds, curry leaves, and green chili.",
    tags: ["gujarati", "snack", "steamed", "vegetarian"],
    chefTips: [
      "Stir in the Eno fruit salt at the last second and steam immediately; if you wait, the batter goes flat.",
    ],
    nutrition: {
      protein: 7,
      carbs: 24,
      fat: 6,
      fiber: 3,
      sugar: 5,
      sodium: 360,
      saturatedFat: 1,
      cholesterol: 5,
    },
    ingredients: [
      { name: "Gram flour (besan)", amount: "200", unit: "g" },
      { name: "Plain yogurt", amount: "150", unit: "g" },
      { name: "Eno fruit salt", amount: "1", unit: "tsp" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Mustard seeds", amount: "1", unit: "tsp" },
      { name: "Curry leaves", amount: "12", unit: "leaves" },
      { name: "Green chili", amount: "2", unit: "pcs" },
      { name: "Granulated sugar", amount: "2", unit: "tsp" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Lemon juice", amount: "1", unit: "tbsp" },
      { name: "White sesame seeds", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the batter",
        durationMin: 10,
        text: "Whisk gram flour, yogurt, turmeric, sugar, salt, lemon juice, 1 tablespoon oil, and 80 ml water to a smooth, pourable batter. Rest 10 minutes.",
      },
      {
        order: 2,
        title: "Steam",
        durationMin: 18,
        text: "Grease a 20 cm tin. Stir Eno into the batter; it will foam. Pour immediately and steam 15 to 18 minutes until a toothpick comes out clean. Cool 5 minutes, then cut into squares.",
      },
      {
        order: 3,
        title: "Temper",
        durationMin: 5,
        text: "Heat the remaining oil. Add mustard seeds, sesame, slit green chilies, and curry leaves. When they crackle, add 80 ml water and a pinch of sugar and bring to a brief boil.",
      },
      {
        order: 4,
        title: "Soak and serve",
        durationMin: 5,
        text: "Pour the hot tempering over the cut dhokla so it soaks in. Serve slightly warm or at room temperature.",
      },
    ],
  },
  {
    slug: "naan-bread",
    cuisineSlug: "indian",
    prepTime: 90,
    calories: 260,
    difficulty: "medium",
    servings: 6,
    title: "Naan Bread",
    description:
      "Soft leavened maida flatbreads with yogurt in the dough, blistered in a hot pan, brushed with ghee, and finished with nigella seeds.",
    tags: ["bread", "tandoor", "side", "north-indian"],
    chefTips: [
      "Roll the naan slightly oval and slap it onto a screaming-hot cast-iron pan; cover for 30 seconds so it puffs like a tandoor bread.",
    ],
    nutrition: {
      protein: 7,
      carbs: 42,
      fat: 7,
      fiber: 1,
      sugar: 3,
      sodium: 320,
      saturatedFat: 3,
      cholesterol: 12,
    },
    ingredients: [
      { name: "Maida (all-purpose flour)", amount: "400", unit: "g" },
      { name: "Plain yogurt", amount: "80", unit: "g" },
      { name: "Instant yeast", amount: "5", unit: "g" },
      { name: "Nigella seeds", amount: "2", unit: "tsp" },
      { name: "Ghee", amount: "40", unit: "g" },
      { name: "Warm milk", amount: "120", unit: "ml" },
      { name: "Granulated sugar", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Baking powder", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the dough",
        durationMin: 15,
        text: "Stir yeast and sugar into the warm milk. Mix flour, salt, baking powder, yogurt, and the yeasty milk into a soft dough. Knead 8 minutes, work in 1 tablespoon ghee, and rest covered until doubled, about 1 hour.",
      },
      {
        order: 2,
        title: "Divide and roll",
        durationMin: 10,
        text: "Divide into 6 balls. Roll each into a 6 mm oval. Brush lightly with water and scatter nigella seeds, pressing them in.",
      },
      {
        order: 3,
        title: "Cook",
        durationMin: 18,
        text: "Heat a cast-iron pan until very hot. Cook each naan seed-side up 1 to 2 minutes until bubbles form, then flip or hold over the flame to char the top. Repeat.",
      },
      {
        order: 4,
        title: "Brush with ghee",
        durationMin: 3,
        text: "Brush the hot naan with melted ghee as they come off the pan. Stack under a cloth so they stay soft.",
      },
    ],
  },
  {
    slug: "rasmalai",
    cuisineSlug: "indian",
    prepTime: 90,
    calories: 290,
    difficulty: "hard",
    servings: 8,
    title: "Rasmalai",
    description:
      "Soft chenna discs poached like rasgulla, then soaked in saffron-cardamom reduced milk and finished with pistachios.",
    tags: ["dessert", "bengali", "milk", "festive"],
    chefTips: [
      "Knead the chenna until it is smooth and just oily; under-kneaded discs crack, over-kneaded ones turn rubbery.",
    ],
    nutrition: {
      protein: 12,
      carbs: 28,
      fat: 14,
      fiber: 0,
      sugar: 26,
      sodium: 80,
      saturatedFat: 8,
      cholesterol: 45,
    },
    ingredients: [
      { name: "Whole milk", amount: "2000", unit: "ml" },
      { name: "Lemon juice", amount: "3", unit: "tbsp" },
      { name: "Granulated sugar", amount: "200", unit: "g" },
      { name: "Saffron strands", amount: "0.25", unit: "tsp" },
      { name: "Green cardamom", amount: "6", unit: "pcs" },
      { name: "Pistachios", amount: "30", unit: "g" },
      { name: "Ice water", amount: "500", unit: "ml" },
      { name: "Rose water", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the chenna",
        durationMin: 20,
        text: "Bring 1 litre of the milk to a boil, stir in lemon juice until it splits, and drain the curds in muslin. Rinse under cold water, hang 20 minutes, then knead 8 minutes into a smooth dough. Shape into 16 small discs.",
      },
      {
        order: 2,
        title: "Poach the discs",
        durationMin: 20,
        text: "Boil 150 g sugar with 600 ml water. Slide in the discs, cover, and simmer 12 to 15 minutes until they swell. Cool them in ice water, then gently squeeze out excess syrup.",
      },
      {
        order: 3,
        title: "Reduce the milk",
        durationMin: 35,
        text: "Simmer the remaining 1 litre of milk with crushed cardamom and saffron until it reduces by about one third and tastes rich. Stir in the remaining sugar and rose water. Cool until just warm.",
      },
      {
        order: 4,
        title: "Soak and chill",
        durationMin: 10,
        text: "Place the discs in the saffron milk and chill at least 4 hours. Serve cold, spooned with the rabri and chopped pistachios.",
      },
    ],
  },
  {
    slug: "jalebi",
    cuisineSlug: "indian",
    prepTime: 80,
    calories: 310,
    difficulty: "hard",
    servings: 8,
    title: "Jalebi",
    description:
      "Fermented maida spirals fried in ghee until crisp, then soaked in saffron-cardamom sugar syrup.",
    tags: ["dessert", "fried", "festive", "street-food"],
    chefTips: [
      "The batter should be thick enough to hold a coil; if it spreads in the oil, whisk in a spoon of flour.",
      "Soak the hot jalebis in warm (not boiling) syrup for 30 seconds so they stay crisp outside and juicy inside.",
    ],
    nutrition: {
      protein: 3,
      carbs: 52,
      fat: 10,
      fiber: 0,
      sugar: 36,
      sodium: 40,
      saturatedFat: 6,
      cholesterol: 20,
    },
    ingredients: [
      { name: "Maida (all-purpose flour)", amount: "200", unit: "g" },
      { name: "Plain yogurt", amount: "60", unit: "g" },
      { name: "Granulated sugar", amount: "300", unit: "g" },
      { name: "Saffron strands", amount: "0.25", unit: "tsp" },
      { name: "Green cardamom", amount: "4", unit: "pcs" },
      { name: "Ghee", amount: "400", unit: "g" },
      { name: "Baking soda", amount: "0.25", unit: "tsp" },
      { name: "Water", amount: "280", unit: "ml" },
      { name: "Lemon juice", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Ferment the batter",
        durationMin: 10,
        text: "Whisk the maida with yogurt and 150 ml water to a smooth, thick batter. Cover and ferment in a warm place 6 to 8 hours, until slightly sour and bubbly. Stir in baking soda just before frying.",
      },
      {
        order: 2,
        title: "Make the syrup",
        durationMin: 12,
        text: "Boil sugar with 130 ml water until it reaches a one-thread consistency. Stir in crushed cardamom, saffron, and lemon juice. Keep the syrup warm.",
      },
      {
        order: 3,
        title: "Fry the spirals",
        durationMin: 20,
        text: "Heat ghee to 180°C. Pipe the batter from a squeeze bottle into tight coils. Fry until deep gold and crisp, turning once, about 2 minutes per side.",
      },
      {
        order: 4,
        title: "Soak and serve",
        durationMin: 8,
        text: "Lift the jalebis into the warm syrup for 30 seconds, turn once, then drain on a rack. Serve warm.",
      },
    ],
  },
];

