import type { DemoRecipe } from "./types";

export const italianRecipes: DemoRecipe[] = [
  {
    slug: "spaghetti-aglio-e-olio",
    cuisineSlug: "italian",
    prepTime: 20,
    calories: 520,
    difficulty: "easy",
    servings: 4,
    title: "Spaghetti Aglio e Olio",
    description:
      "A Neapolitan-Roman pantry pasta of spaghetti tossed in garlic-infused extra virgin olive oil, crushed red pepper, and parsley.",
    tags: ["pasta", "quick", "vegetarian", "weeknight"],
    chefTips: [
      "Slice the garlic thin and cook it slowly until pale gold — browned garlic turns the oil bitter.",
      "Finish the spaghetti in the skillet with a ladle of starchy pasta water so the oil emulsifies into a glossy sauce.",
    ],
    nutrition: {
      protein: 14,
      carbs: 68,
      fat: 22,
      fiber: 3,
      sugar: 2,
      sodium: 480,
      saturatedFat: 4,
      cholesterol: 8,
    },
    ingredients: [
      { name: "Spaghetti", amount: "400", unit: "g" },
      { name: "Extra virgin olive oil", amount: "80", unit: "ml" },
      { name: "Garlic", amount: "6", unit: "cloves" },
      { name: "Crushed red pepper flakes", amount: "1", unit: "tsp" },
      { name: "Flat-leaf parsley", amount: "20", unit: "g" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Pecorino Romano", amount: "40", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Boil the pasta",
        durationMin: 10,
        text: "Bring a large pot of well-salted water to a rolling boil. Cook the spaghetti until just shy of al dente, about 1 minute less than the package time. Reserve 200 ml of pasta water before draining.",
      },
      {
        order: 2,
        title: "Infuse the oil",
        durationMin: 5,
        text: "While the pasta cooks, warm the extra virgin olive oil in a wide skillet over medium-low heat. Add thinly sliced garlic and cook until the edges turn pale gold, 3 to 4 minutes. Stir in the crushed red pepper for the last 30 seconds.",
      },
      {
        order: 3,
        title: "Toss and emulsify",
        durationMin: 3,
        text: "Add the drained spaghetti to the skillet with a splash of pasta water. Toss vigorously over medium heat until the oil and water form a light emulsion that coats every strand.",
      },
      {
        order: 4,
        title: "Finish with parsley",
        durationMin: 2,
        text: "Off the heat, fold in chopped parsley and grated Pecorino Romano. Taste for salt, grind a little black pepper if you like, and serve immediately.",
      },
    ],
  },
  {
    slug: "ravioli-with-sage-butter",
    cuisineSlug: "italian",
    prepTime: 20,
    calories: 490,
    difficulty: "easy",
    servings: 4,
    title: "Ravioli with Sage Butter",
    description:
      "Fresh cheese ravioli dressed in nutty brown butter, crisped sage leaves, a whisper of nutmeg, and Parmesan.",
    tags: ["pasta", "vegetarian", "quick", "dinner"],
    chefTips: [
      "Brown the butter until it smells nutty and the milk solids are amber, then add the sage so the leaves crisp without burning.",
    ],
    nutrition: {
      protein: 18,
      carbs: 42,
      fat: 28,
      fiber: 2,
      sugar: 3,
      sodium: 720,
      saturatedFat: 16,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Fresh cheese ravioli", amount: "500", unit: "g" },
      { name: "Unsalted butter", amount: "80", unit: "g" },
      { name: "Fresh sage", amount: "12", unit: "leaves" },
      { name: "Freshly grated nutmeg", amount: "0.25", unit: "tsp" },
      { name: "Parmigiano-Reggiano", amount: "50", unit: "g" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
      { name: "Lemon zest", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the ravioli",
        durationMin: 6,
        text: "Bring a wide pot of salted water to a gentle boil. Cook the fresh cheese ravioli until they float and the pasta is tender, 3 to 5 minutes. Lift them out with a slotted spoon and reserve 80 ml of the cooking water.",
      },
      {
        order: 2,
        title: "Brown the butter",
        durationMin: 5,
        text: "Melt the unsalted butter in a large skillet over medium heat. Cook, swirling, until the foam subsides and the milk solids turn amber and smell toasted.",
      },
      {
        order: 3,
        title: "Crisp the sage",
        durationMin: 2,
        text: "Add the sage leaves and fry 30 to 45 seconds until they darken and crisp. Grate in the nutmeg and a pinch of black pepper.",
      },
      {
        order: 4,
        title: "Coat and serve",
        durationMin: 3,
        text: "Slide the ravioli into the skillet with a splash of pasta water. Toss gently so the brown butter clings. Finish with grated Parmigiano-Reggiano, lemon zest, and a last grind of pepper.",
      },
    ],
  },
  {
    slug: "gnocchi-alla-sorrentina",
    cuisineSlug: "italian",
    prepTime: 40,
    calories: 560,
    difficulty: "medium",
    servings: 4,
    title: "Gnocchi alla Sorrentina",
    description:
      "Soft potato gnocchi baked in a San Marzano tomato sauce with melted mozzarella, basil, and Parmesan, in the style of the Sorrentine coast.",
    tags: ["pasta", "baked", "vegetarian", "comfort"],
    chefTips: [
      "Use low-moisture mozzarella or pat fresh mozzarella dry so the bake stays saucy instead of watery.",
    ],
    nutrition: {
      protein: 22,
      carbs: 64,
      fat: 22,
      fiber: 5,
      sugar: 8,
      sodium: 780,
      saturatedFat: 9,
      cholesterol: 45,
    },
    ingredients: [
      { name: "Potato gnocchi", amount: "500", unit: "g" },
      { name: "San Marzano tomatoes", amount: "400", unit: "g" },
      { name: "Fresh mozzarella", amount: "200", unit: "g" },
      { name: "Fresh basil", amount: "15", unit: "leaves" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Parmigiano-Reggiano", amount: "40", unit: "g" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Dried oregano", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the tomato sauce",
        durationMin: 15,
        text: "Warm the olive oil in a saucepan and soften smashed garlic without browning. Add crushed San Marzano tomatoes, oregano, and salt. Simmer until the sauce thickens and tastes sweet, about 12 minutes. Tear in half the basil.",
      },
      {
        order: 2,
        title: "Boil the gnocchi",
        durationMin: 5,
        text: "Cook the potato gnocchi in salted boiling water until they float, 2 to 3 minutes. Drain well.",
      },
      {
        order: 3,
        title: "Assemble",
        durationMin: 5,
        text: "Toss the gnocchi with most of the tomato sauce and spoon into a baking dish. Tear the mozzarella over the top, drizzle the remaining sauce, and shower with grated Parmesan.",
      },
      {
        order: 4,
        title: "Bake until bubbling",
        durationMin: 15,
        text: "Bake at 200°C until the mozzarella melts and the edges bubble, 12 to 15 minutes. Rest 3 minutes, then finish with the remaining basil leaves.",
      },
    ],
  },
  {
    slug: "pasta-amatriciana",
    cuisineSlug: "italian",
    prepTime: 35,
    calories: 610,
    difficulty: "medium",
    servings: 4,
    title: "Pasta Amatriciana",
    description:
      "A Roman classic of bucatini in a sauce of rendered guanciale, San Marzano tomatoes, dried chili, and sharp Pecorino Romano.",
    tags: ["pasta", "pork", "roman", "dinner"],
    chefTips: [
      "Render the guanciale slowly so the fat melts and the edges crisp; that fat is the soul of the sauce.",
      "Toss the pasta off the heat with Pecorino so the cheese melts into a creamy coating instead of clumping.",
    ],
    nutrition: {
      protein: 24,
      carbs: 66,
      fat: 26,
      fiber: 4,
      sugar: 7,
      sodium: 890,
      saturatedFat: 10,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Bucatini", amount: "400", unit: "g" },
      { name: "Guanciale", amount: "150", unit: "g" },
      { name: "San Marzano tomatoes", amount: "400", unit: "g" },
      { name: "Pecorino Romano", amount: "60", unit: "g" },
      { name: "Dried chili pepper", amount: "1", unit: "pcs" },
      { name: "Dry white wine", amount: "80", unit: "ml" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Render the guanciale",
        durationMin: 10,
        text: "Cut the guanciale into thick strips. Cook it in a cold skillet over medium-low heat until the fat renders and the pieces turn golden and crisp at the edges. Spoon off excess fat if needed, leaving about 3 tablespoons in the pan.",
      },
      {
        order: 2,
        title: "Build the sauce",
        durationMin: 12,
        text: "Add the crumbled dried chili, then deglaze with white wine and let it reduce by half. Stir in crushed San Marzano tomatoes and a pinch of salt. Simmer until the sauce is thick and glossy.",
      },
      {
        order: 3,
        title: "Cook the bucatini",
        durationMin: 10,
        text: "Boil the bucatini in salted water until al dente. Reserve 150 ml of pasta water and drain.",
      },
      {
        order: 4,
        title: "Toss with pecorino",
        durationMin: 3,
        text: "Add the pasta to the sauce with a splash of pasta water. Off the heat, toss with finely grated Pecorino Romano and plenty of black pepper until creamy. Serve at once.",
      },
    ],
  },
  {
    slug: "pasta-alla-norma",
    cuisineSlug: "italian",
    prepTime: 50,
    calories: 580,
    difficulty: "medium",
    servings: 4,
    title: "Pasta alla Norma",
    description:
      "A Catania classic of rigatoni with fried eggplant, garlic-scented tomato sauce, basil, and a snowfall of ricotta salata.",
    tags: ["pasta", "sicilian", "vegetarian", "eggplant"],
    chefTips: [
      "Salt the eggplant slices and let them sit 20 minutes before frying so they brown instead of soaking up oil.",
    ],
    nutrition: {
      protein: 18,
      carbs: 72,
      fat: 24,
      fiber: 8,
      sugar: 10,
      sodium: 740,
      saturatedFat: 6,
      cholesterol: 20,
    },
    ingredients: [
      { name: "Rigatoni", amount: "400", unit: "g" },
      { name: "Eggplant", amount: "600", unit: "g" },
      { name: "San Marzano tomatoes", amount: "400", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Fresh basil", amount: "12", unit: "leaves" },
      { name: "Ricotta salata", amount: "80", unit: "g" },
      { name: "Extra virgin olive oil", amount: "80", unit: "ml" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Dried oregano", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Salt and fry the eggplant",
        durationMin: 25,
        text: "Slice the eggplant into 1 cm rounds, salt both sides, and rest 20 minutes. Pat dry. Fry in olive oil over medium-high heat until golden on both sides. Drain on paper and tear into bite-size pieces.",
      },
      {
        order: 2,
        title: "Simmer the sauce",
        durationMin: 12,
        text: "In a clean pan, warm a little olive oil with sliced garlic until fragrant. Add crushed tomatoes, oregano, and salt. Simmer 10 minutes, then fold in half the basil.",
      },
      {
        order: 3,
        title: "Cook the rigatoni",
        durationMin: 10,
        text: "Boil the rigatoni in salted water until al dente. Reserve 100 ml of pasta water.",
      },
      {
        order: 4,
        title: "Combine and finish",
        durationMin: 3,
        text: "Toss the pasta with the tomato sauce, fried eggplant, and a splash of pasta water. Plate and grate plenty of ricotta salata over the top with the remaining basil.",
      },
    ],
  },
  {
    slug: "linguine-alle-vongole",
    cuisineSlug: "italian",
    prepTime: 30,
    calories: 540,
    difficulty: "medium",
    servings: 4,
    title: "Linguine alle Vongole",
    description:
      "Linguine tossed with steamed clams, garlic, white wine, chili flake, and parsley in a briny olive-oil sauce.",
    tags: ["pasta", "seafood", "clam", "italian"],
    chefTips: [
      "Purge the clams in cold salted water for 20 minutes and discard any that stay open before cooking.",
      "Do not over-salt the pasta water; the clam liquor is already briny.",
    ],
    nutrition: {
      protein: 28,
      carbs: 66,
      fat: 16,
      fiber: 3,
      sugar: 2,
      sodium: 920,
      saturatedFat: 2,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Linguine", amount: "400", unit: "g" },
      { name: "Fresh clams", amount: "1000", unit: "g" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Extra virgin olive oil", amount: "60", unit: "ml" },
      { name: "Dry white wine", amount: "120", unit: "ml" },
      { name: "Flat-leaf parsley", amount: "20", unit: "g" },
      { name: "Crushed red pepper flakes", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
      { name: "Lemon", amount: "0.5", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Purge the clams",
        durationMin: 5,
        text: "Scrub the clams and soak them in cold salted water. Discard any with cracked shells or that do not close when tapped.",
      },
      {
        order: 2,
        title: "Start the linguine",
        durationMin: 8,
        text: "Boil the linguine in lightly salted water until 2 minutes short of al dente. Reserve 150 ml of pasta water.",
      },
      {
        order: 3,
        title: "Steam the clams",
        durationMin: 8,
        text: "In a wide lidded pan, warm olive oil with thinly sliced garlic and chili flake. Add the clams and white wine, cover, and steam until they open, 4 to 6 minutes. Discard any that stay shut.",
      },
      {
        order: 4,
        title: "Toss together",
        durationMin: 4,
        text: "Add the linguine to the clam pan with a splash of pasta water. Toss over high heat until the sauce turns glossy. Finish with chopped parsley and a squeeze of lemon.",
      },
    ],
  },
  {
    slug: "saltimbocca-alla-romana",
    cuisineSlug: "italian",
    prepTime: 25,
    calories: 420,
    difficulty: "medium",
    servings: 4,
    title: "Saltimbocca alla Romana",
    description:
      "Thin veal cutlets topped with prosciutto and sage, pan-seared and deglazed with white wine and butter.",
    tags: ["veal", "roman", "main", "quick"],
    chefTips: [
      "Pound the veal very thin and sear it hot and fast so it stays tender; overcooking makes it tough.",
    ],
    nutrition: {
      protein: 38,
      carbs: 6,
      fat: 24,
      fiber: 0,
      sugar: 1,
      sodium: 860,
      saturatedFat: 11,
      cholesterol: 140,
    },
    ingredients: [
      { name: "Veal cutlets", amount: "500", unit: "g" },
      { name: "Prosciutto di Parma", amount: "8", unit: "pcs" },
      { name: "Fresh sage", amount: "8", unit: "leaves" },
      { name: "Dry white wine", amount: "120", unit: "ml" },
      { name: "Unsalted butter", amount: "50", unit: "g" },
      { name: "All-purpose flour", amount: "30", unit: "g" },
      { name: "Extra virgin olive oil", amount: "20", unit: "ml" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Assemble the cutlets",
        durationMin: 8,
        text: "Pound the veal cutlets to 3 mm thickness. Season lightly with salt and pepper. Lay a sage leaf on each piece, cover with a slice of prosciutto, and secure with a toothpick. Dust the veal side lightly with flour.",
      },
      {
        order: 2,
        title: "Sear",
        durationMin: 6,
        text: "Heat olive oil and half the butter in a large skillet over medium-high heat. Sear the veal, prosciutto-side down first, 1 to 2 minutes per side until just cooked through. Transfer to a warm plate.",
      },
      {
        order: 3,
        title: "Deglaze",
        durationMin: 4,
        text: "Pour the white wine into the pan and scrape up the browned bits. Reduce by half, then whisk in the remaining butter to make a glossy sauce.",
      },
      {
        order: 4,
        title: "Sauce and serve",
        durationMin: 2,
        text: "Return the saltimbocca to the pan for 30 seconds to coat. Spoon the wine-butter sauce over the cutlets and serve immediately.",
      },
    ],
  },
  {
    slug: "chicken-cacciatore",
    cuisineSlug: "italian",
    prepTime: 70,
    calories: 480,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Cacciatore",
    description:
      "Hunter-style braised chicken thighs with onion, garlic, tomato, bell pepper, rosemary, white wine, and olives.",
    tags: ["chicken", "braise", "dinner", "comfort"],
    chefTips: [
      "Brown the chicken skin well before the braise; that fond is what gives the sauce depth.",
    ],
    nutrition: {
      protein: 36,
      carbs: 14,
      fat: 28,
      fiber: 3,
      sugar: 7,
      sodium: 680,
      saturatedFat: 7,
      cholesterol: 155,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "800", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Canned plum tomatoes", amount: "400", unit: "g" },
      { name: "Bell pepper", amount: "2", unit: "pcs" },
      { name: "Fresh rosemary", amount: "2", unit: "pcs" },
      { name: "Dry white wine", amount: "150", unit: "ml" },
      { name: "Gaeta olives", amount: "80", unit: "g" },
      { name: "Extra virgin olive oil", amount: "30", unit: "ml" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Brown the chicken",
        durationMin: 12,
        text: "Season the chicken thighs with salt and pepper. Brown them skin-side down in olive oil over medium-high heat until the skin is deep gold, then flip briefly. Transfer to a plate.",
      },
      {
        order: 2,
        title: "Soften the vegetables",
        durationMin: 10,
        text: "In the same pot, cook sliced onion and bell pepper until soft. Add sliced garlic and rosemary and cook 1 minute.",
      },
      {
        order: 3,
        title: "Deglaze and braise",
        durationMin: 40,
        text: "Pour in the white wine and reduce by half. Add the tomatoes and olives, nestle the chicken back in, cover, and simmer gently until the meat is tender, about 35 minutes.",
      },
      {
        order: 4,
        title: "Reduce the sauce",
        durationMin: 8,
        text: "Uncover and simmer a few minutes more if the sauce is thin. Taste for salt and serve with bread or polenta.",
      },
    ],
  },
  {
    slug: "eggplant-parmigiana",
    cuisineSlug: "italian",
    prepTime: 75,
    calories: 450,
    difficulty: "medium",
    servings: 6,
    title: "Eggplant Parmigiana",
    description:
      "Layers of fried eggplant, bright tomato sauce, mozzarella, Parmesan, and basil baked until bubbling and golden.",
    tags: ["eggplant", "baked", "vegetarian", "southern-italian"],
    chefTips: [
      "Fry the eggplant in a single layer and drain well so the finished dish is rich, not greasy.",
    ],
    nutrition: {
      protein: 20,
      carbs: 22,
      fat: 32,
      fiber: 6,
      sugar: 10,
      sodium: 820,
      saturatedFat: 12,
      cholesterol: 50,
    },
    ingredients: [
      { name: "Eggplant", amount: "1000", unit: "g" },
      { name: "Tomato passata", amount: "600", unit: "ml" },
      { name: "Fresh mozzarella", amount: "250", unit: "g" },
      { name: "Parmigiano-Reggiano", amount: "80", unit: "g" },
      { name: "Fresh basil", amount: "16", unit: "leaves" },
      { name: "Extra virgin olive oil", amount: "120", unit: "ml" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "All-purpose flour", amount: "40", unit: "g" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Salt and fry the eggplant",
        durationMin: 30,
        text: "Slice the eggplant 8 mm thick, salt, and rest 20 minutes. Pat dry, dust lightly with flour, and fry in olive oil until golden on both sides. Drain on paper.",
      },
      {
        order: 2,
        title: "Simmer the sauce",
        durationMin: 15,
        text: "Warm a little olive oil with smashed garlic, add the tomato passata and a pinch of salt, and simmer until slightly thickened. Tear in a few basil leaves.",
      },
      {
        order: 3,
        title: "Layer the dish",
        durationMin: 10,
        text: "Spoon a thin layer of sauce into a baking dish. Alternate eggplant, sauce, torn mozzarella, grated Parmesan, and basil, finishing with cheese on top.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 25,
        text: "Bake at 190°C until bubbling and the top is spotted gold, 20 to 25 minutes. Rest 10 minutes so the layers set, then slice.",
      },
    ],
  },
  {
    slug: "polenta-with-mushroom-sauce",
    cuisineSlug: "italian",
    prepTime: 45,
    calories: 410,
    difficulty: "medium",
    servings: 4,
    title: "Polenta with Mushroom Sauce",
    description:
      "Creamy coarse polenta topped with a thyme-scented sauce of mixed mushrooms, garlic, butter, and Parmesan.",
    tags: ["polenta", "vegetarian", "mushrooms", "comfort"],
    chefTips: [
      "Whisk the polenta often in the first 5 minutes so it stays lump-free, then cook it low and slow.",
      "Do not crowd the mushrooms; they need space to brown instead of steam.",
    ],
    nutrition: {
      protein: 14,
      carbs: 48,
      fat: 18,
      fiber: 4,
      sugar: 3,
      sodium: 640,
      saturatedFat: 9,
      cholesterol: 35,
    },
    ingredients: [
      { name: "Coarse polenta", amount: "250", unit: "g" },
      { name: "Mixed mushrooms", amount: "500", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Fresh thyme", amount: "6", unit: "leaves" },
      { name: "Unsalted butter", amount: "60", unit: "g" },
      { name: "Parmigiano-Reggiano", amount: "50", unit: "g" },
      { name: "Vegetable stock", amount: "1000", unit: "ml" },
      { name: "Extra virgin olive oil", amount: "20", unit: "ml" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the polenta",
        durationMin: 30,
        text: "Bring the stock to a boil, rain in the coarse polenta while whisking, then lower the heat. Cook, stirring often, until thick and creamy, 25 to 30 minutes. Stir in half the butter, Parmesan, and salt.",
      },
      {
        order: 2,
        title: "Brown the mushrooms",
        durationMin: 10,
        text: "Meanwhile, heat olive oil and the remaining butter in a wide skillet. Add torn mixed mushrooms in a single layer and cook without stirring until they take on color. Season with salt and pepper.",
      },
      {
        order: 3,
        title: "Finish the sauce",
        durationMin: 4,
        text: "Add minced garlic and thyme leaves and cook 1 minute until fragrant. Splash in a spoonful of water if the pan is dry.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 1,
        text: "Spoon the soft polenta into bowls and top with the mushroom sauce and extra Parmesan.",
      },
    ],
  },
  {
    slug: "italian-wedding-soup",
    cuisineSlug: "italian",
    prepTime: 50,
    calories: 380,
    difficulty: "medium",
    servings: 6,
    title: "Italian Wedding Soup",
    description:
      "A comforting broth of tiny pork-and-beef meatballs, escarole, acini di pepe, and a beaten-egg ribbon.",
    tags: ["soup", "meatballs", "comfort", "italian"],
    chefTips: [
      "Brown the meatballs first so they hold their shape and flavor the broth.",
    ],
    nutrition: {
      protein: 24,
      carbs: 22,
      fat: 20,
      fiber: 3,
      sugar: 3,
      sodium: 980,
      saturatedFat: 7,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Chicken broth", amount: "1500", unit: "ml" },
      { name: "Ground pork", amount: "200", unit: "g" },
      { name: "Ground beef", amount: "200", unit: "g" },
      { name: "Parmigiano-Reggiano", amount: "40", unit: "g" },
      { name: "Breadcrumbs", amount: "40", unit: "g" },
      { name: "Escarole", amount: "200", unit: "g" },
      { name: "Acini di pepe", amount: "100", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Flat-leaf parsley", amount: "15", unit: "g" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the meatballs",
        durationMin: 10,
        text: "Combine ground pork, ground beef, grated Parmesan, breadcrumbs, minced garlic, chopped parsley, one beaten egg, and salt. Roll into small meatballs about 2 cm wide.",
      },
      {
        order: 2,
        title: "Brown the meatballs",
        durationMin: 8,
        text: "Brown the meatballs in a little oil in a Dutch oven, turning so they color on all sides. They do not need to cook through.",
      },
      {
        order: 3,
        title: "Simmer the soup",
        durationMin: 20,
        text: "Pour in the chicken broth and bring to a simmer. Cook 10 minutes, then add the acini di pepe and shredded escarole. Simmer until the pasta is tender and the greens wilt, about 8 minutes.",
      },
      {
        order: 4,
        title: "Ribbon the egg",
        durationMin: 3,
        text: "Beat the remaining egg and drizzle it into the simmering soup while stirring to form thin strands. Taste for salt and serve with extra Parmesan.",
      },
    ],
  },
  {
    slug: "focaccia-bread",
    cuisineSlug: "italian",
    prepTime: 150,
    calories: 280,
    difficulty: "medium",
    servings: 8,
    title: "Focaccia Bread",
    description:
      "A Ligurian-style focaccia with a dimpled, olive-oil-rich crumb, rosemary, and a finish of flaky salt.",
    tags: ["bread", "baked", "vegetarian", "side"],
    chefTips: [
      "Pour a generous film of olive oil into the pan and on top of the dough; that oil is what makes the crust crisp and the crumb tender.",
    ],
    nutrition: {
      protein: 7,
      carbs: 42,
      fat: 10,
      fiber: 2,
      sugar: 1,
      sodium: 520,
      saturatedFat: 1.5,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Bread flour", amount: "500", unit: "g" },
      { name: "Extra virgin olive oil", amount: "80", unit: "ml" },
      { name: "Instant yeast", amount: "7", unit: "g" },
      { name: "Fine sea salt", amount: "10", unit: "g" },
      { name: "Fresh rosemary", amount: "8", unit: "leaves" },
      { name: "Flaky sea salt", amount: "1", unit: "tbsp" },
      { name: "Warm water", amount: "375", unit: "ml" },
      { name: "Honey", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the dough",
        durationMin: 15,
        text: "Stir the yeast and honey into the warm water. Add the bread flour and fine salt and mix until a sticky dough forms. Knead 8 minutes until smooth and elastic. Work in 2 tablespoons of olive oil.",
      },
      {
        order: 2,
        title: "First rise",
        durationMin: 75,
        text: "Place the dough in an oiled bowl, cover, and let rise until doubled, about 75 minutes.",
      },
      {
        order: 3,
        title: "Dimple and proof",
        durationMin: 35,
        text: "Oil a 23 by 33 cm pan generously. Stretch the dough to the corners, drizzle more olive oil, and dimple deeply with wet fingertips. Scatter rosemary and flaky salt. Proof 30 minutes until puffy.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 25,
        text: "Bake at 220°C until the top is deep gold and the bottom sounds hollow, 22 to 25 minutes. Cool 10 minutes in the pan, then slice.",
      },
    ],
  },
  {
    slug: "calzone",
    cuisineSlug: "italian",
    prepTime: 45,
    calories: 620,
    difficulty: "medium",
    servings: 4,
    title: "Calzone",
    description:
      "Folded pizza dough stuffed with ricotta, mozzarella, ham, a spoon of tomato, and oregano, baked until blistered.",
    tags: ["pizza", "baked", "ham", "dinner"],
    chefTips: [
      "Leave a 2 cm border and crimp firmly so the filling does not leak; vent the top with a small slit so steam can escape.",
    ],
    nutrition: {
      protein: 32,
      carbs: 58,
      fat: 28,
      fiber: 3,
      sugar: 5,
      sodium: 1100,
      saturatedFat: 13,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Pizza dough", amount: "600", unit: "g" },
      { name: "Whole-milk ricotta", amount: "250", unit: "g" },
      { name: "Fresh mozzarella", amount: "200", unit: "g" },
      { name: "Cooked ham", amount: "120", unit: "g" },
      { name: "Tomato passata", amount: "80", unit: "ml" },
      { name: "Dried oregano", amount: "1", unit: "tsp" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Parmigiano-Reggiano", amount: "30", unit: "g" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Extra virgin olive oil", amount: "15", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the filling",
        durationMin: 8,
        text: "Stir together ricotta, diced mozzarella, chopped ham, a spoon of tomato passata, oregano, grated Parmesan, and black pepper.",
      },
      {
        order: 2,
        title: "Shape the calzoni",
        durationMin: 12,
        text: "Divide the pizza dough into 4 balls and roll each into a 22 cm oval. Spoon filling on one half, leaving a border. Fold over, crimp the edges, and cut a small vent. Brush with beaten egg and a little olive oil.",
      },
      {
        order: 3,
        title: "Bake",
        durationMin: 18,
        text: "Bake on a preheated stone or sheet at 230°C until puffed and well browned, 16 to 18 minutes.",
      },
      {
        order: 4,
        title: "Rest and serve",
        durationMin: 5,
        text: "Rest 5 minutes so the cheese settles. Serve with extra warm tomato passata on the side if you like.",
      },
    ],
  },
  {
    slug: "cannoli-siciliani",
    cuisineSlug: "italian",
    prepTime: 90,
    calories: 340,
    difficulty: "hard",
    servings: 8,
    title: "Cannoli Siciliani",
    description:
      "Crisp fried pastry tubes scented with Marsala and cocoa, filled with sweet ricotta, candied orange, pistachios, and chocolate chips.",
    tags: ["dessert", "sicilian", "fried", "ricotta"],
    chefTips: [
      "Fill the shells just before serving so they stay shatter-crisp.",
      "Drain the ricotta overnight in a sieve so the filling is thick, not watery.",
    ],
    nutrition: {
      protein: 10,
      carbs: 36,
      fat: 18,
      fiber: 1,
      sugar: 18,
      sodium: 80,
      saturatedFat: 8,
      cholesterol: 35,
    },
    ingredients: [
      { name: "00 flour", amount: "200", unit: "g" },
      { name: "Marsala wine", amount: "60", unit: "ml" },
      { name: "Unsweetened cocoa powder", amount: "10", unit: "g" },
      { name: "Sheep's milk ricotta", amount: "500", unit: "g" },
      { name: "Powdered sugar", amount: "120", unit: "g" },
      { name: "Candied orange peel", amount: "40", unit: "g" },
      { name: "Pistachios", amount: "40", unit: "g" },
      { name: "Mini chocolate chips", amount: "50", unit: "g" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Lard", amount: "30", unit: "g" },
      { name: "Sunflower oil", amount: "800", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the dough",
        durationMin: 20,
        text: "Work the flour, cocoa, lard, Marsala, and a beaten egg into a firm dough. Wrap and rest 30 minutes at room temperature.",
      },
      {
        order: 2,
        title: "Fry the shells",
        durationMin: 25,
        text: "Roll the dough thin, cut ovals, and wrap them around cannoli tubes, sealing the overlap with a dab of egg. Fry in 180°C oil until blistered and amber. Cool, then slide off the tubes.",
      },
      {
        order: 3,
        title: "Make the filling",
        durationMin: 10,
        text: "Beat the drained ricotta with powdered sugar until smooth. Fold in chopped candied orange and most of the chocolate chips.",
      },
      {
        order: 4,
        title: "Fill and garnish",
        durationMin: 10,
        text: "Pipe the filling into both ends of each shell. Dip the ends in chopped pistachios and remaining chocolate chips. Dust with powdered sugar and serve at once.",
      },
    ],
  },
  {
    slug: "panna-cotta",
    cuisineSlug: "italian",
    prepTime: 25,
    calories: 310,
    difficulty: "easy",
    servings: 6,
    title: "Panna Cotta",
    description:
      "A Piedmontese set cream flavored with vanilla, served with a tart mixed-berry coulis.",
    tags: ["dessert", "cream", "make-ahead", "italian"],
    chefTips: [
      "Bloom the gelatin fully and never boil the cream after adding it, or the panna cotta will set rubbery.",
    ],
    nutrition: {
      protein: 4,
      carbs: 22,
      fat: 24,
      fiber: 1,
      sugar: 20,
      sodium: 40,
      saturatedFat: 15,
      cholesterol: 90,
    },
    ingredients: [
      { name: "Heavy cream", amount: "400", unit: "ml" },
      { name: "Whole milk", amount: "100", unit: "ml" },
      { name: "Granulated sugar", amount: "80", unit: "g" },
      { name: "Vanilla bean", amount: "1", unit: "pcs" },
      { name: "Gelatin sheets", amount: "3", unit: "pcs" },
      { name: "Mixed berries", amount: "200", unit: "g" },
      { name: "Sugar for coulis", amount: "30", unit: "g" },
      { name: "Lemon juice", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Bloom the gelatin",
        durationMin: 5,
        text: "Soak the gelatin sheets in cold water until soft, about 5 minutes.",
      },
      {
        order: 2,
        title: "Infuse the cream",
        durationMin: 8,
        text: "Warm the cream, milk, sugar, and split vanilla bean over medium heat until the sugar dissolves and the mixture is steaming, not boiling. Squeeze the gelatin dry and stir it in until fully melted. Remove the vanilla pod.",
      },
      {
        order: 3,
        title: "Set",
        durationMin: 5,
        text: "Strain into six ramekins. Cool to room temperature, then refrigerate at least 4 hours until softly set.",
      },
      {
        order: 4,
        title: "Make the coulis",
        durationMin: 7,
        text: "Simmer the berries with 30 g sugar and lemon juice until they collapse. Blend and strain. Unmold the panna cotta or serve in the cups with the coulis spooned over.",
      },
    ],
  },
];
