import type { DemoRecipe } from "./types";

export const japaneseRecipes: DemoRecipe[] = [
  {
    slug: "california-sushi-rolls",
    cuisineSlug: "japanese",
    prepTime: 45,
    calories: 380,
    difficulty: "medium",
    servings: 4,
    title: "California Sushi Rolls",
    description:
      "Inside-out maki of seasoned sushi rice, nori, avocado, cucumber, and imitation crab, finished with toasted sesame.",
    tags: ["sushi", "rolls", "seafood", "rice"],
    chefTips: [
      "Fan the seasoned rice as you fold in the vinegar so the grains stay glossy and separate, not mushy.",
      "A bamboo mat wrapped in plastic wrap keeps the rice from sticking when you roll uramaki.",
    ],
    nutrition: {
      protein: 12,
      carbs: 58,
      fat: 12,
      fiber: 4,
      sugar: 8,
      sodium: 720,
      saturatedFat: 2,
      cholesterol: 15,
    },
    ingredients: [
      { name: "Japanese short-grain rice", amount: "300", unit: "g" },
      { name: "Nori sheets", amount: "4", unit: "pcs" },
      { name: "Ripe avocado", amount: "1", unit: "pcs" },
      { name: "Japanese cucumber", amount: "1", unit: "pcs" },
      { name: "Imitation crab sticks", amount: "150", unit: "g" },
      { name: "Rice vinegar", amount: "40", unit: "ml" },
      { name: "Granulated sugar", amount: "1", unit: "tbsp" },
      { name: "Toasted sesame seeds", amount: "2", unit: "tbsp" },
      { name: "Salt", amount: "0.75", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook and season the rice",
        durationMin: 20,
        text: "Rinse the rice until the water runs almost clear, then cook. Warm the rice vinegar with the sugar and salt until dissolved. Fold the seasoning into the hot rice and fan until the rice is glossy and cooled to just warm.",
      },
      {
        order: 2,
        title: "Prep the fillings",
        durationMin: 8,
        text: "Slice the avocado and cucumber into long batons. Split the imitation crab sticks or shred them lightly.",
      },
      {
        order: 3,
        title: "Assemble the rolls",
        durationMin: 12,
        text: "Cover a bamboo mat with plastic wrap. Place a nori sheet shiny-side down, spread a thin even layer of rice to the edges, and sprinkle with sesame. Flip so the nori faces up. Line avocado, cucumber, and crab across the center.",
      },
      {
        order: 4,
        title: "Roll and slice",
        durationMin: 5,
        text: "Roll tightly with the mat, pressing as you go. Wet a sharp knife and cut each roll into 8 pieces. Serve with soy sauce, wasabi, and pickled ginger.",
      },
    ],
  },
  {
    slug: "spicy-tuna-rolls",
    cuisineSlug: "japanese",
    prepTime: 40,
    calories: 360,
    difficulty: "medium",
    servings: 4,
    title: "Spicy Tuna Rolls",
    description:
      "Sushi rice and nori rolled around chopped tuna mixed with mayonnaise, chili sauce, scallion, and sesame.",
    tags: ["sushi", "tuna", "spicy", "rolls"],
    chefTips: [
      "Use sushi-grade tuna and keep it cold; chop it with a sharp knife rather than pulsing it into a paste.",
      "A little sriracha goes a long way; taste the tuna mix before you roll so the heat does not overwhelm the fish.",
    ],
    nutrition: {
      protein: 22,
      carbs: 48,
      fat: 10,
      fiber: 2,
      sugar: 5,
      sodium: 680,
      saturatedFat: 2,
      cholesterol: 35,
    },
    ingredients: [
      { name: "Japanese short-grain rice", amount: "300", unit: "g" },
      { name: "Nori sheets", amount: "4", unit: "pcs" },
      { name: "Sushi-grade tuna", amount: "250", unit: "g" },
      { name: "Japanese mayonnaise", amount: "2", unit: "tbsp" },
      { name: "Sriracha", amount: "2", unit: "tsp" },
      { name: "Scallions", amount: "2", unit: "stalks" },
      { name: "Toasted sesame seeds", amount: "1", unit: "tbsp" },
      { name: "Rice vinegar", amount: "40", unit: "ml" },
      { name: "Granulated sugar", amount: "1", unit: "tbsp" },
      { name: "Salt", amount: "0.75", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Season the rice",
        durationMin: 20,
        text: "Cook the rinsed rice. Dissolve the sugar and salt in the rice vinegar and fold into the hot rice, fanning until glossy and just warm.",
      },
      {
        order: 2,
        title: "Mix the spicy tuna",
        durationMin: 6,
        text: "Chop the tuna into small pieces. Fold with mayonnaise, sriracha, thinly sliced scallions, and sesame. Chill until you roll.",
      },
      {
        order: 3,
        title: "Roll",
        durationMin: 10,
        text: "Spread rice on nori, leaving a 1 cm strip at the far edge. Spoon the spicy tuna in a line, roll tightly, and seal the edge with a dab of water.",
      },
      {
        order: 4,
        title: "Slice",
        durationMin: 4,
        text: "Cut each roll into 6 or 8 pieces with a wet knife. Serve immediately with soy sauce.",
      },
    ],
  },
  {
    slug: "chicken-teriyaki-bowl",
    cuisineSlug: "japanese",
    prepTime: 30,
    calories: 620,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Teriyaki Bowl",
    description:
      "Pan-seared chicken thighs glazed in soy, mirin, sake, and sugar, served over rice with sesame and scallion.",
    tags: ["chicken", "rice-bowl", "teriyaki", "weeknight"],
    chefTips: [
      "Reduce the glaze until it coats a spoon and turns lacquered on the chicken; watery teriyaki will slide off.",
      "Skin-on thighs stay juicier and give you crisp skin under the glaze.",
    ],
    nutrition: {
      protein: 36,
      carbs: 68,
      fat: 20,
      fiber: 1,
      sugar: 16,
      sodium: 1180,
      saturatedFat: 5,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Bone-in skin-on chicken thighs", amount: "800", unit: "g" },
      { name: "Soy sauce", amount: "60", unit: "ml" },
      { name: "Mirin", amount: "60", unit: "ml" },
      { name: "Sake", amount: "40", unit: "ml" },
      { name: "Granulated sugar", amount: "2", unit: "tbsp" },
      { name: "Cooked Japanese rice", amount: "600", unit: "g" },
      { name: "Toasted sesame seeds", amount: "1", unit: "tbsp" },
      { name: "Scallions", amount: "2", unit: "stalks" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the tare",
        durationMin: 3,
        text: "Stir the soy sauce, mirin, sake, and sugar until the sugar dissolves.",
      },
      {
        order: 2,
        title: "Sear the chicken",
        durationMin: 12,
        text: "Pat the thighs dry. Heat the oil in a skillet over medium heat, skin-side down, and cook until the skin is deep golden, 7 to 8 minutes. Flip and cook 4 minutes more.",
      },
      {
        order: 3,
        title: "Glaze",
        durationMin: 8,
        text: "Pour off excess fat. Add the tare and simmer, spooning it over the chicken, until the sauce is thick and glossy and the chicken is cooked through.",
      },
      {
        order: 4,
        title: "Serve over rice",
        durationMin: 3,
        text: "Slice the chicken. Spoon rice into bowls, top with chicken and remaining glaze, and finish with sesame and sliced scallion.",
      },
    ],
  },
  {
    slug: "shoyu-ramen",
    cuisineSlug: "japanese",
    prepTime: 90,
    calories: 580,
    difficulty: "hard",
    servings: 4,
    title: "Shoyu Ramen",
    description:
      "Soy-tare ramen in a chicken and pork broth with dashi, chashu, menma, nori, and scallion.",
    tags: ["ramen", "noodles", "pork", "soup"],
    chefTips: [
      "Make the tare and the broth separately so you can salt each bowl to taste instead of over-reducing the stock.",
      "A piece of kombu and a handful of katsuobushi give the broth the dashi backbone that shoyu ramen needs.",
    ],
    nutrition: {
      protein: 32,
      carbs: 62,
      fat: 20,
      fiber: 3,
      sugar: 6,
      sodium: 1980,
      saturatedFat: 6,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Fresh ramen noodles", amount: "500", unit: "g" },
      { name: "Chicken and pork broth", amount: "1.6", unit: "l" },
      { name: "Soy sauce", amount: "80", unit: "ml" },
      { name: "Mirin", amount: "30", unit: "ml" },
      { name: "Chashu pork or sliced pork belly", amount: "200", unit: "g" },
      { name: "Menma (seasoned bamboo shoots)", amount: "80", unit: "g" },
      { name: "Nori sheets", amount: "4", unit: "pcs" },
      { name: "Scallions", amount: "3", unit: "stalks" },
      { name: "Kombu", amount: "10", unit: "g" },
      { name: "Katsuobushi", amount: "10", unit: "g" },
      { name: "Sake", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Build the dashi broth",
        durationMin: 25,
        text: "Warm the chicken and pork broth with the kombu just below a simmer for 15 minutes. Remove the kombu, add the katsuobushi, steep 5 minutes, and strain.",
      },
      {
        order: 2,
        title: "Make the shoyu tare",
        durationMin: 8,
        text: "Simmer the soy sauce, mirin, and sake for 3 minutes. Set aside; this is the seasoning for each bowl.",
      },
      {
        order: 3,
        title: "Warm the toppings",
        durationMin: 8,
        text: "Slice the chashu and warm it in a little broth. Slice the scallions. Have the menma and nori ready.",
      },
      {
        order: 4,
        title: "Cook the noodles",
        durationMin: 4,
        text: "Boil the ramen noodles until just chewy, usually 1 to 3 minutes for fresh noodles. Drain well.",
      },
      {
        order: 5,
        title: "Assemble the bowls",
        durationMin: 5,
        text: "Put 2 tablespoons of tare in each bowl, ladle in hot broth, and add the noodles. Top with chashu, menma, nori, and scallion. Serve immediately.",
      },
    ],
  },
  {
    slug: "miso-ramen",
    cuisineSlug: "japanese",
    prepTime: 50,
    calories: 640,
    difficulty: "medium",
    servings: 4,
    title: "Miso Ramen",
    description:
      "Ramen in a miso-enriched chicken broth with stir-fried ground pork, garlic, ginger, bean sprouts, sesame, and corn.",
    tags: ["ramen", "miso", "noodles", "pork"],
    chefTips: [
      "Blend shiro and aka miso for a tare that is both sweet and deep; dissolve it off the boil so it stays fragrant.",
      "Fry the ground pork with garlic and ginger until the fat renders; that soffritto is half the flavor of Sapporo-style miso ramen.",
    ],
    nutrition: {
      protein: 30,
      carbs: 64,
      fat: 26,
      fiber: 4,
      sugar: 8,
      sodium: 2100,
      saturatedFat: 7,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Fresh ramen noodles", amount: "500", unit: "g" },
      { name: "White miso (shiro)", amount: "3", unit: "tbsp" },
      { name: "Red miso (aka)", amount: "2", unit: "tbsp" },
      { name: "Chicken stock", amount: "1.6", unit: "l" },
      { name: "Ground pork", amount: "250", unit: "g" },
      { name: "Bean sprouts", amount: "200", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Fresh ginger", amount: "15", unit: "g" },
      { name: "Toasted sesame oil", amount: "1", unit: "tbsp" },
      { name: "Sweet corn kernels", amount: "120", unit: "g" },
      { name: "Nori sheets", amount: "4", unit: "pcs" },
      { name: "Scallions", amount: "2", unit: "stalks" },
    ],
    steps: [
      {
        order: 1,
        title: "Fry the pork",
        durationMin: 10,
        text: "Heat the sesame oil in a pot. Fry the minced garlic and ginger 30 seconds, then the ground pork until browned and the fat renders.",
      },
      {
        order: 2,
        title: "Build the miso broth",
        durationMin: 12,
        text: "Add the chicken stock and bring to a simmer. Ladle some hot stock into a bowl with both misos, whisk smooth, then stir back into the pot off a hard boil. Taste and adjust.",
      },
      {
        order: 3,
        title: "Cook toppings and noodles",
        durationMin: 6,
        text: "Blanch the bean sprouts briefly. Warm the corn. Boil the ramen noodles until chewy and drain.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 4,
        text: "Divide noodles among bowls, ladle over the miso broth and pork, and top with bean sprouts, corn, nori, and scallion.",
      },
    ],
  },
  {
    slug: "beef-yakisoba",
    cuisineSlug: "japanese",
    prepTime: 25,
    calories: 540,
    difficulty: "easy",
    servings: 4,
    title: "Beef Yakisoba",
    description:
      "Stir-fried yakisoba noodles with thinly sliced beef, cabbage, carrot, and onion in yakisoba sauce, finished with aonori and beni shoga.",
    tags: ["noodles", "beef", "stir-fry", "street-food"],
    chefTips: [
      "Loosen packaged yakisoba noodles under warm water so they separate before they hit the pan.",
      "Aonori and beni shoga are the finish that makes it taste like festival yakisoba, not just sauced noodles.",
    ],
    nutrition: {
      protein: 26,
      carbs: 64,
      fat: 18,
      fiber: 5,
      sugar: 14,
      sodium: 1320,
      saturatedFat: 5,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Yakisoba noodles", amount: "500", unit: "g" },
      { name: "Thinly sliced beef", amount: "300", unit: "g" },
      { name: "Green cabbage", amount: "250", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Yakisoba or okonomiyaki sauce", amount: "80", unit: "ml" },
      { name: "Aonori (green seaweed powder)", amount: "1", unit: "tsp" },
      { name: "Beni shoga (pickled ginger)", amount: "30", unit: "g" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
      { name: "Soy sauce", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the vegetables",
        durationMin: 8,
        text: "Cut the cabbage into bite-size pieces, julienne the carrot, and slice the onion. Loosen the noodles under warm water and drain.",
      },
      {
        order: 2,
        title: "Sear the beef",
        durationMin: 4,
        text: "Heat the oil in a large skillet or teppan over high heat. Stir-fry the beef with the soy sauce until just browned. Remove to a plate.",
      },
      {
        order: 3,
        title: "Stir-fry vegetables and noodles",
        durationMin: 7,
        text: "Stir-fry the onion, carrot, and cabbage until the cabbage wilts. Add the noodles and toss until hot and slightly charred in spots.",
      },
      {
        order: 4,
        title: "Sauce and finish",
        durationMin: 4,
        text: "Return the beef, pour in the yakisoba sauce, and toss until every strand is coated. Plate and top with aonori and beni shoga.",
      },
    ],
  },
  {
    slug: "chicken-yakisoba",
    cuisineSlug: "japanese",
    prepTime: 25,
    calories: 510,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Yakisoba",
    description:
      "Yakisoba noodles stir-fried with chicken, cabbage, carrot, and onion in a sweet-savory sauce, finished with aonori and beni shoga.",
    tags: ["noodles", "chicken", "stir-fry", "street-food"],
    chefTips: [
      "Cut the chicken thin so it cooks in the same time as the vegetables and stays tender.",
      "Let the noodles sit against the hot pan for a few seconds at a time to pick up a little char.",
    ],
    nutrition: {
      protein: 28,
      carbs: 62,
      fat: 16,
      fiber: 5,
      sugar: 14,
      sodium: 1280,
      saturatedFat: 3,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Yakisoba noodles", amount: "500", unit: "g" },
      { name: "Boneless chicken thigh", amount: "350", unit: "g" },
      { name: "Green cabbage", amount: "250", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Yakisoba or okonomiyaki sauce", amount: "80", unit: "ml" },
      { name: "Aonori (green seaweed powder)", amount: "1", unit: "tsp" },
      { name: "Beni shoga (pickled ginger)", amount: "30", unit: "g" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
      { name: "Soy sauce", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Slice and loosen",
        durationMin: 8,
        text: "Slice the chicken into thin strips. Cut the cabbage, julienne the carrot, and slice the onion. Loosen the noodles under warm water.",
      },
      {
        order: 2,
        title: "Cook the chicken",
        durationMin: 5,
        text: "Heat the oil over high heat. Stir-fry the chicken with the soy sauce until just cooked through. Set aside.",
      },
      {
        order: 3,
        title: "Stir-fry",
        durationMin: 7,
        text: "Stir-fry the onion, carrot, and cabbage until wilted. Add the noodles and toss until heated and lightly charred.",
      },
      {
        order: 4,
        title: "Sauce",
        durationMin: 4,
        text: "Return the chicken, add the yakisoba sauce, and toss to coat. Serve with aonori and beni shoga.",
      },
    ],
  },
  {
    slug: "karaage-fried-chicken",
    cuisineSlug: "japanese",
    prepTime: 40,
    calories: 490,
    difficulty: "medium",
    servings: 4,
    title: "Karaage Fried Chicken",
    description:
      "Bite-size chicken thigh marinated in soy, sake, ginger, and garlic, dredged in potato starch, and fried until shatter-crisp.",
    tags: ["chicken", "fried", "appetizer", "izakaya"],
    chefTips: [
      "Potato starch, not wheat flour, is what gives karaage its craggy crust.",
      "Marinate at least 30 minutes and fry twice if you want the crust extra crisp after resting.",
    ],
    nutrition: {
      protein: 32,
      carbs: 16,
      fat: 32,
      fiber: 0,
      sugar: 2,
      sodium: 820,
      saturatedFat: 6,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "700", unit: "g" },
      { name: "Soy sauce", amount: "3", unit: "tbsp" },
      { name: "Sake", amount: "2", unit: "tbsp" },
      { name: "Fresh ginger", amount: "15", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Potato starch", amount: "80", unit: "g" },
      { name: "Neutral oil, for frying", amount: "1", unit: "l" },
      { name: "Lemon wedges", amount: "4", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate",
        durationMin: 10,
        text: "Cut the chicken into 4 cm pieces. Grate the ginger and garlic and toss with the chicken, soy sauce, and sake. Marinate 30 minutes in the fridge.",
      },
      {
        order: 2,
        title: "Dredge",
        durationMin: 5,
        text: "Drain off excess marinade. Toss the chicken in potato starch so every piece is well coated. Rest 5 minutes so the starch hydrates.",
      },
      {
        order: 3,
        title: "First fry",
        durationMin: 12,
        text: "Heat the oil to 170 C. Fry in batches until cooked through and light gold, 5 to 6 minutes. Drain on a rack.",
      },
      {
        order: 4,
        title: "Second fry and serve",
        durationMin: 6,
        text: "Raise the oil to 190 C and fry 1 to 2 minutes more until deep golden. Serve with lemon wedges and Japanese mayonnaise if you like.",
      },
    ],
  },
  {
    slug: "agedashi-tofu",
    cuisineSlug: "japanese",
    prepTime: 25,
    calories: 240,
    difficulty: "easy",
    servings: 4,
    title: "Agedashi Tofu",
    description:
      "Cubes of firm tofu dusted in potato starch, fried until crisp, and served in a hot dashi-soy-mirin broth with grated daikon and scallion.",
    tags: ["tofu", "fried", "dashi", "appetizer"],
    chefTips: [
      "Press the tofu 15 minutes so it fries crisp instead of sputtering.",
      "Pour the tentsuyu around the tofu, not over it, so the crust stays intact at the table.",
    ],
    nutrition: {
      protein: 14,
      carbs: 16,
      fat: 14,
      fiber: 2,
      sugar: 4,
      sodium: 780,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Firm tofu", amount: "400", unit: "g" },
      { name: "Potato starch", amount: "50", unit: "g" },
      { name: "Dashi", amount: "300", unit: "ml" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
      { name: "Mirin", amount: "2", unit: "tbsp" },
      { name: "Grated daikon", amount: "80", unit: "g" },
      { name: "Scallions", amount: "2", unit: "stalks" },
      { name: "Neutral oil, for frying", amount: "400", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Press the tofu",
        durationMin: 8,
        text: "Wrap the tofu in a clean towel and weight it for 10 to 15 minutes. Cut into 8 cubes and pat dry.",
      },
      {
        order: 2,
        title: "Make the tentsuyu",
        durationMin: 5,
        text: "Simmer the dashi, soy sauce, and mirin for 2 minutes. Keep hot.",
      },
      {
        order: 3,
        title: "Fry the tofu",
        durationMin: 8,
        text: "Dredge the cubes in potato starch. Fry in 180 C oil until the crust is pale gold and crisp, 3 to 4 minutes. Drain briefly.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Place the tofu in shallow bowls. Pour hot tentsuyu around it and top with grated daikon and sliced scallion.",
      },
    ],
  },
  {
    slug: "chawanmushi-steamed-egg",
    cuisineSlug: "japanese",
    prepTime: 35,
    calories: 160,
    difficulty: "medium",
    servings: 4,
    title: "Chawanmushi Steamed Egg",
    description:
      "Savory steamed egg custard set with dashi, soy, and mirin, hiding shrimp, shiitake, and kamaboko in each cup.",
    tags: ["egg", "steamed", "dashi", "appetizer"],
    chefTips: [
      "Strain the egg-dashi mixture and steam on the lowest heat so the custard sets silky, not pocked with bubbles.",
      "A 3-to-1 dashi-to-egg ratio by volume is the classic texture.",
    ],
    nutrition: {
      protein: 14,
      carbs: 6,
      fat: 8,
      fiber: 1,
      sugar: 2,
      sodium: 620,
      saturatedFat: 2,
      cholesterol: 195,
    },
    ingredients: [
      { name: "Eggs", amount: "3", unit: "pcs" },
      { name: "Dashi", amount: "360", unit: "ml" },
      { name: "Soy sauce", amount: "1", unit: "tsp" },
      { name: "Mirin", amount: "1", unit: "tsp" },
      { name: "Small shrimp", amount: "8", unit: "pcs" },
      { name: "Shiitake mushrooms", amount: "4", unit: "pcs" },
      { name: "Kamaboko (fish cake)", amount: "40", unit: "g" },
      { name: "Ginkgo nuts (optional)", amount: "8", unit: "pcs" },
      { name: "Mitsuba or scallion", amount: "4", unit: "sprigs" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the custard",
        durationMin: 6,
        text: "Beat the eggs gently without foam. Stir in the cooled dashi, soy sauce, and mirin. Strain through a fine sieve.",
      },
      {
        order: 2,
        title: "Fill the cups",
        durationMin: 6,
        text: "Place shrimp, sliced shiitake, kamaboko, and ginkgo nuts in four chawanmushi cups. Pour the egg mixture over, leaving a little headroom. Skim any bubbles.",
      },
      {
        order: 3,
        title: "Steam",
        durationMin: 15,
        text: "Cover each cup. Steam over barely simmering water until the custard is just set and a toothpick comes out clean, 12 to 15 minutes.",
      },
      {
        order: 4,
        title: "Garnish",
        durationMin: 2,
        text: "Top with mitsuba or scallion and serve warm, with a spoon.",
      },
    ],
  },
  {
    slug: "nikujaga-japanese-stew",
    cuisineSlug: "japanese",
    prepTime: 50,
    calories: 420,
    difficulty: "easy",
    servings: 4,
    title: "Nikujaga Japanese Stew",
    description:
      "A home-style simmer of thinly sliced beef, potato, onion, and carrot in dashi, soy, mirin, and sugar, with shirataki optional.",
    tags: ["beef", "stew", "comfort", "home-cooking"],
    chefTips: [
      "Use a drop lid (otoshibuta) or a parchment circle so the potatoes cook evenly in a shallow simmer.",
      "Nikujaga tastes better after a rest; the potatoes soak up the sweet-savory broth.",
    ],
    nutrition: {
      protein: 22,
      carbs: 42,
      fat: 16,
      fiber: 5,
      sugar: 14,
      sodium: 980,
      saturatedFat: 6,
      cholesterol: 50,
    },
    ingredients: [
      { name: "Thinly sliced beef", amount: "300", unit: "g" },
      { name: "Waxy potatoes", amount: "500", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Dashi", amount: "400", unit: "ml" },
      { name: "Soy sauce", amount: "4", unit: "tbsp" },
      { name: "Mirin", amount: "3", unit: "tbsp" },
      { name: "Granulated sugar", amount: "2", unit: "tbsp" },
      { name: "Shirataki noodles", amount: "150", unit: "g" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cut the vegetables",
        durationMin: 10,
        text: "Peel and cut the potatoes into large chunks, soak briefly to remove excess starch, and drain. Cut the onion into wedges and the carrot into rangiri chunks. Rinse the shirataki.",
      },
      {
        order: 2,
        title: "Brown the beef",
        durationMin: 5,
        text: "Heat the oil in a pot. Stir-fry the beef until it just changes color, then add the onion.",
      },
      {
        order: 3,
        title: "Simmer",
        durationMin: 25,
        text: "Add the potatoes, carrot, shirataki, dashi, soy sauce, mirin, and sugar. Bring to a boil, skim, then cover with a drop lid and simmer until the potatoes are tender, about 20 minutes.",
      },
      {
        order: 4,
        title: "Reduce and serve",
        durationMin: 5,
        text: "Uncover and simmer a few minutes more so the broth reduces slightly. Rest 10 minutes if you can, then serve in bowls.",
      },
    ],
  },
  {
    slug: "oyakodon-chicken-rice-bowl",
    cuisineSlug: "japanese",
    prepTime: 25,
    calories: 580,
    difficulty: "easy",
    servings: 2,
    title: "Oyakodon Chicken Rice Bowl",
    description:
      "Chicken thigh and onion simmered in dashi, soy, mirin, and sugar, bound with softly set egg, and served over rice with mitsuba.",
    tags: ["chicken", "rice-bowl", "egg", "donburi"],
    chefTips: [
      "The egg should be barely set and still glossy; pull the pan when the white is just coagulated and the yolk is creamy.",
      "Simmer in a small skillet so the broth reduces around one bowl's worth of chicken.",
    ],
    nutrition: {
      protein: 38,
      carbs: 62,
      fat: 18,
      fiber: 2,
      sugar: 10,
      sodium: 1240,
      saturatedFat: 5,
      cholesterol: 310,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "300", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Eggs", amount: "3", unit: "pcs" },
      { name: "Dashi", amount: "150", unit: "ml" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
      { name: "Mirin", amount: "2", unit: "tbsp" },
      { name: "Granulated sugar", amount: "1", unit: "tsp" },
      { name: "Cooked Japanese rice", amount: "400", unit: "g" },
      { name: "Mitsuba or scallion", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Slice the chicken and onion",
        durationMin: 6,
        text: "Slice the chicken into bite-size pieces and the onion into thin wedges. Beat the eggs lightly, leaving distinct streaks of white and yolk.",
      },
      {
        order: 2,
        title: "Simmer the chicken",
        durationMin: 8,
        text: "In a small skillet, bring the dashi, soy sauce, mirin, and sugar to a simmer. Add the onion and cook until translucent, then the chicken, simmering until just cooked, about 5 minutes.",
      },
      {
        order: 3,
        title: "Add the egg",
        durationMin: 3,
        text: "Pour the eggs over the chicken in a circular motion. Cover and cook on low until the egg is softly set, 1 to 2 minutes.",
      },
      {
        order: 4,
        title: "Slide over rice",
        durationMin: 2,
        text: "Divide the rice between two bowls. Slide the chicken and egg over the top with the remaining broth. Garnish with mitsuba or scallion.",
      },
    ],
  },
  {
    slug: "takoyaki-octopus-balls",
    cuisineSlug: "japanese",
    prepTime: 40,
    calories: 430,
    difficulty: "medium",
    servings: 4,
    title: "Takoyaki Octopus Balls",
    description:
      "Crisp-outside, custardy-inside balls of dashi batter cooked with octopus, tenkasu, beni shoga, and scallion, finished with takoyaki sauce, mayonnaise, katsuobushi, and aonori.",
    tags: ["octopus", "street-food", "snack", "osaka"],
    chefTips: [
      "The batter should be thin, like heavy cream; a thick batter makes dense balls.",
      "Turn each ball a quarter turn as soon as a shell forms so the uncooked batter spills and seals a sphere.",
    ],
    nutrition: {
      protein: 16,
      carbs: 48,
      fat: 18,
      fiber: 2,
      sugar: 8,
      sodium: 980,
      saturatedFat: 3,
      cholesterol: 80,
    },
    ingredients: [
      { name: "Takoyaki flour or all-purpose flour", amount: "140", unit: "g" },
      { name: "Dashi", amount: "400", unit: "ml" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Boiled octopus", amount: "150", unit: "g" },
      { name: "Tenkasu (tempura scraps)", amount: "30", unit: "g" },
      { name: "Beni shoga (pickled ginger)", amount: "20", unit: "g" },
      { name: "Scallions", amount: "2", unit: "stalks" },
      { name: "Takoyaki sauce", amount: "60", unit: "ml" },
      { name: "Japanese mayonnaise", amount: "40", unit: "g" },
      { name: "Katsuobushi", amount: "5", unit: "g" },
      { name: "Aonori (green seaweed powder)", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the batter",
        durationMin: 8,
        text: "Whisk the flour with the dashi and egg until smooth and thin, like heavy cream. Rest 10 minutes. Cut the octopus into 1 cm pieces and slice the scallions and beni shoga.",
      },
      {
        order: 2,
        title: "Heat the pan",
        durationMin: 4,
        text: "Heat a takoyaki pan over medium heat and oil each well generously until the oil shimmers.",
      },
      {
        order: 3,
        title: "Fill and turn",
        durationMin: 16,
        text: "Pour batter to overflow the wells slightly. Add octopus, tenkasu, beni shoga, and scallion to each. When the edges set, turn each ball a quarter turn with a pick so uncooked batter spills and forms a sphere. Keep turning until all sides are golden, 4 to 5 minutes.",
      },
      {
        order: 4,
        title: "Sauce and serve",
        durationMin: 3,
        text: "Pile the balls on a plate. Stripe with takoyaki sauce and mayonnaise, then shower with katsuobushi and aonori. Serve immediately.",
      },
    ],
  },
  {
    slug: "dorayaki-pancakes",
    cuisineSlug: "japanese",
    prepTime: 40,
    calories: 320,
    difficulty: "easy",
    servings: 6,
    title: "Dorayaki Pancakes",
    description:
      "Soft honey-sweetened pancakes sandwiched around sweet red bean paste (anko), in the style of the classic Japanese tea snack.",
    tags: ["dessert", "pancakes", "anko", "snack"],
    chefTips: [
      "Rest the batter 15 minutes so the baking powder hydrates and the pancakes bake up fluffy and even.",
      "Cook over low-medium heat; dorayaki should be uniformly golden, not mottled or dark.",
    ],
    nutrition: {
      protein: 8,
      carbs: 56,
      fat: 7,
      fiber: 3,
      sugar: 32,
      sodium: 220,
      saturatedFat: 2,
      cholesterol: 95,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "150", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Granulated sugar", amount: "60", unit: "g" },
      { name: "Honey", amount: "2", unit: "tbsp" },
      { name: "Baking powder", amount: "1", unit: "tsp" },
      { name: "Whole milk", amount: "80", unit: "ml" },
      { name: "Anko (sweet red bean paste)", amount: "240", unit: "g" },
      { name: "Neutral oil, for the pan", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the batter",
        durationMin: 8,
        text: "Whisk the eggs, sugar, and honey until pale. Sift in the flour and baking powder, then stir in the milk until just smooth. Rest 15 minutes.",
      },
      {
        order: 2,
        title: "Cook the pancakes",
        durationMin: 16,
        text: "Lightly oil a nonstick skillet over medium-low heat. Pour 2-tablespoon rounds and cook until bubbles form and the undersides are even gold, about 2 minutes. Flip and cook 1 minute more. You need 12 pancakes.",
      },
      {
        order: 3,
        title: "Cool",
        durationMin: 5,
        text: "Cool the pancakes on a rack so steam does not soften the faces that will hold the filling.",
      },
      {
        order: 4,
        title: "Fill with anko",
        durationMin: 5,
        text: "Spread about 40 g of anko on the paler side of one pancake, leaving a 1 cm border. Cap with a second pancake and press the edges gently to seal. Repeat to make 6 dorayaki.",
      },
    ],
  },
  {
    slug: "japanese-cheesecake",
    cuisineSlug: "japanese",
    prepTime: 100,
    calories: 310,
    difficulty: "hard",
    servings: 8,
    title: "Japanese Cheesecake",
    description:
      "Souffle-style cotton cheesecake: cream cheese, eggs, sugar, cake flour, milk, butter, and lemon, baked in a water bath until tall, jiggly, and lightly browned.",
    tags: ["dessert", "cheesecake", "souffle", "baked"],
    chefTips: [
      "Whip the meringue to soft-medium peaks only; stiff peaks make the cake crack and shrink.",
      "Bake in a water bath and cool in the oven with the door ajar so the souffle settles instead of collapsing.",
    ],
    nutrition: {
      protein: 9,
      carbs: 24,
      fat: 20,
      fiber: 0,
      sugar: 18,
      sodium: 220,
      saturatedFat: 12,
      cholesterol: 155,
    },
    ingredients: [
      { name: "Cream cheese", amount: "250", unit: "g" },
      { name: "Eggs", amount: "5", unit: "pcs" },
      { name: "Granulated sugar", amount: "100", unit: "g" },
      { name: "Cake flour", amount: "50", unit: "g" },
      { name: "Whole milk", amount: "100", unit: "ml" },
      { name: "Unsalted butter", amount: "40", unit: "g" },
      { name: "Lemon juice", amount: "1", unit: "tbsp" },
      { name: "Lemon zest", amount: "1", unit: "tsp" },
      { name: "Cream of tartar", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Line the pan",
        durationMin: 8,
        text: "Line the base and sides of an 18 cm round cake pan with parchment, leaving a collar above the rim. Separate the eggs. Bring the cream cheese, butter, and milk to room temperature.",
      },
      {
        order: 2,
        title: "Make the batter",
        durationMin: 12,
        text: "Melt the cream cheese, butter, and milk over a barely simmering water bath until smooth. Off the heat, whisk in the egg yolks, lemon juice, zest, and sifted cake flour until no lumps remain. Cool slightly.",
      },
      {
        order: 3,
        title: "Whip the meringue",
        durationMin: 8,
        text: "Whip the egg whites with cream of tartar until foamy, then rain in the sugar and whip to soft-medium glossy peaks. Fold one-third into the cheese batter to loosen, then fold in the rest without deflating.",
      },
      {
        order: 4,
        title: "Bake in a water bath",
        durationMin: 70,
        text: "Pour into the pan, tap to release large bubbles, and set in a roasting tin with 3 cm of hot water. Bake at 160 C for 25 minutes, then 140 C for 40 to 45 minutes until the top is pale gold and the center still jiggles. Cool in the oven with the door ajar 30 minutes, then unmold and chill before slicing.",
      },
    ],
  },
];
