import type { DemoRecipe } from "./types";

export const koreanRecipes: DemoRecipe[] = [
  {
    slug: "kimchi-fried-rice",
    cuisineSlug: "korean",
    prepTime: 25,
    calories: 480,
    difficulty: "easy",
    servings: 2,
    title: "Kimchi Fried Rice",
    description:
      "Day-old rice wok-fried with well-fermented kimchi, gochujang, sesame oil, and scallion, crowned with a fried egg and optional diced Spam.",
    tags: ["rice", "kimchi", "weeknight", "comfort"],
    chefTips: [
      "Use sour, well-fermented kimchi and some of its brine; fresh kimchi will not give the same depth.",
      "Cold leftover rice fries without turning gummy.",
    ],
    nutrition: {
      protein: 18,
      carbs: 58,
      fat: 18,
      fiber: 3,
      sugar: 6,
      sodium: 980,
      saturatedFat: 5,
      cholesterol: 195,
    },
    ingredients: [
      { name: "Day-old cooked rice", amount: "400", unit: "g" },
      { name: "Well-fermented kimchi", amount: "200", unit: "g" },
      { name: "Gochujang", amount: "1", unit: "tbsp" },
      { name: "Toasted sesame oil", amount: "2", unit: "tsp" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Scallions", amount: "3", unit: "pcs" },
      { name: "Spam", amount: "80", unit: "g" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
      { name: "Kimchi brine", amount: "2", unit: "tbsp" },
      { name: "Toasted sesame seeds", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the kimchi",
        durationMin: 5,
        text: "Chop the kimchi into bite-size pieces. Dice the Spam and slice the scallions, keeping the greens for garnish.",
      },
      {
        order: 2,
        title: "Fry the Spam and kimchi",
        durationMin: 6,
        text: "Heat the neutral oil in a wok or large skillet. Crisp the Spam, then add the kimchi and stir-fry until the edges caramelize. Stir in gochujang and kimchi brine.",
      },
      {
        order: 3,
        title: "Add the rice",
        durationMin: 6,
        text: "Add the cold rice, breaking up clumps. Stir-fry until every grain is coated and hot. Finish with sesame oil and most of the scallion whites.",
      },
      {
        order: 4,
        title: "Fry the eggs and serve",
        durationMin: 6,
        text: "Fry the eggs sunny-side up. Divide the rice between bowls, top with an egg, scallion greens, and sesame seeds.",
      },
    ],
  },
  {
    slug: "korean-beef-bulgogi-bowl",
    cuisineSlug: "korean",
    prepTime: 40,
    calories: 560,
    difficulty: "medium",
    servings: 4,
    title: "Korean Beef Bulgogi Bowl",
    description:
      "Thinly sliced ribeye marinated in soy, grated Asian pear, garlic, sesame oil, and brown sugar, quickly seared and served over rice with scallion.",
    tags: ["beef", "bbq", "rice-bowl", "dinner"],
    chefTips: [
      "Freeze the ribeye 20 minutes so you can slice it paper-thin across the grain.",
      "The grated pear tenderizes the meat and adds a gentle sweetness — do not skip it.",
    ],
    nutrition: {
      protein: 34,
      carbs: 48,
      fat: 24,
      fiber: 2,
      sugar: 12,
      sodium: 890,
      saturatedFat: 8,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Ribeye steak", amount: "600", unit: "g" },
      { name: "Soy sauce", amount: "60", unit: "ml" },
      { name: "Asian pear", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Toasted sesame oil", amount: "1", unit: "tbsp" },
      { name: "Brown sugar", amount: "2", unit: "tbsp" },
      { name: "Cooked short-grain rice", amount: "600", unit: "g" },
      { name: "Scallions", amount: "3", unit: "pcs" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Toasted sesame seeds", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Slice the beef",
        durationMin: 10,
        text: "Partially freeze the ribeye, then slice very thinly across the grain. Slice the onion into thin wedges.",
      },
      {
        order: 2,
        title: "Make the marinade",
        durationMin: 8,
        text: "Grate the pear and mix with soy sauce, minced garlic, sesame oil, and brown sugar. Toss the beef and onion in the marinade and rest 20 minutes.",
      },
      {
        order: 3,
        title: "Sear the bulgogi",
        durationMin: 10,
        text: "Heat a wide skillet or grill pan until very hot. Cook the beef in batches so it browns instead of stewing, 2 to 3 minutes per batch.",
      },
      {
        order: 4,
        title: "Build the bowls",
        durationMin: 5,
        text: "Spoon hot rice into bowls, pile the bulgogi on top, and finish with sliced scallion and sesame seeds.",
      },
    ],
  },
  {
    slug: "dakgalbi-spicy-chicken",
    cuisineSlug: "korean",
    prepTime: 45,
    calories: 520,
    difficulty: "medium",
    servings: 4,
    title: "Dakgalbi Spicy Chicken",
    description:
      "A Chuncheon-style stir-fry of chicken in gochujang and gochugaru with cabbage, sweet potato, rice cakes, onion, and garlic, cooked on a wide pan.",
    tags: ["chicken", "spicy", "stir-fry", "dinner"],
    chefTips: [
      "The sweet potato should be in thin half-moons so it cooks with the chicken, not after.",
      "If you have leftover sauce, stir in cooked rice at the end for dakgalbi fried rice.",
    ],
    nutrition: {
      protein: 36,
      carbs: 42,
      fat: 22,
      fiber: 5,
      sugar: 10,
      sodium: 920,
      saturatedFat: 5,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "700", unit: "g" },
      { name: "Gochujang", amount: "3", unit: "tbsp" },
      { name: "Gochugaru", amount: "1.5", unit: "tbsp" },
      { name: "Napa cabbage", amount: "300", unit: "g" },
      { name: "Sweet potato", amount: "1", unit: "pcs" },
      { name: "Tteok rice cakes", amount: "200", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "5", unit: "cloves" },
      { name: "Soy sauce", amount: "1", unit: "tbsp" },
      { name: "Toasted sesame oil", amount: "1", unit: "tsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the sauce",
        durationMin: 5,
        text: "Stir gochujang, gochugaru, soy sauce, minced garlic, sugar, and sesame oil into a thick paste.",
      },
      {
        order: 2,
        title: "Cut the vegetables",
        durationMin: 10,
        text: "Cut the chicken into bite-size pieces. Slice cabbage, onion, and sweet potato. Soak the rice cakes in warm water if they are hard.",
      },
      {
        order: 3,
        title: "Coat the chicken",
        durationMin: 8,
        text: "Toss the chicken with the sauce and let it sit 10 minutes while you heat a wide skillet or tabletop pan.",
      },
      {
        order: 4,
        title: "Stir-fry everything",
        durationMin: 18,
        text: "Add a little oil, then chicken, sweet potato, cabbage, onion, and rice cakes. Stir and press so the sauce coats everything. Cook until the chicken is done and the sweet potato is tender.",
      },
      {
        order: 5,
        title: "Serve",
        durationMin: 4,
        text: "Bring the pan to the table if you can. Serve with extra lettuce leaves for wrapping, or stir leftover sauce into rice.",
      },
    ],
  },
  {
    slug: "korean-braised-beef",
    cuisineSlug: "korean",
    prepTime: 130,
    calories: 610,
    difficulty: "hard",
    servings: 6,
    title: "Korean Braised Beef",
    description:
      "Galbijjim-style beef short ribs braised in soy, garlic, and pear with onion, carrot, jujube, and shiitake, finished with sesame oil.",
    tags: ["beef", "braise", "celebration", "comfort"],
    chefTips: [
      "Parboil the ribs first to remove scum so the braising liquid stays clear and clean-tasting.",
      "Dried jujubes add a gentle sweetness that sugar alone cannot.",
    ],
    nutrition: {
      protein: 38,
      carbs: 22,
      fat: 40,
      fiber: 3,
      sugar: 12,
      sodium: 980,
      saturatedFat: 16,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Beef short ribs", amount: "1.5", unit: "kg" },
      { name: "Soy sauce", amount: "80", unit: "ml" },
      { name: "Garlic", amount: "8", unit: "cloves" },
      { name: "Asian pear", amount: "1", unit: "pcs" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Carrot", amount: "2", unit: "pcs" },
      { name: "Dried jujubes", amount: "6", unit: "pcs" },
      { name: "Dried shiitake mushrooms", amount: "6", unit: "pcs" },
      { name: "Toasted sesame oil", amount: "1", unit: "tbsp" },
      { name: "Brown sugar", amount: "2", unit: "tbsp" },
      { name: "Fresh ginger", amount: "20", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Parboil the ribs",
        durationMin: 15,
        text: "Cover the short ribs with cold water, bring to a boil, and simmer 8 minutes. Drain and rinse the bones so the braise stays clean. Soak the shiitake in warm water.",
      },
      {
        order: 2,
        title: "Build the braising liquid",
        durationMin: 10,
        text: "Grate the pear and mix with soy sauce, brown sugar, smashed garlic, sliced ginger, and 600 ml water or the shiitake soaking liquid.",
      },
      {
        order: 3,
        title: "Braise the ribs",
        durationMin: 80,
        text: "Return the ribs to a pot with the liquid, onion wedges, carrot chunks, jujubes, and shiitake. Simmer covered until the meat is tender, about 80 minutes, skimming fat.",
      },
      {
        order: 4,
        title: "Reduce and finish",
        durationMin: 15,
        text: "Uncover and reduce the sauce until it is glossy and coats the ribs. Stir in sesame oil. Serve with rice and kimchi.",
      },
    ],
  },
  {
    slug: "jjajangmyeon-black-bean-noodles",
    cuisineSlug: "korean",
    prepTime: 40,
    calories: 690,
    difficulty: "medium",
    servings: 4,
    title: "Jjajangmyeon Black Bean Noodles",
    description:
      "Chewy wheat noodles in a rich chunjang black-bean sauce with pork, onion, zucchini, and potato, finished with raw cucumber.",
    tags: ["noodles", "pork", "comfort", "korean-chinese"],
    chefTips: [
      "Fry the chunjang in oil until it smells nutty; raw paste tastes harsh and dusty.",
      "A little potato starch slurry at the end gives the sauce its restaurant sheen.",
    ],
    nutrition: {
      protein: 24,
      carbs: 88,
      fat: 26,
      fiber: 6,
      sugar: 10,
      sodium: 1120,
      saturatedFat: 7,
      cholesterol: 55,
    },
    ingredients: [
      { name: "Fresh wheat noodles", amount: "600", unit: "g" },
      { name: "Chunjang black bean paste", amount: "80", unit: "g" },
      { name: "Pork shoulder", amount: "300", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Zucchini", amount: "1", unit: "pcs" },
      { name: "Potato", amount: "1", unit: "pcs" },
      { name: "Cucumber", amount: "0.5", unit: "pcs" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
      { name: "Potato starch", amount: "1", unit: "tbsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Dice the filling",
        durationMin: 10,
        text: "Dice the pork, onion, zucchini, and potato into small even cubes. Julienne the cucumber for garnish and keep it cold.",
      },
      {
        order: 2,
        title: "Fry the chunjang",
        durationMin: 8,
        text: "Heat 2 tablespoons oil and fry the chunjang, stirring, until it darkens and smells toasted, 3 to 4 minutes. Scoop it out.",
      },
      {
        order: 3,
        title: "Cook the sauce",
        durationMin: 14,
        text: "In the same pan, cook pork, then onion, potato, and zucchini. Return the fried paste, add 400 ml water and sugar, and simmer until the potato is tender. Thicken with starch mixed with a little water.",
      },
      {
        order: 4,
        title: "Boil noodles and serve",
        durationMin: 8,
        text: "Boil the wheat noodles until chewy, rinse briefly, and divide into bowls. Ladle the black bean sauce over and top with cucumber.",
      },
    ],
  },
  {
    slug: "kalguksu-noodle-soup",
    cuisineSlug: "korean",
    prepTime: 50,
    calories: 420,
    difficulty: "medium",
    servings: 4,
    title: "Kalguksu Noodle Soup",
    description:
      "Knife-cut wheat noodles in a clear anchovy-kelp broth with zucchini, potato, optional clams, and a finish of scallion.",
    tags: ["noodles", "soup", "comfort", "seafood"],
    chefTips: [
      "Pull the kelp out after 10 minutes or the broth turns slimy and bitter.",
      "Add the noodles only when the vegetables are nearly done so they do not overcook.",
    ],
    nutrition: {
      protein: 18,
      carbs: 62,
      fat: 8,
      fiber: 4,
      sugar: 3,
      sodium: 980,
      saturatedFat: 1,
      cholesterol: 25,
    },
    ingredients: [
      { name: "Knife-cut wheat noodles", amount: "400", unit: "g" },
      { name: "Dried anchovies", amount: "20", unit: "g" },
      { name: "Dried kelp", amount: "10", unit: "g" },
      { name: "Zucchini", amount: "1", unit: "pcs" },
      { name: "Potato", amount: "1", unit: "pcs" },
      { name: "Manila clams", amount: "200", unit: "g" },
      { name: "Scallions", amount: "3", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Korean soup soy sauce", amount: "2", unit: "tbsp" },
      { name: "Sesame oil", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the anchovy-kelp broth",
        durationMin: 18,
        text: "Simmer dried anchovies and kelp in 1.5 liters of water for 10 minutes. Remove the kelp, simmer 5 minutes more, then strain. Season with soup soy sauce.",
      },
      {
        order: 2,
        title: "Prep the vegetables",
        durationMin: 8,
        text: "Slice zucchini into half-moons and potato into thin bite-size pieces. Mince the garlic and slice the scallions. Scrub the clams if using.",
      },
      {
        order: 3,
        title: "Simmer vegetables and clams",
        durationMin: 12,
        text: "Return the broth to a simmer. Add potato, then zucchini, garlic, and clams. Cook until the potato is tender and the clams open.",
      },
      {
        order: 4,
        title: "Cook the noodles",
        durationMin: 8,
        text: "Add the knife-cut noodles and cook until just tender. Finish with sesame oil and scallion. Serve immediately, while the noodles are still chewy.",
      },
    ],
  },
  {
    slug: "mandu-korean-dumplings",
    cuisineSlug: "korean",
    prepTime: 60,
    calories: 380,
    difficulty: "medium",
    servings: 6,
    title: "Mandu Korean Dumplings",
    description:
      "Pork-and-tofu mandu with garlic chives, ginger, and soy, folded in thin wrappers and steamed or pan-fried until juicy.",
    tags: ["dumplings", "pork", "appetizer", "freezer-friendly"],
    chefTips: [
      "Squeeze the tofu and the chopped chives dry so the filling is juicy, not wet.",
      "A drop of sesame oil in the filling is enough; too much makes the wrappers slip.",
    ],
    nutrition: {
      protein: 18,
      carbs: 36,
      fat: 16,
      fiber: 2,
      sugar: 2,
      sodium: 720,
      saturatedFat: 5,
      cholesterol: 45,
    },
    ingredients: [
      { name: "Round dumpling wrappers", amount: "40", unit: "pcs" },
      { name: "Ground pork", amount: "300", unit: "g" },
      { name: "Firm tofu", amount: "150", unit: "g" },
      { name: "Garlic chives", amount: "80", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Fresh ginger", amount: "15", unit: "g" },
      { name: "Soy sauce", amount: "1.5", unit: "tbsp" },
      { name: "Toasted sesame oil", amount: "1", unit: "tsp" },
      { name: "Napa cabbage", amount: "80", unit: "g" },
      { name: "Egg", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Prepare the filling",
        durationMin: 15,
        text: "Squeeze the tofu dry and crumble it. Salt and squeeze the chopped cabbage. Finely chop the garlic chives. Mix with pork, minced garlic, grated ginger, soy sauce, sesame oil, and the egg.",
      },
      {
        order: 2,
        title: "Fold the mandu",
        durationMin: 25,
        text: "Place a teaspoon of filling on each wrapper, wet the edge, and fold into half-moons, pleating if you like. Keep finished dumplings under a cloth so they do not dry.",
      },
      {
        order: 3,
        title: "Cook the dumplings",
        durationMin: 12,
        text: "Steam 10 minutes, or pan-fry until the bottoms are golden, then add a splash of water and cover to steam through.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 3,
        text: "Serve hot with a dip of soy sauce, vinegar, and a pinch of gochugaru.",
      },
    ],
  },
  {
    slug: "korean-corn-cheese",
    cuisineSlug: "korean",
    prepTime: 20,
    calories: 310,
    difficulty: "easy",
    servings: 4,
    title: "Korean Corn Cheese",
    description:
      "A bubbling skillet of sweet corn bound with mayonnaise, butter, a pinch of sugar, and a blanket of melted mozzarella, finished with scallion.",
    tags: ["side", "cheese", "anju", "quick"],
    chefTips: [
      "Drain canned corn very well or the skillet will weep instead of blister.",
      "A little sugar is traditional; it makes the corn taste like Korean corn, not American succotash.",
    ],
    nutrition: {
      protein: 10,
      carbs: 22,
      fat: 20,
      fiber: 2,
      sugar: 8,
      sodium: 480,
      saturatedFat: 8,
      cholesterol: 40,
    },
    ingredients: [
      { name: "Canned corn", amount: "340", unit: "g" },
      { name: "Mozzarella", amount: "120", unit: "g" },
      { name: "Mayonnaise", amount: "3", unit: "tbsp" },
      { name: "Unsalted butter", amount: "20", unit: "g" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Scallions", amount: "2", unit: "pcs" },
      { name: "Black pepper", amount: "0.25", unit: "tsp" },
      { name: "Gochugaru", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Drain the corn",
        durationMin: 4,
        text: "Drain the corn thoroughly and pat dry. Slice the scallions. Grate or tear the mozzarella.",
      },
      {
        order: 2,
        title: "Mix the filling",
        durationMin: 4,
        text: "Stir corn with mayonnaise, melted butter, sugar, most of the scallion, and a pinch of pepper.",
      },
      {
        order: 3,
        title: "Bake or broil",
        durationMin: 10,
        text: "Spread in a small ovenproof skillet, cover with mozzarella, and broil or bake at 220 C until the cheese is melted and spotted brown.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Scatter remaining scallion and a pinch of gochugaru. Serve bubbling, with spoons.",
      },
    ],
  },
  {
    slug: "pajeon-green-onion-pancake",
    cuisineSlug: "korean",
    prepTime: 30,
    calories: 340,
    difficulty: "medium",
    servings: 4,
    title: "Pajeon Green Onion Pancake",
    description:
      "A savory Korean pancake packed with scallions in a light batter of flour, egg, and icy water, optionally with squid, served with a soy-vinegar dip.",
    tags: ["pancake", "appetizer", "rainy-day", "anju"],
    chefTips: [
      "Icy water keeps the batter from turning bready; buchim garu gives an even crisper edge if you have it.",
      "Do not flip until the underside is deeply golden or the pancake will tear.",
    ],
    nutrition: {
      protein: 12,
      carbs: 38,
      fat: 16,
      fiber: 3,
      sugar: 3,
      sodium: 680,
      saturatedFat: 3,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Scallions", amount: "250", unit: "g" },
      { name: "All-purpose flour", amount: "150", unit: "g" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Ice water", amount: "180", unit: "ml" },
      { name: "Squid", amount: "100", unit: "g" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
      { name: "Rice vinegar", amount: "1", unit: "tbsp" },
      { name: "Neutral oil", amount: "4", unit: "tbsp" },
      { name: "Gochugaru", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the dip",
        durationMin: 3,
        text: "Stir soy sauce, rice vinegar, a pinch of gochugaru, and a splash of water. Set aside.",
      },
      {
        order: 2,
        title: "Mix the batter",
        durationMin: 7,
        text: "Whisk flour, egg, and ice water into a thin batter. Cut scallions into 8 cm lengths. Slice the squid into rings if using and fold both into the batter.",
      },
      {
        order: 3,
        title: "Fry the pajeon",
        durationMin: 14,
        text: "Heat a generous film of oil in a wide skillet. Pour in half the batter, spreading the scallions evenly. Cook over medium heat until the bottom is golden and set, then flip and cook the other side. Repeat.",
      },
      {
        order: 4,
        title: "Cut and serve",
        durationMin: 3,
        text: "Cut into squares and serve immediately with the soy-vinegar dip.",
      },
    ],
  },
  {
    slug: "bossam-pork-wraps",
    cuisineSlug: "korean",
    prepTime: 90,
    calories: 540,
    difficulty: "medium",
    servings: 6,
    title: "Bossam Pork Wraps",
    description:
      "Pork belly simmered with doenjang, saeujeot, ginger, and garlic, sliced and wrapped in cabbage leaves with ssamjang and radish kimchi.",
    tags: ["pork", "banquet", "wraps", "dinner"],
    chefTips: [
      "The brine should taste salty and a little funky from the shrimp sauce; that is what seasons the pork from the inside.",
      "Chill the cooked belly briefly so you can slice it thin and neat.",
    ],
    nutrition: {
      protein: 28,
      carbs: 12,
      fat: 42,
      fiber: 3,
      sugar: 4,
      sodium: 1180,
      saturatedFat: 15,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Pork belly", amount: "1.2", unit: "kg" },
      { name: "Doenjang", amount: "2", unit: "tbsp" },
      { name: "Saeujeot salted shrimp", amount: "1", unit: "tbsp" },
      { name: "Fresh ginger", amount: "30", unit: "g" },
      { name: "Garlic", amount: "8", unit: "cloves" },
      { name: "Napa cabbage leaves", amount: "12", unit: "pcs" },
      { name: "Ssamjang", amount: "80", unit: "g" },
      { name: "Radish kimchi", amount: "200", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Whole black peppercorns", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Simmer the pork",
        durationMin: 60,
        text: "Cover the pork belly with water. Add doenjang, saeujeot, ginger slices, smashed garlic, onion, and peppercorns. Simmer gently until a skewer slides in easily, about 55 minutes.",
      },
      {
        order: 2,
        title: "Blanch the cabbage",
        durationMin: 8,
        text: "Blanch the cabbage leaves until just wilted and flexible. Shock in cold water and drain.",
      },
      {
        order: 3,
        title: "Slice the pork",
        durationMin: 10,
        text: "Lift the belly, rest 10 minutes, and slice thinly against the grain. Arrange on a platter.",
      },
      {
        order: 4,
        title: "Wrap and eat",
        durationMin: 8,
        text: "Each diner wraps a slice of pork in cabbage with a smear of ssamjang and a piece of radish kimchi.",
      },
    ],
  },
  {
    slug: "la-galbi-korean-ribs",
    cuisineSlug: "korean",
    prepTime: 50,
    calories: 580,
    difficulty: "medium",
    servings: 4,
    title: "LA Galbi Korean Ribs",
    description:
      "Flanken-cut short ribs marinated in soy, grated pear, garlic, sesame oil, brown sugar, and onion, then grilled until caramelized at the edges.",
    tags: ["beef", "bbq", "grill", "dinner"],
    chefTips: [
      "Score the meat between the bones so the marinade reaches the center.",
      "Grill over high heat; LA galbi should char in minutes, not stew.",
    ],
    nutrition: {
      protein: 36,
      carbs: 18,
      fat: 38,
      fiber: 1,
      sugar: 14,
      sodium: 920,
      saturatedFat: 14,
      cholesterol: 120,
    },
    ingredients: [
      { name: "Flanken-cut short ribs", amount: "1", unit: "kg" },
      { name: "Soy sauce", amount: "80", unit: "ml" },
      { name: "Asian pear", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "6", unit: "cloves" },
      { name: "Toasted sesame oil", amount: "1.5", unit: "tbsp" },
      { name: "Brown sugar", amount: "3", unit: "tbsp" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Rice wine", amount: "2", unit: "tbsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Toasted sesame seeds", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Score the ribs",
        durationMin: 8,
        text: "Pat the flanken ribs dry and score the meat in a shallow crosshatch so the marinade can enter.",
      },
      {
        order: 2,
        title: "Blend the marinade",
        durationMin: 8,
        text: "Blend or grate the pear and onion. Mix with soy sauce, minced garlic, sesame oil, brown sugar, rice wine, and pepper. Coat the ribs and marinate at least 30 minutes, or overnight.",
      },
      {
        order: 3,
        title: "Grill",
        durationMin: 12,
        text: "Grill over high heat, 3 to 4 minutes per side, until the edges caramelize and the meat is just cooked. Watch the sugar so it chars, not burns.",
      },
      {
        order: 4,
        title: "Rest and serve",
        durationMin: 5,
        text: "Rest a few minutes, scatter sesame seeds, and serve with lettuce, rice, and ssamjang.",
      },
    ],
  },
  {
    slug: "spicy-korean-cucumber-salad",
    cuisineSlug: "korean",
    prepTime: 20,
    calories: 70,
    difficulty: "easy",
    servings: 4,
    title: "Spicy Korean Cucumber Salad",
    description:
      "Oi muchim: salted cucumber tossed with gochugaru, vinegar, garlic, sesame oil, sugar, and scallion until crisp, spicy, and bright.",
    tags: ["banchan", "salad", "spicy", "quick"],
    chefTips: [
      "Salt the cucumber first, then squeeze; the dressing clings instead of pooling.",
      "Eat it the same day while the cucumbers still snap.",
    ],
    nutrition: {
      protein: 1,
      carbs: 8,
      fat: 4,
      fiber: 1,
      sugar: 5,
      sodium: 420,
      saturatedFat: 0,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Korean or Persian cucumbers", amount: "400", unit: "g" },
      { name: "Gochugaru", amount: "1", unit: "tbsp" },
      { name: "Rice vinegar", amount: "1.5", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Toasted sesame oil", amount: "1", unit: "tsp" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Scallion", amount: "1", unit: "pcs" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Toasted sesame seeds", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Salt the cucumber",
        durationMin: 8,
        text: "Slice the cucumbers into half-moons or smash them into chunks. Toss with salt and rest 8 minutes, then squeeze out the liquid.",
      },
      {
        order: 2,
        title: "Mix the dressing",
        durationMin: 4,
        text: "Stir gochugaru, vinegar, minced garlic, sesame oil, sugar, and sliced scallion.",
      },
      {
        order: 3,
        title: "Toss",
        durationMin: 3,
        text: "Toss the cucumbers with the dressing until every piece is stained red. Taste for salt, sugar, and heat.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Scatter sesame seeds and serve as banchan. Best within a few hours.",
      },
    ],
  },
  {
    slug: "korean-potato-salad",
    cuisineSlug: "korean",
    prepTime: 35,
    calories: 240,
    difficulty: "easy",
    servings: 6,
    title: "Korean Potato Salad",
    description:
      "A creamy picnic salad of mashed potato with apple, cucumber, carrot, corn, and mayonnaise — sweeter and softer than a Western potato salad.",
    tags: ["banchan", "salad", "side", "picnic"],
    chefTips: [
      "Mash the potatoes while warm so they turn fluffy, then cool before adding mayo.",
      "Salt and squeeze the cucumber so it does not water down the salad.",
    ],
    nutrition: {
      protein: 5,
      carbs: 28,
      fat: 12,
      fiber: 3,
      sugar: 8,
      sodium: 380,
      saturatedFat: 2,
      cholesterol: 45,
    },
    ingredients: [
      { name: "Potatoes", amount: "600", unit: "g" },
      { name: "Apple", amount: "1", unit: "pcs" },
      { name: "Cucumber", amount: "0.5", unit: "pcs" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Canned corn", amount: "80", unit: "g" },
      { name: "Mayonnaise", amount: "80", unit: "g" },
      { name: "Hard-boiled eggs", amount: "2", unit: "pcs" },
      { name: "Sugar", amount: "1", unit: "tsp" },
      { name: "Kosher salt", amount: "0.75", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Boil the potatoes",
        durationMin: 18,
        text: "Peel and chunk the potatoes. Boil in salted water until very tender. Drain and mash while warm, leaving a little texture.",
      },
      {
        order: 2,
        title: "Prep the mix-ins",
        durationMin: 10,
        text: "Dice the apple and cucumber. Salt the cucumber briefly and squeeze dry. Blanch diced carrot until just tender. Drain the corn. Chop the eggs.",
      },
      {
        order: 3,
        title: "Fold the salad",
        durationMin: 5,
        text: "When the potato is just warm, fold in mayonnaise, sugar, salt, apple, cucumber, carrot, corn, and egg.",
      },
      {
        order: 4,
        title: "Chill",
        durationMin: 2,
        text: "Taste and adjust salt and sweetness. Chill before serving as banchan.",
      },
    ],
  },
  {
    slug: "yakgwa-honey-cookies",
    cuisineSlug: "korean",
    prepTime: 80,
    calories: 220,
    difficulty: "hard",
    servings: 12,
    title: "Yakgwa Honey Cookies",
    description:
      "Flower-stamped wheat cookies fried in oil, then soaked in a ginger-honey and rice-syrup bath, finished with pine nuts.",
    tags: ["dessert", "cookie", "holiday", "fried"],
    chefTips: [
      "Fry low and slow so the yakgwa cook through before they brown; rushed oil makes a hard shell and a raw center.",
      "Soak while still warm so the jocheong syrup is absorbed, not just coated.",
    ],
    nutrition: {
      protein: 3,
      carbs: 32,
      fat: 10,
      fiber: 1,
      sugar: 18,
      sodium: 40,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "250", unit: "g" },
      { name: "Toasted sesame oil", amount: "40", unit: "ml" },
      { name: "Honey", amount: "80", unit: "g" },
      { name: "Rice syrup", amount: "150", unit: "g" },
      { name: "Fresh ginger", amount: "30", unit: "g" },
      { name: "Pine nuts", amount: "20", unit: "g" },
      { name: "Rice wine", amount: "2", unit: "tbsp" },
      { name: "Neutral frying oil", amount: "800", unit: "ml" },
      { name: "Water", amount: "80", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the dough",
        durationMin: 15,
        text: "Rub sesame oil into the flour until it looks like damp sand. Add 2 tablespoons honey, rice wine, and just enough water to form a firm dough. Rest 20 minutes.",
      },
      {
        order: 2,
        title: "Cut the cookies",
        durationMin: 12,
        text: "Roll the dough 8 mm thick and cut into flower or diamond shapes, pressing a pattern if you have a yakgwa mold. Prick the centers so they do not puff too much.",
      },
      {
        order: 3,
        title: "Fry gently",
        durationMin: 25,
        text: "Heat oil to about 130 C and fry the cookies, raising the heat gradually to 160 C, until they are deep amber and cooked through, 10 to 12 minutes per batch.",
      },
      {
        order: 4,
        title: "Soak in syrup",
        durationMin: 20,
        text: "Simmer remaining honey, rice syrup, sliced ginger, and a splash of water. Soak the warm cookies in the syrup 15 minutes, then lift out and top with pine nuts. Dry on a rack.",
      },
    ],
  },
  {
    slug: "bungeoppang-fish-pastry",
    cuisineSlug: "korean",
    prepTime: 35,
    calories: 260,
    difficulty: "medium",
    servings: 6,
    title: "Bungeoppang Fish Pastry",
    description:
      "A street-cart batter of wheat flour cooked in a fish-shaped mold around a pocket of sweet red bean paste, crisp outside and soft within.",
    tags: ["dessert", "street-food", "pastry", "sweet"],
    chefTips: [
      "A fish mold is traditional; a well-greased waffle iron works if you accept a different shape.",
      "The batter should be pourable, like thin pancake batter, so it seals around the bean paste.",
    ],
    nutrition: {
      protein: 6,
      carbs: 48,
      fat: 6,
      fiber: 3,
      sugar: 18,
      sodium: 180,
      saturatedFat: 1,
      cholesterol: 35,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "200", unit: "g" },
      { name: "Sweet red bean paste", amount: "250", unit: "g" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Milk", amount: "220", unit: "ml" },
      { name: "Sugar", amount: "2", unit: "tbsp" },
      { name: "Baking powder", amount: "1", unit: "tsp" },
      { name: "Vanilla extract", amount: "0.5", unit: "tsp" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
      { name: "Salt", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the batter",
        durationMin: 8,
        text: "Whisk flour, sugar, baking powder, and salt. Add egg, milk, vanilla, and oil and whisk until smooth. Rest 10 minutes.",
      },
      {
        order: 2,
        title: "Heat the mold",
        durationMin: 5,
        text: "Heat a bungeoppang mold or waffle iron and brush lightly with oil. The surface should sizzle a drop of batter.",
      },
      {
        order: 3,
        title: "Fill and cook",
        durationMin: 16,
        text: "Pour a thin layer of batter, add a spoon of red bean paste, and cover with more batter. Close the mold and cook until golden and crisp, 3 to 4 minutes per side. Repeat.",
      },
      {
        order: 4,
        title: "Serve warm",
        durationMin: 2,
        text: "Eat the pastries hot from the mold, when the shell is crisp and the bean paste is molten.",
      },
    ],
  },
];
