import type { DemoRecipe } from "./types";

export const mediterraneanRecipes: DemoRecipe[] = [
  {
    slug: "greek-chicken-gyro",
    cuisineSlug: "mediterranean",
    prepTime: 45,
    calories: 540,
    difficulty: "medium",
    servings: 4,
    title: "Greek Chicken Gyro",
    description:
      "Oregano-and-lemon marinated chicken thighs, sliced thin and tucked into warm pita with tomato, onion, and a cool cucumber-garlic tzatziki.",
    tags: ["chicken", "greek", "street-food", "dinner"],
    chefTips: [
      "Marinate the thighs at least 30 minutes so the lemon and oregano penetrate the meat.",
      "Pat the grated cucumber dry before folding it into the yogurt or the tzatziki will weep.",
    ],
    nutrition: {
      protein: 38,
      carbs: 42,
      fat: 24,
      fiber: 3,
      sugar: 6,
      sodium: 720,
      saturatedFat: 6,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "700", unit: "g" },
      { name: "Dried oregano", amount: "2", unit: "tsp" },
      { name: "Garlic", amount: "5", unit: "cloves" },
      { name: "Extra virgin olive oil", amount: "60", unit: "ml" },
      { name: "Lemon", amount: "2", unit: "pcs" },
      { name: "Pita bread", amount: "4", unit: "pcs" },
      { name: "Tomato", amount: "2", unit: "pcs" },
      { name: "Red onion", amount: "1", unit: "pcs" },
      { name: "Greek yogurt", amount: "200", unit: "g" },
      { name: "Cucumber", amount: "1", unit: "pcs" },
      { name: "Fresh dill", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate the chicken",
        durationMin: 15,
        text: "Toss the chicken thighs with oregano, 3 minced garlic cloves, 40 ml olive oil, the zest and juice of 1 lemon, and a pinch of salt. Rest at least 30 minutes, or up to overnight in the fridge.",
      },
      {
        order: 2,
        title: "Make the tzatziki",
        durationMin: 10,
        text: "Grate the cucumber, squeeze out the liquid, and fold it into the Greek yogurt with the remaining garlic, dill, a splash of lemon juice, and a drizzle of olive oil. Chill until serving.",
      },
      {
        order: 3,
        title: "Grill the chicken",
        durationMin: 14,
        text: "Grill or pan-sear the thighs over medium-high heat until charred at the edges and cooked through, 6 to 7 minutes per side. Rest 5 minutes, then slice across the grain.",
      },
      {
        order: 4,
        title: "Warm the pita and assemble",
        durationMin: 6,
        text: "Warm the pita until pliable. Fill with sliced chicken, tomato wedges, thin red onion, and a generous spoon of tzatziki. Serve immediately.",
      },
    ],
  },
  {
    slug: "chicken-souvlaki",
    cuisineSlug: "mediterranean",
    prepTime: 40,
    calories: 420,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Souvlaki",
    description:
      "Cubes of chicken marinated in oregano, lemon, garlic, and olive oil, threaded on skewers and grilled until juicy, with warm pita on the side.",
    tags: ["chicken", "greek", "grill", "skewers"],
    chefTips: [
      "Soak wooden skewers in water for 20 minutes so they do not burn on the grill.",
      "Do not overcrowd the cubes; a little space helps the edges caramelize.",
    ],
    nutrition: {
      protein: 36,
      carbs: 28,
      fat: 18,
      fiber: 2,
      sugar: 3,
      sodium: 580,
      saturatedFat: 4,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Boneless chicken breast", amount: "700", unit: "g" },
      { name: "Dried oregano", amount: "2", unit: "tsp" },
      { name: "Lemon", amount: "2", unit: "pcs" },
      { name: "Extra virgin olive oil", amount: "50", unit: "ml" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Wooden skewers", amount: "8", unit: "pcs" },
      { name: "Pita bread", amount: "4", unit: "pcs" },
      { name: "Red onion", amount: "1", unit: "pcs" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cube and marinate",
        durationMin: 12,
        text: "Cut the chicken into 3 cm cubes. Toss with oregano, lemon zest and juice, olive oil, minced garlic, salt, and pepper. Rest 20 to 30 minutes.",
      },
      {
        order: 2,
        title: "Thread the skewers",
        durationMin: 8,
        text: "Thread the chicken onto soaked skewers, alternating with chunks of red onion if you like. Leave a little space between pieces.",
      },
      {
        order: 3,
        title: "Grill the souvlaki",
        durationMin: 14,
        text: "Grill over medium-high heat, turning every few minutes, until the chicken is cooked through and lightly charred, about 12 minutes.",
      },
      {
        order: 4,
        title: "Serve with pita",
        durationMin: 6,
        text: "Warm the pita and serve alongside the skewers with extra lemon wedges. A spoon of tzatziki is welcome if you have it.",
      },
    ],
  },
  {
    slug: "beef-kofta",
    cuisineSlug: "mediterranean",
    prepTime: 35,
    calories: 390,
    difficulty: "medium",
    servings: 4,
    title: "Beef Kofta",
    description:
      "Grilled ground-beef kofta seasoned with onion, parsley, cumin, coriander, cinnamon, and garlic, shaped onto skewers and cooked until browned.",
    tags: ["beef", "grill", "middle-eastern", "dinner"],
    chefTips: [
      "Grate the onion and squeeze out the juice so the kofta hold together on the grill.",
      "Chill the shaped kofta 15 minutes before grilling so they keep their form.",
    ],
    nutrition: {
      protein: 28,
      carbs: 6,
      fat: 28,
      fiber: 1,
      sugar: 2,
      sodium: 640,
      saturatedFat: 10,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Ground beef", amount: "600", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Flat-leaf parsley", amount: "30", unit: "g" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Ground coriander", amount: "1", unit: "tsp" },
      { name: "Ground cinnamon", amount: "0.5", unit: "tsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Olive oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the kofta",
        durationMin: 10,
        text: "Grate the onion and squeeze dry. Mix with the ground beef, chopped parsley, cumin, coriander, cinnamon, minced garlic, salt, and pepper until just combined.",
      },
      {
        order: 2,
        title: "Shape onto skewers",
        durationMin: 8,
        text: "Divide into 8 portions and mold around metal or soaked wooden skewers into long ovals. Chill 15 minutes if the mixture feels soft.",
      },
      {
        order: 3,
        title: "Grill",
        durationMin: 12,
        text: "Brush lightly with olive oil. Grill over medium-high heat, turning, until browned and cooked through, 10 to 12 minutes.",
      },
      {
        order: 4,
        title: "Rest and serve",
        durationMin: 5,
        text: "Rest a few minutes off the heat. Serve with pita, salad, or a yogurt sauce.",
      },
    ],
  },
  {
    slug: "lamb-kofta",
    cuisineSlug: "mediterranean",
    prepTime: 35,
    calories: 430,
    difficulty: "medium",
    servings: 4,
    title: "Lamb Kofta",
    description:
      "Ground lamb mixed with parsley, onion, allspice, cumin, and optional pine nuts, shaped into kofta and grilled until the edges crisp.",
    tags: ["lamb", "grill", "middle-eastern", "dinner"],
    chefTips: [
      "A pinch of allspice is the Levantine note that makes lamb kofta taste like home cooking, not a burger.",
      "Toast the pine nuts first so they stay fragrant inside the meat.",
    ],
    nutrition: {
      protein: 26,
      carbs: 5,
      fat: 34,
      fiber: 1,
      sugar: 2,
      sodium: 620,
      saturatedFat: 12,
      cholesterol: 105,
    },
    ingredients: [
      { name: "Ground lamb", amount: "600", unit: "g" },
      { name: "Flat-leaf parsley", amount: "35", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Ground allspice", amount: "1", unit: "tsp" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Pine nuts", amount: "30", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Olive oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Toast the pine nuts",
        durationMin: 4,
        text: "Toast the pine nuts in a dry pan until golden, then chop roughly. Grate the onion and squeeze out the moisture.",
      },
      {
        order: 2,
        title: "Mix and shape",
        durationMin: 10,
        text: "Combine lamb, parsley, onion, allspice, cumin, pine nuts, minced garlic, salt, and pepper. Shape into 8 oval kofta or sausage shapes around skewers.",
      },
      {
        order: 3,
        title: "Grill the kofta",
        durationMin: 12,
        text: "Brush with olive oil and grill over medium-high heat, turning, until browned outside and just cooked through, about 12 minutes.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 4,
        text: "Rest briefly. Serve with lemon, herbs, and a cucumber-yogurt sauce.",
      },
    ],
  },
  {
    slug: "greek-moussaka",
    cuisineSlug: "mediterranean",
    prepTime: 110,
    calories: 580,
    difficulty: "hard",
    servings: 6,
    title: "Greek Moussaka",
    description:
      "Layered eggplant and potato with a cinnamon-and-clove lamb ragù, a splash of red wine, and a nutmeg béchamel enriched with egg yolk.",
    tags: ["baked", "greek", "lamb", "comfort"],
    chefTips: [
      "Salt and roast the eggplant first so the bake is silky, not watery.",
      "Let the moussaka rest 20 minutes after baking so the layers set when you slice.",
    ],
    nutrition: {
      protein: 28,
      carbs: 32,
      fat: 38,
      fiber: 6,
      sugar: 9,
      sodium: 820,
      saturatedFat: 16,
      cholesterol: 165,
    },
    ingredients: [
      { name: "Eggplant", amount: "2", unit: "pcs" },
      { name: "Waxy potatoes", amount: "500", unit: "g" },
      { name: "Ground lamb", amount: "500", unit: "g" },
      { name: "Ground cinnamon", amount: "1", unit: "tsp" },
      { name: "Ground cloves", amount: "0.25", unit: "tsp" },
      { name: "Canned tomatoes", amount: "400", unit: "g" },
      { name: "Red wine", amount: "80", unit: "ml" },
      { name: "Unsalted butter", amount: "50", unit: "g" },
      { name: "All-purpose flour", amount: "50", unit: "g" },
      { name: "Whole milk", amount: "500", unit: "ml" },
      { name: "Egg yolks", amount: "2", unit: "pcs" },
      { name: "Freshly grated nutmeg", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Roast the vegetables",
        durationMin: 25,
        text: "Slice eggplant and potatoes into 8 mm rounds. Salt the eggplant 15 minutes, pat dry, then roast both with a little oil at 200 C until tender and golden.",
      },
      {
        order: 2,
        title: "Cook the ragù",
        durationMin: 25,
        text: "Brown the lamb, then add cinnamon, cloves, a pinch of nutmeg, crushed tomatoes, and red wine. Simmer until thick and the wine has cooked off.",
      },
      {
        order: 3,
        title: "Make the béchamel",
        durationMin: 15,
        text: "Melt butter, stir in flour, and cook 2 minutes. Whisk in warm milk until thick. Off the heat, beat in egg yolks and nutmeg. Season with salt.",
      },
      {
        order: 4,
        title: "Layer the moussaka",
        durationMin: 10,
        text: "In a baking dish, layer potatoes, eggplant, lamb ragù, then remaining eggplant. Pour the béchamel over the top and smooth.",
      },
      {
        order: 5,
        title: "Bake and rest",
        durationMin: 35,
        text: "Bake at 180 C until the top is golden and set, 30 to 35 minutes. Rest 20 minutes before cutting into squares.",
      },
    ],
  },
  {
    slug: "chicken-mediterranean-bowl",
    cuisineSlug: "mediterranean",
    prepTime: 35,
    calories: 510,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Mediterranean Bowl",
    description:
      "Herb-grilled chicken over lemon-herb rice with cucumber, tomato, olives, crumbled feta, a spoon of hummus, and a drizzle of olive oil.",
    tags: ["chicken", "bowl", "weeknight", "healthy"],
    chefTips: [
      "Cook the rice in a little extra lemon zest so the bowl tastes bright even under the hummus.",
      "Warm the olives slightly so their flavor opens up.",
    ],
    nutrition: {
      protein: 36,
      carbs: 44,
      fat: 22,
      fiber: 5,
      sugar: 5,
      sodium: 780,
      saturatedFat: 6,
      cholesterol: 115,
    },
    ingredients: [
      { name: "Boneless chicken breasts", amount: "600", unit: "g" },
      { name: "Cucumber", amount: "1", unit: "pcs" },
      { name: "Cherry tomatoes", amount: "250", unit: "g" },
      { name: "Kalamata olives", amount: "80", unit: "g" },
      { name: "Feta cheese", amount: "100", unit: "g" },
      { name: "Hummus", amount: "120", unit: "g" },
      { name: "Long-grain rice", amount: "200", unit: "g" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Lemon", amount: "1", unit: "pcs" },
      { name: "Dried oregano", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the lemon-herb rice",
        durationMin: 18,
        text: "Rinse the rice and cook in salted water with a strip of lemon zest. Fluff with a fork, then stir in chopped herbs if you have them and a drizzle of olive oil.",
      },
      {
        order: 2,
        title: "Season and cook the chicken",
        durationMin: 14,
        text: "Rub the chicken with oregano, minced garlic, olive oil, salt, and lemon juice. Grill or pan-sear until cooked through, then slice.",
      },
      {
        order: 3,
        title: "Prep the salad toppings",
        durationMin: 8,
        text: "Dice the cucumber, halve the tomatoes, and crumble the feta. Pit the olives if needed.",
      },
      {
        order: 4,
        title: "Assemble the bowls",
        durationMin: 5,
        text: "Divide rice among bowls. Top with chicken, cucumber, tomato, olives, feta, and a scoop of hummus. Finish with olive oil and lemon.",
      },
    ],
  },
  {
    slug: "tzatziki-dip",
    cuisineSlug: "mediterranean",
    prepTime: 20,
    calories: 110,
    difficulty: "easy",
    servings: 6,
    title: "Tzatziki Dip",
    description:
      "Thick Greek yogurt folded with squeezed grated cucumber, garlic, olive oil, red wine vinegar, and dill — the classic cooling dip for grilled meats and pita.",
    tags: ["dip", "greek", "vegetarian", "sauce"],
    chefTips: [
      "Squeeze the cucumber in a clean towel until almost dry; watery cucumber ruins the body of the dip.",
      "Make it an hour ahead so the garlic softens into the yogurt.",
    ],
    nutrition: {
      protein: 7,
      carbs: 5,
      fat: 7,
      fiber: 0,
      sugar: 4,
      sodium: 220,
      saturatedFat: 3,
      cholesterol: 12,
    },
    ingredients: [
      { name: "Greek yogurt", amount: "400", unit: "g" },
      { name: "Cucumber", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Extra virgin olive oil", amount: "2", unit: "tbsp" },
      { name: "Red wine vinegar", amount: "1", unit: "tbsp" },
      { name: "Fresh dill", amount: "15", unit: "g" },
      { name: "Kosher salt", amount: "0.75", unit: "tsp" },
      { name: "Lemon juice", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Grate and drain the cucumber",
        durationMin: 8,
        text: "Halve the cucumber, scrape out the seeds, and grate. Salt lightly, rest 5 minutes, then squeeze hard in a towel until little liquid remains.",
      },
      {
        order: 2,
        title: "Mince the garlic",
        durationMin: 3,
        text: "Mash the garlic to a paste with a pinch of salt so it disappears into the yogurt instead of leaving raw chunks.",
      },
      {
        order: 3,
        title: "Fold the tzatziki",
        durationMin: 5,
        text: "Stir yogurt, cucumber, garlic, olive oil, red wine vinegar, chopped dill, and a squeeze of lemon. Taste for salt.",
      },
      {
        order: 4,
        title: "Chill and serve",
        durationMin: 4,
        text: "Chill at least 20 minutes. Serve with a last drizzle of olive oil and extra dill. Good with pita, vegetables, or grilled meat.",
      },
    ],
  },
  {
    slug: "baba-ganoush",
    cuisineSlug: "mediterranean",
    prepTime: 50,
    calories: 160,
    difficulty: "medium",
    servings: 6,
    title: "Baba Ganoush",
    description:
      "Fire-roasted eggplant mashed with tahini, lemon, garlic, olive oil, and a pinch of cumin until smoky and creamy.",
    tags: ["dip", "levantine", "vegan", "eggplant"],
    chefTips: [
      "Char the eggplant over an open flame or under a broiler until the skin is black and the flesh collapses — that smoke is the dish.",
      "Drain the roasted flesh in a sieve so the dip stays thick, not watery.",
    ],
    nutrition: {
      protein: 4,
      carbs: 10,
      fat: 13,
      fiber: 5,
      sugar: 4,
      sodium: 280,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Eggplant", amount: "2", unit: "pcs" },
      { name: "Tahini", amount: "60", unit: "g" },
      { name: "Lemon", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Ground cumin", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Flat-leaf parsley", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Fire-roast the eggplant",
        durationMin: 25,
        text: "Prick the eggplants and roast over a gas flame, on a grill, or under a broiler, turning, until the skins are charred and the flesh is completely soft, 20 to 25 minutes.",
      },
      {
        order: 2,
        title: "Drain the flesh",
        durationMin: 8,
        text: "Cool slightly, split, and scoop the flesh into a sieve. Let it drain 5 to 10 minutes, then discard the skins.",
      },
      {
        order: 3,
        title: "Mash with tahini",
        durationMin: 8,
        text: "Mash the eggplant with tahini, lemon juice, minced garlic, cumin, and salt. Stir in most of the olive oil, keeping a little for the top.",
      },
      {
        order: 4,
        title: "Finish and serve",
        durationMin: 4,
        text: "Spoon into a shallow bowl, swirl the remaining oil on top, and scatter chopped parsley. Serve with pita or raw vegetables.",
      },
    ],
  },
  {
    slug: "tabbouleh-salad",
    cuisineSlug: "mediterranean",
    prepTime: 30,
    calories: 190,
    difficulty: "easy",
    servings: 6,
    title: "Tabbouleh Salad",
    description:
      "A Levantine herb salad of fine bulgur, abundant parsley, mint, tomato, green onion, lemon, and olive oil — more green than grain.",
    tags: ["salad", "levantine", "vegan", "herbs"],
    chefTips: [
      "Chop the parsley very fine by hand; a food processor bruises it and turns the salad dark.",
      "The salad should taste lemony and herbal. Grain is only there to catch the dressing.",
    ],
    nutrition: {
      protein: 4,
      carbs: 22,
      fat: 10,
      fiber: 5,
      sugar: 3,
      sodium: 240,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Fine bulgur", amount: "80", unit: "g" },
      { name: "Flat-leaf parsley", amount: "150", unit: "g" },
      { name: "Fresh mint", amount: "30", unit: "g" },
      { name: "Ripe tomatoes", amount: "3", unit: "pcs" },
      { name: "Lemon", amount: "2", unit: "pcs" },
      { name: "Extra virgin olive oil", amount: "50", unit: "ml" },
      { name: "Green onions", amount: "4", unit: "pcs" },
      { name: "Kosher salt", amount: "0.75", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak the bulgur",
        durationMin: 12,
        text: "Rinse the fine bulgur, then cover with just-boiled water and soak until tender, about 10 minutes. Drain well and squeeze dry in a towel.",
      },
      {
        order: 2,
        title: "Chop the herbs",
        durationMin: 10,
        text: "Wash and thoroughly dry the parsley and mint. Chop very finely. Thinly slice the green onions. Dice the tomatoes small and drain off excess juice.",
      },
      {
        order: 3,
        title: "Dress the salad",
        durationMin: 5,
        text: "Toss bulgur, herbs, tomato, and green onion with lemon juice, olive oil, and salt. Taste; it should be bright and lemon-forward.",
      },
      {
        order: 4,
        title: "Rest and serve",
        durationMin: 3,
        text: "Let the tabbouleh sit 15 minutes so the bulgur drinks the dressing. Serve cool, not icy cold.",
      },
    ],
  },
  {
    slug: "greek-lemon-chicken",
    cuisineSlug: "mediterranean",
    prepTime: 75,
    calories: 490,
    difficulty: "easy",
    servings: 4,
    title: "Greek Lemon Chicken",
    description:
      "Chicken roasted with potatoes in a bath of lemon, oregano, garlic, and olive oil until the potatoes are golden and the pan juices are sharp and savory.",
    tags: ["chicken", "greek", "roast", "one-pan"],
    chefTips: [
      "Cut the potatoes so they finish with the chicken; they should sit in the lemon-oil juices.",
      "A last squeeze of lemon at the table keeps the dish tasting Greek, not just roasted.",
    ],
    nutrition: {
      protein: 38,
      carbs: 28,
      fat: 26,
      fiber: 3,
      sugar: 3,
      sodium: 680,
      saturatedFat: 6,
      cholesterol: 155,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "1", unit: "kg" },
      { name: "Lemon", amount: "3", unit: "pcs" },
      { name: "Dried oregano", amount: "2", unit: "tsp" },
      { name: "Garlic", amount: "6", unit: "cloves" },
      { name: "Yukon Gold potatoes", amount: "800", unit: "g" },
      { name: "Extra virgin olive oil", amount: "80", unit: "ml" },
      { name: "Chicken stock", amount: "120", unit: "ml" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Season the chicken",
        durationMin: 10,
        text: "Pat the thighs dry. Toss with oregano, smashed garlic, the zest of 1 lemon, half the olive oil, salt, and pepper.",
      },
      {
        order: 2,
        title: "Prep the potatoes",
        durationMin: 10,
        text: "Cut the potatoes into wedges. Toss in a roasting pan with remaining oil, juice of 2 lemons, and the stock. Nestle the chicken among them, skin side up.",
      },
      {
        order: 3,
        title: "Roast",
        durationMin: 50,
        text: "Roast at 200 C until the chicken skin is crisp and the potatoes are tender and browned at the edges, 45 to 50 minutes. Baste once with the pan juices.",
      },
      {
        order: 4,
        title: "Finish with lemon",
        durationMin: 5,
        text: "Squeeze the last lemon over the pan. Rest 5 minutes and serve with the juices spooned over the potatoes.",
      },
    ],
  },
  {
    slug: "mediterranean-stuffed-zucchini",
    cuisineSlug: "mediterranean",
    prepTime: 55,
    calories: 320,
    difficulty: "medium",
    servings: 4,
    title: "Mediterranean Stuffed Zucchini",
    description:
      "Zucchini boats filled with herbed rice, tomato, feta, and pine nuts, baked until tender and golden on top.",
    tags: ["vegetarian", "baked", "zucchini", "dinner"],
    chefTips: [
      "Scoop the zucchini leaving a sturdy wall so the boats hold the filling without collapsing.",
      "Toast the pine nuts; raw ones taste flat next to the feta.",
    ],
    nutrition: {
      protein: 12,
      carbs: 28,
      fat: 18,
      fiber: 4,
      sugar: 7,
      sodium: 560,
      saturatedFat: 6,
      cholesterol: 25,
    },
    ingredients: [
      { name: "Zucchini", amount: "4", unit: "pcs" },
      { name: "Long-grain rice", amount: "120", unit: "g" },
      { name: "Tomato", amount: "2", unit: "pcs" },
      { name: "Fresh oregano", amount: "1", unit: "tbsp" },
      { name: "Fresh mint", amount: "10", unit: "g" },
      { name: "Feta cheese", amount: "100", unit: "g" },
      { name: "Pine nuts", amount: "30", unit: "g" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Hollow the zucchini",
        durationMin: 10,
        text: "Halve the zucchini lengthwise and scoop out the centers, leaving a 1 cm wall. Chop the scooped flesh and reserve. Brush the boats with olive oil and season.",
      },
      {
        order: 2,
        title: "Cook the filling",
        durationMin: 18,
        text: "Sauté onion and garlic in olive oil. Add chopped zucchini flesh, diced tomato, rice, and a splash of water. Cook until the rice is just tender. Stir in herbs, toasted pine nuts, and most of the feta.",
      },
      {
        order: 3,
        title: "Stuff the boats",
        durationMin: 7,
        text: "Pack the filling into the zucchini boats. Crumble the remaining feta on top and drizzle with olive oil.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 20,
        text: "Bake at 190 C until the zucchini is tender and the tops are golden, 18 to 22 minutes. Rest a few minutes before serving.",
      },
    ],
  },
  {
    slug: "roasted-garlic-hummus",
    cuisineSlug: "mediterranean",
    prepTime: 40,
    calories: 180,
    difficulty: "easy",
    servings: 8,
    title: "Roasted Garlic Hummus",
    description:
      "Silky chickpea hummus blended with tahini, lemon, cumin, and a whole head of roasted garlic for a sweet, mellow bite.",
    tags: ["dip", "levantine", "vegan", "chickpeas"],
    chefTips: [
      "Peel the chickpeas if you want restaurant-smooth hummus; it is tedious and worth it.",
      "Ice water while blending lightens the texture without thinning the flavor.",
    ],
    nutrition: {
      protein: 6,
      carbs: 16,
      fat: 11,
      fiber: 4,
      sugar: 1,
      sodium: 310,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Canned chickpeas", amount: "400", unit: "g" },
      { name: "Tahini", amount: "80", unit: "g" },
      { name: "Garlic", amount: "1", unit: "head" },
      { name: "Lemon", amount: "2", unit: "pcs" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Ice water", amount: "60", unit: "ml" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Roast the garlic",
        durationMin: 30,
        text: "Slice the top off a head of garlic, drizzle with oil, wrap in foil, and roast at 200 C until soft and golden, about 30 minutes. Squeeze out the cloves.",
      },
      {
        order: 2,
        title: "Drain the chickpeas",
        durationMin: 3,
        text: "Drain and rinse the chickpeas. For a smoother dip, slip off the skins.",
      },
      {
        order: 3,
        title: "Blend the hummus",
        durationMin: 5,
        text: "Blend chickpeas, tahini, roasted garlic, lemon juice, cumin, and salt. Stream in ice water and most of the olive oil until pale and creamy.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Spoon into a bowl, swirl the remaining oil on top, and dust with a pinch of cumin. Serve with pita or vegetables.",
      },
    ],
  },
  {
    slug: "lemon-herb-couscous",
    cuisineSlug: "mediterranean",
    prepTime: 20,
    calories: 260,
    difficulty: "easy",
    servings: 4,
    title: "Lemon Herb Couscous",
    description:
      "Fluffy couscous steeped in vegetable stock, then dressed with lemon, parsley, and olive oil — a fast side for grilled fish or chicken.",
    tags: ["side", "couscous", "vegetarian", "quick"],
    chefTips: [
      "Pour boiling stock over the couscous, cover, and do not stir until it has steamed; then fluff with a fork.",
      "Add the lemon and herbs off the heat so they stay bright.",
    ],
    nutrition: {
      protein: 7,
      carbs: 42,
      fat: 8,
      fiber: 3,
      sugar: 1,
      sodium: 420,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Instant couscous", amount: "250", unit: "g" },
      { name: "Lemon", amount: "1", unit: "pcs" },
      { name: "Flat-leaf parsley", amount: "25", unit: "g" },
      { name: "Extra virgin olive oil", amount: "30", unit: "ml" },
      { name: "Vegetable stock", amount: "300", unit: "ml" },
      { name: "Fresh mint", amount: "8", unit: "g" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
      { name: "Black pepper", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Boil the stock",
        durationMin: 4,
        text: "Bring the vegetable stock to a boil. Season with a pinch of salt if it is unsalted.",
      },
      {
        order: 2,
        title: "Steam the couscous",
        durationMin: 7,
        text: "Put the couscous in a bowl, pour the boiling stock over, cover tightly, and let stand 5 to 7 minutes until the liquid is absorbed.",
      },
      {
        order: 3,
        title: "Fluff and dress",
        durationMin: 5,
        text: "Fluff with a fork. Stir in olive oil, lemon zest and juice, chopped parsley and mint, salt, and pepper.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Taste for lemon and salt. Serve warm or at room temperature alongside grilled meat, fish, or roasted vegetables.",
      },
    ],
  },
  {
    slug: "mediterranean-lentil-soup",
    cuisineSlug: "mediterranean",
    prepTime: 50,
    calories: 280,
    difficulty: "easy",
    servings: 6,
    title: "Mediterranean Lentil Soup",
    description:
      "A pot of brown lentils simmered with onion, carrot, celery, tomato, and cumin, finished with olive oil and a squeeze of lemon.",
    tags: ["soup", "lentils", "vegan", "weeknight"],
    chefTips: [
      "Do not add the lemon until the end or the lentils can stay firm.",
      "A slick of raw olive oil on each bowl is as important as the cumin.",
    ],
    nutrition: {
      protein: 15,
      carbs: 38,
      fat: 8,
      fiber: 12,
      sugar: 6,
      sodium: 540,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Brown lentils", amount: "300", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Carrot", amount: "2", unit: "pcs" },
      { name: "Celery", amount: "2", unit: "stalks" },
      { name: "Canned tomatoes", amount: "400", unit: "g" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Lemon", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Vegetable stock", amount: "1.2", unit: "l" },
    ],
    steps: [
      {
        order: 1,
        title: "Sweat the soffritto",
        durationMin: 10,
        text: "Warm olive oil and cook diced onion, carrot, and celery until soft. Add minced garlic and cumin and cook 1 minute until fragrant.",
      },
      {
        order: 2,
        title: "Add lentils and tomato",
        durationMin: 5,
        text: "Rinse the lentils and add them with the crushed tomatoes and stock. Bring to a simmer.",
      },
      {
        order: 3,
        title: "Simmer until tender",
        durationMin: 30,
        text: "Simmer gently until the lentils are tender but not mushy, 25 to 30 minutes. Add water if the soup gets too thick. Season with salt.",
      },
      {
        order: 4,
        title: "Finish with lemon",
        durationMin: 5,
        text: "Stir in lemon juice and a last drizzle of olive oil. Taste and serve with more lemon at the table.",
      },
    ],
  },
  {
    slug: "greek-yogurt-parfait",
    cuisineSlug: "mediterranean",
    prepTime: 15,
    calories: 290,
    difficulty: "easy",
    servings: 4,
    title: "Greek Yogurt Parfait",
    description:
      "Thick Greek yogurt layered with honey, toasted walnuts, and fresh berries or figs — a simple breakfast or light dessert.",
    tags: ["breakfast", "dessert", "vegetarian", "quick"],
    chefTips: [
      "Toast the walnuts so they taste buttery against the tang of the yogurt.",
      "Use a full-fat Greek yogurt; low-fat versions turn watery under the honey.",
    ],
    nutrition: {
      protein: 16,
      carbs: 28,
      fat: 13,
      fiber: 3,
      sugar: 22,
      sodium: 70,
      saturatedFat: 4,
      cholesterol: 15,
    },
    ingredients: [
      { name: "Greek yogurt", amount: "500", unit: "g" },
      { name: "Honey", amount: "60", unit: "g" },
      { name: "Walnuts", amount: "60", unit: "g" },
      { name: "Fresh figs", amount: "4", unit: "pcs" },
      { name: "Mixed berries", amount: "150", unit: "g" },
      { name: "Lemon zest", amount: "1", unit: "tsp" },
      { name: "Ground cinnamon", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Toast the walnuts",
        durationMin: 5,
        text: "Toast the walnuts in a dry pan until fragrant, then chop roughly. Let them cool so they stay crisp in the yogurt.",
      },
      {
        order: 2,
        title: "Prep the fruit",
        durationMin: 4,
        text: "Quarter the figs and rinse the berries. If the figs are not in season, use extra berries.",
      },
      {
        order: 3,
        title: "Layer the parfaits",
        durationMin: 4,
        text: "Spoon yogurt into glasses, drizzle with honey, and add fruit and walnuts. Repeat the layers.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Top with a last thread of honey, lemon zest, and a pinch of cinnamon. Serve at once so the walnuts stay crunchy.",
      },
    ],
  },
];
