import type { DemoRecipe } from "./types";

export const mexicanRecipes: DemoRecipe[] = [
  {
    slug: "beef-tacos",
    cuisineSlug: "mexican",
    prepTime: 30,
    calories: 410,
    difficulty: "easy",
    servings: 4,
    title: "Beef Tacos",
    description:
      "Cumin-and-chili-seasoned ground beef piled on warm corn tortillas with onion, cilantro, lime, and salsa.",
    tags: ["beef", "tacos", "weeknight", "street-food"],
    chefTips: [
      "Warm the corn tortillas on a dry comal until they smell toasty and stay pliable; cold tortillas crack when you fold them.",
      "Brown the beef hard before adding spices so you get caramelized bits, not gray steamed meat.",
    ],
    nutrition: {
      protein: 26,
      carbs: 28,
      fat: 22,
      fiber: 4,
      sugar: 3,
      sodium: 620,
      saturatedFat: 8,
      cholesterol: 75,
    },
    ingredients: [
      { name: "Ground beef (80/20)", amount: "500", unit: "g" },
      { name: "Corn tortillas", amount: "12", unit: "pcs" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Cilantro", amount: "30", unit: "g" },
      { name: "Limes", amount: "2", unit: "pcs" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Chili powder", amount: "2", unit: "tsp" },
      { name: "Salsa roja", amount: "120", unit: "ml" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Brown the beef",
        durationMin: 10,
        text: "Heat oil in a skillet over medium-high heat. Add the ground beef and cook, breaking it up, until well browned and the fat renders, about 8 minutes. Spoon off excess fat if needed.",
      },
      {
        order: 2,
        title: "Season",
        durationMin: 5,
        text: "Stir in minced garlic, cumin, chili powder, and 1 teaspoon salt. Cook 1 minute until fragrant. Add a splash of water and simmer until the spices cling to the meat.",
      },
      {
        order: 3,
        title: "Warm the tortillas",
        durationMin: 6,
        text: "Heat a dry comal or skillet over medium heat. Warm each corn tortilla 20 to 30 seconds per side until pliable and lightly toasted. Keep them wrapped in a cloth.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 5,
        text: "Spoon beef onto the tortillas. Top with finely diced onion, chopped cilantro, salsa, and a squeeze of lime. Serve immediately.",
      },
    ],
  },
  {
    slug: "chicken-tostadas",
    cuisineSlug: "mexican",
    prepTime: 35,
    calories: 430,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Tostadas",
    description:
      "Crisp fried corn tortillas spread with refried beans and topped with shredded chicken, lettuce, crema, cotija, and salsa.",
    tags: ["chicken", "tostadas", "crispy", "weeknight"],
    chefTips: [
      "Fry the tortillas until they are fully rigid; a pale tostada will wilt under the beans and chicken.",
      "Warm the refried beans so they spread in a thin, even layer that helps the toppings stick.",
    ],
    nutrition: {
      protein: 28,
      carbs: 32,
      fat: 20,
      fiber: 6,
      sugar: 3,
      sodium: 740,
      saturatedFat: 7,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Corn tortillas", amount: "8", unit: "pcs" },
      { name: "Cooked shredded chicken", amount: "400", unit: "g" },
      { name: "Refried beans", amount: "300", unit: "g" },
      { name: "Romaine lettuce", amount: "80", unit: "g" },
      { name: "Mexican crema", amount: "80", unit: "ml" },
      { name: "Cotija cheese", amount: "60", unit: "g" },
      { name: "Salsa verde", amount: "100", unit: "ml" },
      { name: "Neutral oil", amount: "200", unit: "ml" },
      { name: "Limes", amount: "2", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Fry the tostadas",
        durationMin: 10,
        text: "Heat 1 cm of oil in a skillet to 180 C. Fry each tortilla 30 to 45 seconds per side until rigid and gold. Drain on a rack and sprinkle with a pinch of salt.",
      },
      {
        order: 2,
        title: "Warm the toppings",
        durationMin: 6,
        text: "Heat the refried beans until spreadable. Toss the shredded chicken with a squeeze of lime and a pinch of salt.",
      },
      {
        order: 3,
        title: "Build the tostadas",
        durationMin: 6,
        text: "Spread a thin layer of beans on each tostada. Pile on chicken, shredded lettuce, salsa, a drizzle of crema, and crumbled cotija.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 3,
        text: "Squeeze lime over the top and serve at once so the tostadas stay crisp.",
      },
    ],
  },
  {
    slug: "carnitas-tacos",
    cuisineSlug: "mexican",
    prepTime: 210,
    calories: 480,
    difficulty: "medium",
    servings: 6,
    title: "Carnitas Tacos",
    description:
      "Michoacán-style pork shoulder slow-cooked with orange, onion, bay, Mexican oregano, and cumin until it shreds, then crisped and served on corn tortillas with cilantro, onion, and lime.",
    tags: ["pork", "tacos", "michoacan", "slow-cook"],
    chefTips: [
      "The pork should first braise in its own fat and orange until fork-tender, then finish uncovered so the edges caramelize.",
      "Do not skip the orange; the peel and juice give Michoacán carnitas their sweet-savory perfume.",
    ],
    nutrition: {
      protein: 32,
      carbs: 24,
      fat: 28,
      fiber: 3,
      sugar: 3,
      sodium: 580,
      saturatedFat: 10,
      cholesterol: 105,
    },
    ingredients: [
      { name: "Pork shoulder", amount: "1.5", unit: "kg" },
      { name: "Orange", amount: "1", unit: "pcs" },
      { name: "White onion", amount: "2", unit: "pcs" },
      { name: "Bay leaves", amount: "3", unit: "pcs" },
      { name: "Mexican oregano", amount: "1", unit: "tsp" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Corn tortillas", amount: "18", unit: "pcs" },
      { name: "Cilantro", amount: "40", unit: "g" },
      { name: "Limes", amount: "3", unit: "pcs" },
      { name: "Lard", amount: "60", unit: "g" },
      { name: "Kosher salt", amount: "2", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Season the pork",
        durationMin: 10,
        text: "Cut the shoulder into 6 cm chunks. Toss with salt, cumin, and Mexican oregano. Quarter one onion. Halve the orange.",
      },
      {
        order: 2,
        title: "Braise",
        durationMin: 150,
        text: "Melt the lard in a heavy pot. Add the pork, onion quarters, bay leaves, and the orange halves squeezed and dropped in. Add water to barely cover. Simmer uncovered, stirring now and then, until the water evaporates and the pork is fork-tender, about 2.5 hours.",
      },
      {
        order: 3,
        title: "Crisp the carnitas",
        durationMin: 20,
        text: "Raise the heat and let the pork fry in the remaining fat until the edges are deep gold and crisp, 15 to 20 minutes. Shred into large pieces, leaving some crispy bits intact.",
      },
      {
        order: 4,
        title: "Warm tortillas and serve",
        durationMin: 10,
        text: "Warm the corn tortillas on a comal. Dice the remaining onion. Serve the carnitas on tortillas with onion, cilantro, and lime wedges.",
      },
    ],
  },
  {
    slug: "chicken-burritos",
    cuisineSlug: "mexican",
    prepTime: 40,
    calories: 620,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Burritos",
    description:
      "Large flour tortillas wrapped around seasoned chicken, rice, beans, cheese, salsa, and sour cream.",
    tags: ["chicken", "burrito", "weeknight", "tex-mex"],
    chefTips: [
      "Warm the flour tortillas until they are fully pliable or they will tear when you roll.",
      "Keep the filling compact and slightly warm so the cheese melts and the burrito holds together.",
    ],
    nutrition: {
      protein: 36,
      carbs: 62,
      fat: 24,
      fiber: 7,
      sugar: 4,
      sodium: 980,
      saturatedFat: 10,
      cholesterol: 105,
    },
    ingredients: [
      { name: "Flour tortillas (25 cm)", amount: "4", unit: "pcs" },
      { name: "Cooked shredded chicken", amount: "450", unit: "g" },
      { name: "Cooked white rice", amount: "300", unit: "g" },
      { name: "Pinto beans, drained", amount: "250", unit: "g" },
      { name: "Shredded Monterey Jack", amount: "120", unit: "g" },
      { name: "Salsa roja", amount: "120", unit: "ml" },
      { name: "Sour cream", amount: "80", unit: "ml" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Chili powder", amount: "1", unit: "tsp" },
      { name: "Lime", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Season the chicken",
        durationMin: 8,
        text: "Warm the shredded chicken in a skillet with cumin, chili powder, a pinch of salt, and a squeeze of lime until hot and fragrant.",
      },
      {
        order: 2,
        title: "Warm the beans and rice",
        durationMin: 6,
        text: "Heat the pinto beans and the rice separately so both are steaming. Warm the tortillas on a dry skillet until soft.",
      },
      {
        order: 3,
        title: "Fill",
        durationMin: 8,
        text: "Down the center of each tortilla layer rice, beans, chicken, cheese, salsa, and sour cream. Do not overfill.",
      },
      {
        order: 4,
        title: "Roll",
        durationMin: 6,
        text: "Fold in the short sides, then roll tightly away from you into a burrito. Rest seam-side down 1 minute so the cheese helps seal it. Serve whole or halved.",
      },
    ],
  },
  {
    slug: "beef-enchiladas",
    cuisineSlug: "mexican",
    prepTime: 70,
    calories: 540,
    difficulty: "medium",
    servings: 4,
    title: "Beef Enchiladas",
    description:
      "Corn tortillas filled with shredded beef, dipped in a red enchilada sauce of toasted ancho and guajillo chilies, then baked with cheese and onion.",
    tags: ["beef", "enchiladas", "baked", "chilies"],
    chefTips: [
      "Toast the dried chilies until they smell raisiny, then soak them — raw dried chili tastes dusty and bitter.",
      "Dip each tortilla in warm sauce before filling so it stays supple and does not crack in the oven.",
    ],
    nutrition: {
      protein: 34,
      carbs: 36,
      fat: 28,
      fiber: 6,
      sugar: 5,
      sodium: 890,
      saturatedFat: 12,
      cholesterol: 110,
    },
    ingredients: [
      { name: "Corn tortillas", amount: "12", unit: "pcs" },
      { name: "Shredded cooked beef", amount: "500", unit: "g" },
      { name: "Dried ancho chilies", amount: "3", unit: "pcs" },
      { name: "Dried guajillo chilies", amount: "4", unit: "pcs" },
      { name: "Monterey Jack or Chihuahua cheese", amount: "200", unit: "g" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Chicken broth", amount: "400", unit: "ml" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the chili sauce",
        durationMin: 20,
        text: "Stem and seed the anchos and guajillos. Toast them in a dry skillet 30 seconds per side until fragrant. Soak in hot water 15 minutes. Blend with garlic, cumin, 1/4 of the onion, and broth until smooth. Strain. Simmer 10 minutes with 1 teaspoon salt.",
      },
      {
        order: 2,
        title: "Soften the tortillas",
        durationMin: 8,
        text: "Heat oil in a skillet. Briefly fry each tortilla 5 seconds per side, then dip in the warm enchilada sauce.",
      },
      {
        order: 3,
        title: "Fill and roll",
        durationMin: 12,
        text: "Spoon shredded beef and a little diced onion into each sauced tortilla. Roll and nestle seam-side down in a baking dish. Pour remaining sauce over the top and cover with shredded cheese.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 20,
        text: "Bake at 190 C until the cheese is melted and the sauce is bubbling, 15 to 18 minutes. Rest 5 minutes. Garnish with remaining onion.",
      },
    ],
  },
  {
    slug: "chimichangas",
    cuisineSlug: "mexican",
    prepTime: 40,
    calories: 580,
    difficulty: "medium",
    servings: 4,
    title: "Chimichangas",
    description:
      "Flour tortillas filled with shredded beef, beans, and cheese, rolled tight and fried until shatter-crisp, then served with salsa.",
    tags: ["beef", "fried", "burrito", "crispy"],
    chefTips: [
      "Roll the burritos tightly and rest them seam-side down so they hold when they hit the oil.",
      "Fry at 180 C; cooler oil soaks in and the shell turns greasy instead of blistered.",
    ],
    nutrition: {
      protein: 30,
      carbs: 44,
      fat: 32,
      fiber: 5,
      sugar: 3,
      sodium: 860,
      saturatedFat: 11,
      cholesterol: 90,
    },
    ingredients: [
      { name: "Flour tortillas (25 cm)", amount: "4", unit: "pcs" },
      { name: "Shredded cooked beef", amount: "400", unit: "g" },
      { name: "Refried beans", amount: "200", unit: "g" },
      { name: "Shredded Chihuahua cheese", amount: "120", unit: "g" },
      { name: "Salsa roja", amount: "120", unit: "ml" },
      { name: "White onion", amount: "0.5", unit: "pcs" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Neutral oil", amount: "500", unit: "ml" },
      { name: "Sour cream", amount: "60", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Season the filling",
        durationMin: 8,
        text: "Warm the shredded beef with cumin, diced onion, and a pinch of salt. Stir in the refried beans so the filling is cohesive, not loose.",
      },
      {
        order: 2,
        title: "Fill and roll",
        durationMin: 8,
        text: "Warm the tortillas until pliable. Spoon filling and cheese down the center, fold the sides in, and roll tightly. Rest seam-side down.",
      },
      {
        order: 3,
        title: "Fry",
        durationMin: 12,
        text: "Heat oil to 180 C. Fry the chimichangas seam-side down first, turning until all sides are deep gold and blistered, 3 to 4 minutes. Drain on a rack.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 4,
        text: "Spoon salsa over the top and add a dollop of sour cream. Serve immediately while the shell is still crisp.",
      },
    ],
  },
  {
    slug: "mexican-pozole-verde",
    cuisineSlug: "mexican",
    prepTime: 150,
    calories: 420,
    difficulty: "hard",
    servings: 6,
    title: "Mexican Pozole Verde",
    description:
      "A Guerrero-style green pozole of pork shoulder and hominy in a salsa of tomatillo, serrano, toasted pepitas, cilantro, and Mexican oregano, garnished with radish, cabbage, and lime.",
    tags: ["pork", "soup", "pozole", "hominy"],
    chefTips: [
      "Toast the pepitas until they pop; that nutty oil is what gives pozole verde body instead of a thin, watery broth.",
      "Set the garnishes out in bowls so each diner can pile on radish, cabbage, and lime at the table.",
    ],
    nutrition: {
      protein: 32,
      carbs: 28,
      fat: 20,
      fiber: 6,
      sugar: 5,
      sodium: 780,
      saturatedFat: 6,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Pork shoulder", amount: "1.2", unit: "kg" },
      { name: "Cooked white hominy", amount: "800", unit: "g" },
      { name: "Tomatillos", amount: "500", unit: "g" },
      { name: "Serrano chilies", amount: "3", unit: "pcs" },
      { name: "Raw pepitas", amount: "80", unit: "g" },
      { name: "Cilantro", amount: "40", unit: "g" },
      { name: "Mexican oregano", amount: "1", unit: "tsp" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Radishes", amount: "6", unit: "pcs" },
      { name: "Green cabbage", amount: "200", unit: "g" },
      { name: "Limes", amount: "3", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Simmer the pork",
        durationMin: 75,
        text: "Cut the shoulder into large chunks. Cover with water, half the onion, 2 garlic cloves, and 2 teaspoons salt. Simmer until the pork is tender, about 1 hour 15 minutes. Skim foam. Keep the broth.",
      },
      {
        order: 2,
        title: "Make the green salsa",
        durationMin: 20,
        text: "Husk the tomatillos. Simmer them with the serranos until they dull and soften, 8 minutes. Toast the pepitas in a dry pan until they pop. Blend tomatillos, chilies, pepitas, remaining onion and garlic, cilantro, and oregano with a ladle of pork broth until smooth.",
      },
      {
        order: 3,
        title: "Combine",
        durationMin: 25,
        text: "Pour the green salsa into the pork broth. Add the drained hominy and simmer 20 minutes so the pozole tastes of chili and pumpkin seed. Shred the pork and return it to the pot. Taste for salt.",
      },
      {
        order: 4,
        title: "Garnish",
        durationMin: 10,
        text: "Ladle into bowls. Serve with sliced radish, shredded cabbage, lime wedges, and extra oregano at the table.",
      },
    ],
  },
  {
    slug: "chicken-tortilla-soup",
    cuisineSlug: "mexican",
    prepTime: 45,
    calories: 340,
    difficulty: "easy",
    servings: 4,
    title: "Chicken Tortilla Soup",
    description:
      "A tomato-chili broth with shredded chicken, crisp tortilla strips, avocado, lime, cilantro, and cumin.",
    tags: ["chicken", "soup", "tomato", "weeknight"],
    chefTips: [
      "Fry the tortilla strips just before serving so they stay crisp when they hit the broth.",
      "A dried chile or a spoon of chipotle in adobo in the blender gives the soup a smoky backbone.",
    ],
    nutrition: {
      protein: 26,
      carbs: 22,
      fat: 16,
      fiber: 5,
      sugar: 6,
      sodium: 820,
      saturatedFat: 3,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "600", unit: "g" },
      { name: "Roma tomatoes", amount: "400", unit: "g" },
      { name: "Dried guajillo chili", amount: "1", unit: "pcs" },
      { name: "Corn tortillas", amount: "4", unit: "pcs" },
      { name: "Avocado", amount: "1", unit: "pcs" },
      { name: "Limes", amount: "2", unit: "pcs" },
      { name: "Cilantro", amount: "20", unit: "g" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Chicken broth", amount: "1", unit: "l" },
    ],
    steps: [
      {
        order: 1,
        title: "Poach the chicken",
        durationMin: 20,
        text: "Simmer the thighs in the broth with half the onion and a pinch of salt until cooked through, 18 minutes. Shred the meat and keep the broth.",
      },
      {
        order: 2,
        title: "Blend the base",
        durationMin: 10,
        text: "Toast the guajillo, then soak 5 minutes. Blend with chopped tomatoes, remaining onion, garlic, and cumin until smooth. Fry the puree in a pot 5 minutes until it darkens and thickens.",
      },
      {
        order: 3,
        title: "Simmer",
        durationMin: 8,
        text: "Pour in the reserved broth and shredded chicken. Simmer 8 minutes. Taste for salt and add a squeeze of lime.",
      },
      {
        order: 4,
        title: "Fry strips and serve",
        durationMin: 7,
        text: "Cut the tortillas into thin strips and fry in a little oil until gold. Ladle the soup into bowls and top with avocado, cilantro, lime, and the crisp strips.",
      },
    ],
  },
  {
    slug: "huevos-rancheros",
    cuisineSlug: "mexican",
    prepTime: 30,
    calories: 420,
    difficulty: "easy",
    servings: 4,
    title: "Huevos Rancheros",
    description:
      "Fried eggs on crisp-edged corn tortillas with a ranchero salsa of tomato, jalapeño, and onion, served with refried beans and cotija.",
    tags: ["eggs", "breakfast", "salsa", "vegetarian"],
    chefTips: [
      "The ranchero salsa should be cooked down until it is spoonable, not watery, so it sits on the eggs instead of flooding the plate.",
      "Fry the eggs in the same skillet as the salsa so the edges pick up chili oil.",
    ],
    nutrition: {
      protein: 20,
      carbs: 32,
      fat: 22,
      fiber: 7,
      sugar: 6,
      sodium: 680,
      saturatedFat: 7,
      cholesterol: 380,
    },
    ingredients: [
      { name: "Eggs", amount: "8", unit: "pcs" },
      { name: "Corn tortillas", amount: "8", unit: "pcs" },
      { name: "Roma tomatoes", amount: "500", unit: "g" },
      { name: "Jalapeño", amount: "2", unit: "pcs" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Refried beans", amount: "300", unit: "g" },
      { name: "Cotija cheese", amount: "60", unit: "g" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Neutral oil", amount: "4", unit: "tbsp" },
      { name: "Cilantro", amount: "15", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Make ranchero salsa",
        durationMin: 12,
        text: "Char the tomatoes, jalapeños, and half the onion on a dry comal until blistered. Blend with garlic and a pinch of salt, leaving it a little chunky. Simmer in 1 tablespoon oil 5 minutes until thick.",
      },
      {
        order: 2,
        title: "Warm beans and tortillas",
        durationMin: 8,
        text: "Heat the refried beans. Lightly fry the tortillas in oil until the edges crisp but the centers stay pliable. Keep warm.",
      },
      {
        order: 3,
        title: "Fry the eggs",
        durationMin: 6,
        text: "Fry the eggs in the remaining oil until the whites are set and the yolks are still runny, or to your liking.",
      },
      {
        order: 4,
        title: "Plate",
        durationMin: 4,
        text: "Set two tortillas on each plate, spoon on beans, top with two eggs, and smother with ranchero salsa. Finish with crumbled cotija, diced remaining onion, and cilantro.",
      },
    ],
  },
  {
    slug: "mexican-stuffed-peppers",
    cuisineSlug: "mexican",
    prepTime: 55,
    calories: 390,
    difficulty: "medium",
    servings: 4,
    title: "Mexican Stuffed Peppers",
    description:
      "Roasted poblano or bell peppers filled with cumin-spiced ground beef, rice, and tomato, baked under melted cheese.",
    tags: ["beef", "peppers", "baked", "dinner"],
    chefTips: [
      "If you use poblanos, blister and peel them first so the filling sits in a tender, smoky shell.",
      "Undercook the rice slightly; it finishes in the oven and will not turn mushy.",
    ],
    nutrition: {
      protein: 26,
      carbs: 28,
      fat: 20,
      fiber: 5,
      sugar: 7,
      sodium: 640,
      saturatedFat: 9,
      cholesterol: 80,
    },
    ingredients: [
      { name: "Poblano or bell peppers", amount: "4", unit: "pcs" },
      { name: "Ground beef", amount: "400", unit: "g" },
      { name: "Cooked white rice", amount: "200", unit: "g" },
      { name: "Roma tomatoes", amount: "2", unit: "pcs" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Shredded Oaxaca or Jack cheese", amount: "120", unit: "g" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Mexican oregano", amount: "0.5", unit: "tsp" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the peppers",
        durationMin: 12,
        text: "If using poblanos, blister over a flame, sweat in a bag, and peel. Halve any peppers lengthwise and seed them. If using bells, just halve and seed. Rub with a little oil.",
      },
      {
        order: 2,
        title: "Cook the filling",
        durationMin: 12,
        text: "Brown the beef in oil with diced onion and garlic. Stir in cumin, oregano, chopped tomatoes, and salt. Fold in the cooked rice and simmer 3 minutes.",
      },
      {
        order: 3,
        title: "Stuff",
        durationMin: 6,
        text: "Pack the filling into the pepper halves and set them in a baking dish. Cover with shredded cheese.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 20,
        text: "Bake at 190 C until the peppers are tender and the cheese is melted and spotted gold, 18 to 20 minutes. Rest 5 minutes before serving.",
      },
    ],
  },
  {
    slug: "elote-salad",
    cuisineSlug: "mexican",
    prepTime: 25,
    calories: 280,
    difficulty: "easy",
    servings: 4,
    title: "Elote Salad",
    description:
      "Charred corn kernels tossed with mayonnaise, cotija, chili powder, lime, and cilantro — street elote in a bowl, with Tajín if you like extra tang.",
    tags: ["corn", "salad", "side", "street-food"],
    chefTips: [
      "Char the corn in a dry skillet or on a grill until some kernels blacken; raw-sweet corn will not taste like elote.",
      "Toss while the corn is still warm so the mayo melts into a creamy dressing that clings.",
    ],
    nutrition: {
      protein: 8,
      carbs: 26,
      fat: 18,
      fiber: 3,
      sugar: 8,
      sodium: 420,
      saturatedFat: 5,
      cholesterol: 20,
    },
    ingredients: [
      { name: "Corn kernels (from 4 ears)", amount: "500", unit: "g" },
      { name: "Mayonnaise", amount: "60", unit: "g" },
      { name: "Cotija cheese", amount: "80", unit: "g" },
      { name: "Chili powder", amount: "1", unit: "tsp" },
      { name: "Limes", amount: "2", unit: "pcs" },
      { name: "Cilantro", amount: "20", unit: "g" },
      { name: "Tajín seasoning", amount: "1", unit: "tsp" },
      { name: "Unsalted butter", amount: "20", unit: "g" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Char the corn",
        durationMin: 10,
        text: "Melt the butter in a wide skillet over high heat. Add the corn and cook without stirring too often until many kernels are blistered and gold, 8 to 10 minutes.",
      },
      {
        order: 2,
        title: "Make the dressing",
        durationMin: 3,
        text: "Stir mayonnaise with the juice of both limes, chili powder, Tajín, and salt.",
      },
      {
        order: 3,
        title: "Toss",
        durationMin: 4,
        text: "Take the corn off the heat and fold in the dressing, crumbled cotija, and chopped cilantro while still warm.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 2,
        text: "Taste for lime and salt. Dust with a little more chili powder or Tajín and serve warm or at room temperature.",
      },
    ],
  },
  {
    slug: "refried-beans",
    cuisineSlug: "mexican",
    prepTime: 30,
    calories: 220,
    difficulty: "easy",
    servings: 6,
    title: "Refried Beans",
    description:
      "Cooked pinto beans fried in lard with onion, garlic, and cumin until thick and creamy, with a sprig of epazote if you have it.",
    tags: ["beans", "side", "vegetarian-option", "staple"],
    chefTips: [
      "Mash the beans in the hot fat, then fry them a few minutes more so they lose their raw-bean taste and turn glossy.",
      "Lard gives the classic flavor; a neutral oil works if you want them vegetarian.",
    ],
    nutrition: {
      protein: 10,
      carbs: 24,
      fat: 10,
      fiber: 8,
      sugar: 1,
      sodium: 380,
      saturatedFat: 4,
      cholesterol: 8,
    },
    ingredients: [
      { name: "Cooked pinto beans", amount: "800", unit: "g" },
      { name: "Lard or neutral oil", amount: "40", unit: "g" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Epazote sprigs", amount: "2", unit: "pcs" },
      { name: "Bean cooking liquid", amount: "150", unit: "ml" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Soften the aromatics",
        durationMin: 8,
        text: "Melt the lard in a wide skillet. Cook finely diced onion until translucent, then add minced garlic, cumin, and epazote and stir 1 minute.",
      },
      {
        order: 2,
        title: "Add the beans",
        durationMin: 5,
        text: "Add the beans and a splash of their cooking liquid. Bring to a simmer and fish out the epazote if you prefer a smoother mash.",
      },
      {
        order: 3,
        title: "Mash and fry",
        durationMin: 10,
        text: "Mash with a potato masher to the texture you like — rustic or almost smooth. Keep frying, stirring, until the beans thicken and pull away from the pan in a glossy mass.",
      },
      {
        order: 4,
        title: "Season",
        durationMin: 2,
        text: "Taste for salt. Loosen with more bean liquid if they seize. Serve hot as a side or a spread for tostadas.",
      },
    ],
  },
  {
    slug: "mexican-pinto-beans",
    cuisineSlug: "mexican",
    prepTime: 130,
    calories: 180,
    difficulty: "easy",
    servings: 8,
    title: "Mexican Pinto Beans",
    description:
      "A pot of pinto beans simmered with onion, garlic, bay, Mexican oregano, and epazote until creamy in a light, savory broth.",
    tags: ["beans", "side", "pot", "staple"],
    chefTips: [
      "Salt the beans once they start to soften, not at the very beginning, so the skins stay tender.",
      "Epazote is the classic pot herb; if you cannot find it, cumin will warm the broth in a different but still Mexican way.",
    ],
    nutrition: {
      protein: 10,
      carbs: 30,
      fat: 2,
      fiber: 10,
      sugar: 1,
      sodium: 320,
      saturatedFat: 0,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Dried pinto beans", amount: "500", unit: "g" },
      { name: "White onion", amount: "1", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Bay leaves", amount: "2", unit: "pcs" },
      { name: "Mexican oregano", amount: "1", unit: "tsp" },
      { name: "Epazote sprigs", amount: "2", unit: "pcs" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Jalapeño", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak and rinse",
        durationMin: 10,
        text: "Pick over the beans. Cover with cold water and soak 4 hours or overnight, then drain and rinse. For a same-day pot, skip the soak and add 20 minutes to the simmer.",
      },
      {
        order: 2,
        title: "Start the pot",
        durationMin: 10,
        text: "Put the beans in a pot with the halved onion, smashed garlic, bay, oregano, whole jalapeño, and epazote. Cover with water by 5 cm.",
      },
      {
        order: 3,
        title: "Simmer",
        durationMin: 90,
        text: "Bring to a boil, then simmer gently until the beans are creamy inside, 1.5 to 2 hours. Add hot water if the pot looks dry. Salt in the last 20 minutes.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 5,
        text: "Remove the bay, onion, and jalapeño if you want a cleaner broth. Taste for salt. Serve in their liquor as a side, or mash a cup of beans back into the pot to thicken it.",
      },
    ],
  },
  {
    slug: "tres-leches-cake",
    cuisineSlug: "mexican",
    prepTime: 240,
    calories: 380,
    difficulty: "medium",
    servings: 12,
    title: "Tres Leches Cake",
    description:
      "A light sponge soaked in evaporated milk, sweetened condensed milk, and heavy cream, then topped with vanilla whipped cream.",
    tags: ["dessert", "cake", "milk", "celebration"],
    chefTips: [
      "The sponge must be airy and fully cooled before you soak it, or it will collapse into a pudding.",
      "Poke the cake all over with a fork and pour the tres leches slowly so every crumb drinks; chill at least 3 hours.",
    ],
    nutrition: {
      protein: 8,
      carbs: 48,
      fat: 16,
      fiber: 0,
      sugar: 38,
      sodium: 180,
      saturatedFat: 10,
      cholesterol: 115,
    },
    ingredients: [
      { name: "All-purpose flour", amount: "150", unit: "g" },
      { name: "Eggs", amount: "5", unit: "pcs" },
      { name: "Sugar", amount: "200", unit: "g" },
      { name: "Evaporated milk", amount: "350", unit: "ml" },
      { name: "Sweetened condensed milk", amount: "300", unit: "ml" },
      { name: "Heavy cream", amount: "500", unit: "ml" },
      { name: "Vanilla extract", amount: "2", unit: "tsp" },
      { name: "Baking powder", amount: "1.5", unit: "tsp" },
      { name: "Kosher salt", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Bake the sponge",
        durationMin: 40,
        text: "Heat the oven to 175 C. Beat the eggs and 150 g sugar until very pale and thick, 6 minutes. Sift in flour, baking powder, and salt and fold gently. Pour into a buttered 23 x 33 cm pan and bake 25 to 30 minutes until a tester comes out clean. Cool in the pan.",
      },
      {
        order: 2,
        title: "Mix the three milks",
        durationMin: 5,
        text: "Whisk evaporated milk, sweetened condensed milk, 200 ml heavy cream, and 1 teaspoon vanilla.",
      },
      {
        order: 3,
        title: "Soak",
        durationMin: 10,
        text: "Poke the cooled cake all over with a fork. Pour the milk mixture slowly and evenly over the cake. Cover and refrigerate at least 3 hours, preferably overnight.",
      },
      {
        order: 4,
        title: "Whip the topping",
        durationMin: 8,
        text: "Beat remaining heavy cream with remaining sugar and vanilla to medium peaks. Spread over the soaked cake. Slice cold.",
      },
    ],
  },
  {
    slug: "mexican-flan",
    cuisineSlug: "mexican",
    prepTime: 300,
    calories: 310,
    difficulty: "medium",
    servings: 8,
    title: "Mexican Flan",
    description:
      "A silky baked custard of eggs, sweetened condensed milk, evaporated milk, and vanilla inverted onto a dark sugar caramel.",
    tags: ["dessert", "custard", "caramel", "classic"],
    chefTips: [
      "Cook the caramel to deep amber; pale caramel tastes merely sweet, and black caramel is bitter.",
      "Bake the flan in a water bath and chill overnight so it slices clean and the caramel turns to sauce.",
    ],
    nutrition: {
      protein: 9,
      carbs: 42,
      fat: 12,
      fiber: 0,
      sugar: 42,
      sodium: 140,
      saturatedFat: 7,
      cholesterol: 160,
    },
    ingredients: [
      { name: "Eggs", amount: "4", unit: "pcs" },
      { name: "Egg yolks", amount: "2", unit: "pcs" },
      { name: "Sweetened condensed milk", amount: "400", unit: "ml" },
      { name: "Evaporated milk", amount: "350", unit: "ml" },
      { name: "Vanilla extract", amount: "2", unit: "tsp" },
      { name: "Sugar", amount: "180", unit: "g" },
      { name: "Whole milk", amount: "120", unit: "ml" },
      { name: "Kosher salt", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the caramel",
        durationMin: 8,
        text: "Melt the sugar in a heavy saucepan over medium heat, swirling but not stirring, until it turns deep amber. Immediately pour into a 20 cm flan mold or loaf pan and tilt to coat the bottom. Work fast; caramel sets in seconds.",
      },
      {
        order: 2,
        title: "Blend the custard",
        durationMin: 5,
        text: "Blend eggs, yolks, sweetened condensed milk, evaporated milk, whole milk, vanilla, and salt just until smooth. Do not whip in air. Strain into the caramel-lined mold.",
      },
      {
        order: 3,
        title: "Bake in a water bath",
        durationMin: 60,
        text: "Set the mold in a larger pan. Pour hot water halfway up the sides. Bake at 160 C until the center still wobbles slightly, 50 to 60 minutes. Cool, then refrigerate at least 4 hours or overnight.",
      },
      {
        order: 4,
        title: "Unmold",
        durationMin: 5,
        text: "Run a thin knife around the edge. Invert onto a rimmed plate so the caramel sauce floods over the custard. Slice and serve cold.",
      },
    ],
  },
];
