import type { DemoRecipe } from "./types";

export const middleEasternRecipes: DemoRecipe[] = [
  {
    slug: "beef-shawarma-plate",
    cuisineSlug: "middle-eastern",
    prepTime: 50,
    calories: 560,
    difficulty: "medium",
    servings: 4,
    title: "Beef Shawarma Plate",
    description:
      "Thin-sliced flank or sirloin marinated in cumin, coriander, turmeric, paprika, garlic, and yogurt, seared and served with rice or pita, pickles, and tahini.",
    tags: ["beef", "shawarma", "grill", "dinner"],
    chefTips: [
      "Slice the beef against the grain as thin as you can, then stack and slice again so it cooks like spit shawarma.",
      "A screaming-hot skillet or grill is what gives you those dark, spice-crusted edges.",
    ],
    nutrition: {
      protein: 38,
      carbs: 42,
      fat: 24,
      fiber: 3,
      sugar: 5,
      sodium: 780,
      saturatedFat: 7,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Beef flank or sirloin", amount: "700", unit: "g" },
      { name: "Ground cumin", amount: "2", unit: "tsp" },
      { name: "Ground coriander", amount: "1.5", unit: "tsp" },
      { name: "Ground turmeric", amount: "1", unit: "tsp" },
      { name: "Paprika", amount: "2", unit: "tsp" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Plain yogurt", amount: "80", unit: "g" },
      { name: "Cooked basmati rice", amount: "480", unit: "g" },
      { name: "Pickled turnips", amount: "120", unit: "g" },
      { name: "Tahini", amount: "60", unit: "g" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate the beef",
        durationMin: 15,
        text: "Slice the beef thin against the grain. Toss with cumin, coriander, turmeric, paprika, minced garlic, yogurt, 1 tablespoon olive oil, and a pinch of salt. Rest 20 minutes, or overnight in the fridge.",
      },
      {
        order: 2,
        title: "Thin the tahini",
        durationMin: 5,
        text: "Whisk tahini with lemon juice, a pinch of salt, and cold water until it turns pale and pourable.",
      },
      {
        order: 3,
        title: "Sear the shawarma",
        durationMin: 12,
        text: "Heat a cast-iron skillet until very hot. Cook the beef in batches with the remaining oil so it browns instead of steams, 2 to 3 minutes per batch.",
      },
      {
        order: 4,
        title: "Plate",
        durationMin: 18,
        text: "Pile the beef over warm rice or inside pita. Add pickled turnips and a generous ribbon of tahini sauce.",
      },
    ],
  },
  {
    slug: "lamb-shawarma",
    cuisineSlug: "middle-eastern",
    prepTime: 55,
    calories: 580,
    difficulty: "medium",
    servings: 4,
    title: "Lamb Shawarma",
    description:
      "Lamb shoulder rubbed with baharat, cumin, allspice, cardamom, and garlic, roasted until shreddable, then tucked into pita with tahini and onion.",
    tags: ["lamb", "shawarma", "pita", "dinner"],
    chefTips: [
      "If you do not have baharat, mix equal parts cumin, allspice, and black pepper with a pinch of cardamom and cinnamon.",
      "Broil the shredded lamb for 3 minutes so the edges crisp like they would on a spit.",
    ],
    nutrition: {
      protein: 36,
      carbs: 38,
      fat: 28,
      fiber: 3,
      sugar: 4,
      sodium: 760,
      saturatedFat: 10,
      cholesterol: 120,
    },
    ingredients: [
      { name: "Lamb shoulder", amount: "800", unit: "g" },
      { name: "Baharat", amount: "2", unit: "tsp" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Ground allspice", amount: "0.5", unit: "tsp" },
      { name: "Ground cardamom", amount: "0.25", unit: "tsp" },
      { name: "Garlic", amount: "5", unit: "cloves" },
      { name: "Plain yogurt", amount: "100", unit: "g" },
      { name: "Pita bread", amount: "4", unit: "pcs" },
      { name: "Tahini", amount: "60", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Olive oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Season the lamb",
        durationMin: 12,
        text: "Cut the lamb into large chunks. Rub with baharat, cumin, allspice, cardamom, minced garlic, yogurt, olive oil, and salt. Rest at least 30 minutes.",
      },
      {
        order: 2,
        title: "Roast",
        durationMin: 30,
        text: "Roast at 200°C until the lamb is browned and tender, about 35 to 45 minutes depending on chunk size. Rest 10 minutes, then slice or shred.",
      },
      {
        order: 3,
        title: "Make the tahini",
        durationMin: 5,
        text: "Whisk tahini with lemon juice, water, and salt until smooth. Slice the onion thin and toss with a pinch of salt and lemon.",
      },
      {
        order: 4,
        title: "Stuff the pita",
        durationMin: 8,
        text: "Warm the pita. Fill with lamb, onion, and tahini. Broil the open sandwiches 2 minutes if you want crisp edges.",
      },
    ],
  },
  {
    slug: "chicken-kabsa",
    cuisineSlug: "middle-eastern",
    prepTime: 75,
    calories: 540,
    difficulty: "medium",
    servings: 6,
    title: "Chicken Kabsa",
    description:
      "A Saudi rice dish of chicken and basmati cooked with tomato, dried lime, baharat, and onion, finished with raisins and toasted almonds.",
    tags: ["chicken", "rice", "saudi", "one-pot"],
    chefTips: [
      "Pierce the dried limes (loomi) so their citrus-bitter perfume soaks into the rice; pull them out before serving if they overwhelm.",
      "Do not stir the rice once the lid is on — steam it, then fluff.",
    ],
    nutrition: {
      protein: 34,
      carbs: 52,
      fat: 18,
      fiber: 3,
      sugar: 8,
      sodium: 720,
      saturatedFat: 4,
      cholesterol: 105,
    },
    ingredients: [
      { name: "Bone-in chicken pieces", amount: "1.2", unit: "kg" },
      { name: "Basmati rice", amount: "400", unit: "g" },
      { name: "Tomatoes", amount: "3", unit: "pcs" },
      { name: "Dried limes (loomi)", amount: "2", unit: "pcs" },
      { name: "Baharat", amount: "2", unit: "tsp" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Raisins", amount: "40", unit: "g" },
      { name: "Blanched almonds", amount: "40", unit: "g" },
      { name: "Chicken stock", amount: "800", unit: "ml" },
      { name: "Tomato paste", amount: "1", unit: "tbsp" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Kosher salt", amount: "2", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Brown the chicken",
        durationMin: 15,
        text: "Season the chicken with salt and 1 teaspoon baharat. Brown in olive oil until the skin is gold. Transfer to a plate. Rinse the basmati until the water runs clear and soak it.",
      },
      {
        order: 2,
        title: "Build the sauce",
        durationMin: 12,
        text: "Cook sliced onions in the pot until soft. Add tomato paste, remaining baharat, grated tomatoes, and pierced dried limes. Return the chicken and pour in the stock. Simmer 20 minutes.",
      },
      {
        order: 3,
        title: "Steam the rice",
        durationMin: 30,
        text: "Lift out the chicken. Stir drained rice into the pot, adding a splash of stock if the liquid does not sit 1 cm above the grains. Nestle the chicken back on top, cover tightly, and cook on low until the rice is tender, about 20 minutes.",
      },
      {
        order: 4,
        title: "Garnish",
        durationMin: 18,
        text: "Rest off the heat 10 minutes. Toast almonds in a dry pan and warm the raisins in a little oil. Pile the rice on a platter, arrange the chicken, and scatter almonds and raisins.",
      },
    ],
  },
  {
    slug: "lamb-kofta-kebab",
    cuisineSlug: "middle-eastern",
    prepTime: 40,
    calories: 420,
    difficulty: "medium",
    servings: 4,
    title: "Lamb Kofta Kebab",
    description:
      "Ground lamb mixed with parsley, onion, baharat, and cumin, molded onto skewers and grilled until charred and juicy.",
    tags: ["lamb", "kebab", "grill", "dinner"],
    chefTips: [
      "Chill the shaped kofta 20 minutes so they cling to the skewers on the grill.",
      "A grated onion, squeezed dry, keeps the meat moist without making the mix sloppy.",
    ],
    nutrition: {
      protein: 28,
      carbs: 6,
      fat: 32,
      fiber: 1,
      sugar: 2,
      sodium: 640,
      saturatedFat: 13,
      cholesterol: 110,
    },
    ingredients: [
      { name: "Ground lamb", amount: "700", unit: "g" },
      { name: "Flat-leaf parsley", amount: "30", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Baharat", amount: "2", unit: "tsp" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Olive oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the kofta",
        durationMin: 12,
        text: "Grate the onion and squeeze out the liquid. Finely chop the parsley. Combine with ground lamb, baharat, cumin, minced garlic, salt, and pepper. Knead 2 minutes until sticky.",
      },
      {
        order: 2,
        title: "Shape on skewers",
        durationMin: 12,
        text: "With wet hands, mold the meat into long sausages around 8 metal or soaked wooden skewers. Press firmly so there are no air pockets.",
      },
      {
        order: 3,
        title: "Grill",
        durationMin: 12,
        text: "Brush with olive oil. Grill over high heat, turning, until charred in spots and just cooked through, 8 to 10 minutes.",
      },
      {
        order: 4,
        title: "Rest and serve",
        durationMin: 4,
        text: "Rest 3 minutes. Serve with pita, yogurt, or a chopped salad.",
      },
    ],
  },
  {
    slug: "beef-kofta-kebab",
    cuisineSlug: "middle-eastern",
    prepTime: 40,
    calories: 400,
    difficulty: "medium",
    servings: 4,
    title: "Beef Kofta Kebab",
    description:
      "Ground beef kofta seasoned with parsley, onion, allspice, cumin, and garlic, grilled on skewers until smoky.",
    tags: ["beef", "kebab", "grill", "dinner"],
    chefTips: [
      "Use meat that is about 20 percent fat — extra-lean beef dries out on the grill.",
      "Allspice is the Levantine note that makes these taste like street kofta, not hamburger.",
    ],
    nutrition: {
      protein: 30,
      carbs: 5,
      fat: 28,
      fiber: 1,
      sugar: 2,
      sodium: 620,
      saturatedFat: 10,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Ground beef", amount: "700", unit: "g" },
      { name: "Flat-leaf parsley", amount: "30", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Ground allspice", amount: "1.5", unit: "tsp" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Olive oil", amount: "1", unit: "tbsp" },
      { name: "Paprika", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the meat",
        durationMin: 12,
        text: "Grate and squeeze the onion. Chop the parsley fine. Knead into the beef with allspice, cumin, paprika, minced garlic, salt, and pepper until the mixture is tacky.",
      },
      {
        order: 2,
        title: "Form the kebabs",
        durationMin: 12,
        text: "Divide into 8 portions and press onto skewers in even cylinders. Chill 15 minutes if the kitchen is warm.",
      },
      {
        order: 3,
        title: "Grill",
        durationMin: 12,
        text: "Brush with olive oil and grill over high heat, turning often, until browned and cooked through, about 8 minutes.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 4,
        text: "Rest briefly. Serve with tahini, pickles, or warm flatbread.",
      },
    ],
  },
  {
    slug: "chicken-fatteh",
    cuisineSlug: "middle-eastern",
    prepTime: 45,
    calories: 490,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Fatteh",
    description:
      "A Levantine layered dish of shredded chicken, toasted pita, chickpeas, and a garlic yogurt-tahini sauce, finished with pine nuts and ghee.",
    tags: ["chicken", "levantine", "yogurt", "dinner"],
    chefTips: [
      "Assemble fatteh just before serving so the pita stays partly crisp under the sauce.",
      "Brown the pine nuts in ghee until they smell toasted — that hot fat over the yogurt is the whole point.",
    ],
    nutrition: {
      protein: 36,
      carbs: 34,
      fat: 22,
      fiber: 5,
      sugar: 6,
      sodium: 680,
      saturatedFat: 7,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "700", unit: "g" },
      { name: "Pita bread", amount: "3", unit: "pcs" },
      { name: "Plain yogurt", amount: "400", unit: "g" },
      { name: "Tahini", amount: "40", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Pine nuts", amount: "30", unit: "g" },
      { name: "Ghee", amount: "30", unit: "g" },
      { name: "Chickpeas", amount: "200", unit: "g" },
      { name: "Lemon juice", amount: "1", unit: "tbsp" },
      { name: "Ground cumin", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Poach the chicken",
        durationMin: 20,
        text: "Cover the chicken with salted water, add a smashed garlic clove, and simmer until tender, about 20 minutes. Shred the meat. Warm the chickpeas in a little of the broth.",
      },
      {
        order: 2,
        title: "Toast the pita",
        durationMin: 8,
        text: "Tear the pita into bite-size shards. Toast in a dry pan or 200°C oven until crisp and golden.",
      },
      {
        order: 3,
        title: "Mix the sauce",
        durationMin: 7,
        text: "Whisk yogurt with tahini, remaining minced garlic, lemon, cumin, and salt until smooth. Loosen with a spoon of chicken broth if it is too thick.",
      },
      {
        order: 4,
        title: "Layer and finish",
        durationMin: 10,
        text: "Spread pita in a shallow dish. Spoon over chickpeas and shredded chicken. Blanket with the yogurt-tahini sauce. Fry pine nuts in ghee until gold and pour the nuts and hot ghee over the top.",
      },
    ],
  },
  {
    slug: "fatteh-hummus",
    cuisineSlug: "middle-eastern",
    prepTime: 35,
    calories: 430,
    difficulty: "easy",
    servings: 4,
    title: "Fatteh Hummus",
    description:
      "Warm chickpeas and toasted pita layered with garlic yogurt-tahini, cumin, pine nuts, and a pour of olive oil or ghee.",
    tags: ["vegetarian", "chickpeas", "levantine", "appetizer"],
    chefTips: [
      "Warm the chickpeas in their liquid with a pinch of cumin so the dish is not cold in the middle.",
      "Some cooks add a spoon of the chickpea broth to the yogurt so it soaks the pita like a savory bread pudding.",
    ],
    nutrition: {
      protein: 18,
      carbs: 42,
      fat: 22,
      fiber: 9,
      sugar: 7,
      sodium: 620,
      saturatedFat: 5,
      cholesterol: 12,
    },
    ingredients: [
      { name: "Chickpeas", amount: "500", unit: "g" },
      { name: "Pita bread", amount: "3", unit: "pcs" },
      { name: "Plain yogurt", amount: "350", unit: "g" },
      { name: "Tahini", amount: "50", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Ground cumin", amount: "1", unit: "tsp" },
      { name: "Pine nuts", amount: "30", unit: "g" },
      { name: "Ghee", amount: "25", unit: "g" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Paprika", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Warm the chickpeas",
        durationMin: 10,
        text: "Heat canned or cooked chickpeas with a splash of their liquid, cumin, and a pinch of salt until steaming.",
      },
      {
        order: 2,
        title: "Toast the pita",
        durationMin: 8,
        text: "Tear pita into shards and toast until crisp. Spread them in a serving dish.",
      },
      {
        order: 3,
        title: "Make the sauce",
        durationMin: 7,
        text: "Whisk yogurt, tahini, minced garlic, lemon juice, and salt. Thin with a spoon of chickpea liquid if needed.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 10,
        text: "Spoon chickpeas over the pita, pour the yogurt-tahini on top, and fry pine nuts in ghee. Drizzle the ghee and nuts over the fatteh and dust with paprika.",
      },
    ],
  },
  {
    slug: "warak-enab-stuffed-grape-leaves",
    cuisineSlug: "middle-eastern",
    prepTime: 90,
    calories: 380,
    difficulty: "hard",
    servings: 6,
    title: "Warak Enab Stuffed Grape Leaves",
    description:
      "Grape leaves rolled around short-grain rice, lamb mince, allspice, and mint, simmered in lemon and olive oil. Often cooked over a layer of lamb chops.",
    tags: ["lamb", "rice", "levantine", "meze"],
    chefTips: [
      "Line the pot with lamb chops or spare ribs so the rolls steam over meat instead of scorching on the metal.",
      "Roll tightly but leave a little room at the ends — the rice swells as it cooks.",
    ],
    nutrition: {
      protein: 16,
      carbs: 32,
      fat: 20,
      fiber: 3,
      sugar: 2,
      sodium: 680,
      saturatedFat: 6,
      cholesterol: 40,
    },
    ingredients: [
      { name: "Grape leaves", amount: "40", unit: "pcs" },
      { name: "Short-grain rice", amount: "250", unit: "g" },
      { name: "Ground lamb", amount: "250", unit: "g" },
      { name: "Lemon juice", amount: "80", unit: "ml" },
      { name: "Olive oil", amount: "80", unit: "ml" },
      { name: "Ground allspice", amount: "1", unit: "tsp" },
      { name: "Fresh mint", amount: "15", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Lamb chops", amount: "4", unit: "pcs" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the filling",
        durationMin: 15,
        text: "Rinse the rice. Mix with ground lamb, grated onion, chopped mint, allspice, 2 tablespoons olive oil, salt, and pepper.",
      },
      {
        order: 2,
        title: "Roll the leaves",
        durationMin: 30,
        text: "Rinse brined grape leaves and pat dry. Place a leaf vein-side up, add a scant tablespoon of filling near the stem, fold the sides, and roll into a tight cigar. Repeat.",
      },
      {
        order: 3,
        title: "Layer the pot",
        durationMin: 10,
        text: "Lay lamb chops in the bottom of a heavy pot and drizzle with a little oil. Pack the rolls seam-side down in tight concentric circles. Invert a small plate on top to keep them from unfurling.",
      },
      {
        order: 4,
        title: "Braise",
        durationMin: 35,
        text: "Pour in remaining olive oil, lemon juice, and enough water to come just to the plate. Simmer gently, covered, until the rice is tender and the leaves are silky, about 45 minutes. Cool 15 minutes before lifting out.",
      },
    ],
  },
  {
    slug: "middle-eastern-tabbouleh-salad",
    cuisineSlug: "middle-eastern",
    prepTime: 30,
    calories: 220,
    difficulty: "easy",
    servings: 4,
    title: "Tabbouleh Salad",
    description:
      "A parsley-forward Levantine salad of fine bulgur, mint, tomato, lemon, and olive oil — more herb than grain.",
    tags: ["salad", "vegetarian", "meze", "levantine"],
    chefTips: [
      "Chop the parsley by hand until it is fine but not bruised into paste — a food processor turns it dark and wet.",
      "The bulgur should be a seasoning, not the bulk; if the bowl looks like a grain salad, add more parsley.",
    ],
    nutrition: {
      protein: 4,
      carbs: 18,
      fat: 16,
      fiber: 5,
      sugar: 3,
      sodium: 280,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Fine bulgur", amount: "60", unit: "g" },
      { name: "Flat-leaf parsley", amount: "150", unit: "g" },
      { name: "Fresh mint", amount: "30", unit: "g" },
      { name: "Tomatoes", amount: "3", unit: "pcs" },
      { name: "Lemon juice", amount: "60", unit: "ml" },
      { name: "Extra virgin olive oil", amount: "60", unit: "ml" },
      { name: "Green onion", amount: "3", unit: "pcs" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Black pepper", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak the bulgur",
        durationMin: 10,
        text: "Rinse fine bulgur and soak in just enough cold water to cover for 10 minutes. Drain and squeeze dry in a cloth so it is fluffy, not wet.",
      },
      {
        order: 2,
        title: "Chop the herbs",
        durationMin: 12,
        text: "Strip parsley and mint leaves and chop them very fine. Slice the green onions thin. Dice the tomatoes small and drain off excess juice.",
      },
      {
        order: 3,
        title: "Dress",
        durationMin: 5,
        text: "Toss herbs, tomato, onion, and bulgur with lemon juice, olive oil, salt, and pepper.",
      },
      {
        order: 4,
        title: "Rest",
        durationMin: 3,
        text: "Taste and add more lemon if it is not bright. Let stand 10 minutes so the bulgur finishes softening, then serve.",
      },
    ],
  },
  {
    slug: "baba-ghanoush",
    cuisineSlug: "middle-eastern",
    prepTime: 50,
    calories: 180,
    difficulty: "easy",
    servings: 4,
    title: "Baba Ghanoush",
    description:
      "Fire-roasted eggplant mashed with tahini, lemon, and garlic, finished with olive oil and optional pomegranate seeds.",
    tags: ["dip", "vegetarian", "meze", "eggplant"],
    chefTips: [
      "Char the eggplants over a flame or under a broiler until the skins blacken and the flesh collapses — that smoke is the dish.",
      "Drain the roasted flesh in a sieve so the dip stays thick instead of watery.",
    ],
    nutrition: {
      protein: 4,
      carbs: 12,
      fat: 14,
      fiber: 5,
      sugar: 6,
      sodium: 320,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Eggplants", amount: "2", unit: "pcs" },
      { name: "Tahini", amount: "50", unit: "g" },
      { name: "Lemon juice", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Pomegranate seeds", amount: "40", unit: "g" },
      { name: "Extra virgin olive oil", amount: "40", unit: "ml" },
      { name: "Ground cumin", amount: "0.5", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Flat-leaf parsley", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Char the eggplants",
        durationMin: 30,
        text: "Prick the eggplants and roast over a gas flame, on a grill, or under a hot broiler, turning, until the skins are black and the flesh is completely soft, 20 to 30 minutes.",
      },
      {
        order: 2,
        title: "Drain the flesh",
        durationMin: 10,
        text: "Cool until you can handle them. Split, scoop the flesh, and let it drain in a sieve 10 minutes. Discard the skins.",
      },
      {
        order: 3,
        title: "Mash",
        durationMin: 6,
        text: "Mash the eggplant with tahini, lemon juice, grated garlic, cumin, and salt. Do not puree to a baby-food smoothness — a little texture is right.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 4,
        text: "Spoon into a shallow bowl, swirl olive oil over the top, and scatter pomegranate seeds and parsley.",
      },
    ],
  },
  {
    slug: "ful-medames",
    cuisineSlug: "middle-eastern",
    prepTime: 25,
    calories: 320,
    difficulty: "easy",
    servings: 4,
    title: "Ful Medames",
    description:
      "An Egyptian breakfast of warm fava beans mashed with garlic, cumin, lemon, and olive oil, finished with parsley.",
    tags: ["breakfast", "vegetarian", "egyptian", "beans"],
    chefTips: [
      "Mash only some of the beans so you keep a mix of creamy and whole.",
      "A hard-boiled egg and a piece of baladi bread on the side is the Cairo plate.",
    ],
    nutrition: {
      protein: 14,
      carbs: 36,
      fat: 14,
      fiber: 10,
      sugar: 3,
      sodium: 540,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Fava beans", amount: "500", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Lemon juice", amount: "3", unit: "tbsp" },
      { name: "Extra virgin olive oil", amount: "60", unit: "ml" },
      { name: "Flat-leaf parsley", amount: "15", unit: "g" },
      { name: "Yellow onion", amount: "0.5", unit: "pcs" },
      { name: "Ground cumin for garnish", amount: "0.25", unit: "tsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Cayenne pepper", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Warm the beans",
        durationMin: 10,
        text: "Heat canned or cooked dried fava beans with a splash of their liquid until they simmer. If using dried beans, they should already be fully tender.",
      },
      {
        order: 2,
        title: "Mash with aromatics",
        durationMin: 8,
        text: "Crush garlic with salt. Stir it into the pot with cumin and cayenne. Mash about half the beans against the side of the pot.",
      },
      {
        order: 3,
        title: "Dress",
        durationMin: 4,
        text: "Off the heat, stir in lemon juice and most of the olive oil. Taste for salt and acidity.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 3,
        text: "Spoon into bowls. Top with chopped parsley, minced onion, a last drizzle of oil, and a dust of cumin.",
      },
    ],
  },
  {
    slug: "shakshuka",
    cuisineSlug: "middle-eastern",
    prepTime: 35,
    calories: 280,
    difficulty: "easy",
    servings: 4,
    title: "Shakshuka",
    description:
      "Eggs poached in a cumin-and-paprika tomato-pepper sauce with garlic, onion, and cilantro, served from the skillet.",
    tags: ["eggs", "breakfast", "vegetarian", "one-pan"],
    chefTips: [
      "Reduce the sauce until a spoon leaves a trail — watery shakshuka will not hold the egg whites.",
      "Cover the pan for the last few minutes so the whites set while the yolks stay runny.",
    ],
    nutrition: {
      protein: 14,
      carbs: 16,
      fat: 18,
      fiber: 4,
      sugar: 9,
      sodium: 520,
      saturatedFat: 4,
      cholesterol: 280,
    },
    ingredients: [
      { name: "Eggs", amount: "6", unit: "pcs" },
      { name: "Tomatoes", amount: "800", unit: "g" },
      { name: "Red bell pepper", amount: "1", unit: "pcs" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Paprika", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Cilantro", amount: "20", unit: "g" },
      { name: "Olive oil", amount: "3", unit: "tbsp" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
      { name: "Chili flakes", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the base",
        durationMin: 12,
        text: "Warm olive oil in a wide skillet. Cook sliced onion and diced pepper until soft. Add minced garlic, cumin, paprika, and chili flakes and stir 1 minute.",
      },
      {
        order: 2,
        title: "Simmer the sauce",
        durationMin: 12,
        text: "Add crushed or grated tomatoes and salt. Simmer until thick and jammy, 10 to 12 minutes. Taste for spice and salt.",
      },
      {
        order: 3,
        title: "Poach the eggs",
        durationMin: 8,
        text: "Make 6 wells and crack in the eggs. Cover and cook until the whites are just set and the yolks are still soft, 6 to 8 minutes.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 3,
        text: "Scatter chopped cilantro over the pan. Serve from the skillet with bread for scooping.",
      },
    ],
  },
  {
    slug: "mujaddara-lentil-rice",
    cuisineSlug: "middle-eastern",
    prepTime: 55,
    calories: 410,
    difficulty: "easy",
    servings: 4,
    title: "Mujaddara Lentil Rice",
    description:
      "Brown lentils and rice cooked together and crowned with a deep pile of caramelized onions, seasoned with cumin and olive oil.",
    tags: ["vegetarian", "lentils", "rice", "levantine"],
    chefTips: [
      "Take the onions further than you think — they should be mahogany and sweet, almost jammy, not pale and fried.",
      "A spoon of the onion oil stirred into the rice is what makes mujaddara taste like itself.",
    ],
    nutrition: {
      protein: 14,
      carbs: 58,
      fat: 14,
      fiber: 10,
      sugar: 6,
      sodium: 480,
      saturatedFat: 2,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Brown lentils", amount: "200", unit: "g" },
      { name: "Long-grain rice", amount: "200", unit: "g" },
      { name: "Yellow onions", amount: "3", unit: "pcs" },
      { name: "Ground cumin", amount: "1.5", unit: "tsp" },
      { name: "Olive oil", amount: "80", unit: "ml" },
      { name: "Kosher salt", amount: "1.5", unit: "tsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Ground cinnamon", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the lentils",
        durationMin: 20,
        text: "Simmer the lentils in salted water until just tender but not falling apart, 15 to 20 minutes. Drain, reserving a cup of the cooking liquid. Rinse the rice.",
      },
      {
        order: 2,
        title: "Caramelize the onions",
        durationMin: 22,
        text: "Slice the onions thin. Cook in olive oil over medium heat, stirring often, until deeply browned and sweet, 20 to 25 minutes. Season with salt. Spoon most of the onions out and leave the oil in the pot.",
      },
      {
        order: 3,
        title: "Steam the rice",
        durationMin: 10,
        text: "Toast the rice in the onion oil with cumin and cinnamon for 1 minute. Add lentils, 400 ml water or lentil liquid, salt, and pepper. Cover and cook on low until the rice is tender, about 18 minutes.",
      },
      {
        order: 4,
        title: "Pile on the onions",
        durationMin: 3,
        text: "Rest 10 minutes, fluff, and top with the reserved caramelized onions. Serve with yogurt if you like.",
      },
    ],
  },
  {
    slug: "maamoul-date-cookies",
    cuisineSlug: "middle-eastern",
    prepTime: 70,
    calories: 190,
    difficulty: "medium",
    servings: 24,
    title: "Maamoul Date Cookies",
    description:
      "Semolina shortbread cookies filled with date paste, scented with orange blossom or rose water and optional mahlab, pressed in a wooden mold.",
    tags: ["cookies", "dessert", "holiday", "baked"],
    chefTips: [
      "Rest the semolina dough a few hours so the grains swell and the cookies hold the mold pattern.",
      "If you do not have a maamoul mold, flatten stuffed balls and press a fork pattern on top.",
    ],
    nutrition: {
      protein: 3,
      carbs: 28,
      fat: 8,
      fiber: 2,
      sugar: 14,
      sodium: 40,
      saturatedFat: 5,
      cholesterol: 20,
    },
    ingredients: [
      { name: "Fine semolina", amount: "300", unit: "g" },
      { name: "Unsalted butter", amount: "180", unit: "g" },
      { name: "Date paste", amount: "300", unit: "g" },
      { name: "Orange blossom water", amount: "2", unit: "tbsp" },
      { name: "Mahlab", amount: "0.5", unit: "tsp" },
      { name: "All-purpose flour", amount: "60", unit: "g" },
      { name: "Granulated sugar", amount: "40", unit: "g" },
      { name: "Powdered sugar", amount: "20", unit: "g" },
      { name: "Whole milk", amount: "60", unit: "ml" },
    ],
    steps: [
      {
        order: 1,
        title: "Rub the dough",
        durationMin: 15,
        text: "Rub melted, cooled butter into the semolina, flour, granulated sugar, and mahlab until the mix looks like wet sand. Sprinkle in orange blossom water and milk and bring together into a soft dough. Rest 30 minutes.",
      },
      {
        order: 2,
        title: "Shape the filling",
        durationMin: 10,
        text: "Knead the date paste until pliable. Roll into 24 small logs or balls. If it is stiff, warm it with a teaspoon of oil.",
      },
      {
        order: 3,
        title: "Mold the cookies",
        durationMin: 25,
        text: "Take a walnut of dough, flatten it, wrap it around a date piece, and press into a floured maamoul mold. Tap out onto a baking sheet. Repeat.",
      },
      {
        order: 4,
        title: "Bake",
        durationMin: 20,
        text: "Bake at 180°C until the bottoms are pale gold and the tops are still fair, 15 to 18 minutes. Cool, then dust lightly with powdered sugar.",
      },
    ],
  },
  {
    slug: "basbousa-semolina-cake",
    cuisineSlug: "middle-eastern",
    prepTime: 55,
    calories: 340,
    difficulty: "easy",
    servings: 12,
    title: "Basbousa Semolina Cake",
    description:
      "A coarse semolina cake bound with yogurt and butter, soaked in a lemon-rose sugar syrup, and crowned with an almond on each square.",
    tags: ["cake", "dessert", "semolina", "syrup"],
    chefTips: [
      "Pour cold syrup over a hot cake, or hot syrup over a cooled cake — never both hot, or the crumb turns mushy.",
      "Score the batter before baking so the almonds sit centered on each piece.",
    ],
    nutrition: {
      protein: 5,
      carbs: 52,
      fat: 12,
      fiber: 1,
      sugar: 32,
      sodium: 120,
      saturatedFat: 7,
      cholesterol: 30,
    },
    ingredients: [
      { name: "Coarse semolina", amount: "300", unit: "g" },
      { name: "Granulated sugar", amount: "250", unit: "g" },
      { name: "Plain yogurt", amount: "200", unit: "g" },
      { name: "Unsalted butter", amount: "100", unit: "g" },
      { name: "Baking powder", amount: "1", unit: "tsp" },
      { name: "Lemon juice", amount: "2", unit: "tbsp" },
      { name: "Rose water", amount: "1", unit: "tbsp" },
      { name: "Blanched almonds", amount: "16", unit: "pcs" },
      { name: "Water", amount: "200", unit: "ml" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the syrup",
        durationMin: 10,
        text: "Simmer 150 g of the sugar with the water until slightly thickened, 5 minutes. Stir in lemon juice and rose water. Cool the syrup.",
      },
      {
        order: 2,
        title: "Mix the batter",
        durationMin: 10,
        text: "Stir semolina with remaining sugar, baking powder, melted butter, yogurt, and vanilla. Rest 10 minutes so the semolina hydrates.",
      },
      {
        order: 3,
        title: "Bake",
        durationMin: 30,
        text: "Spread in a greased 20 by 20 cm pan. Score into squares and press an almond into each. Bake at 180°C until gold and a tester comes out clean, 28 to 32 minutes.",
      },
      {
        order: 4,
        title: "Soak",
        durationMin: 5,
        text: "Pour the cooled syrup slowly over the hot cake. Let it absorb at least 30 minutes before cutting along the scored lines.",
      },
    ],
  },
];
