import type { DemoRecipe } from "./types";

export const thaiRecipes: DemoRecipe[] = [
  {
    slug: "thai-pineapple-chicken",
    cuisineSlug: "thai",
    prepTime: 30,
    calories: 410,
    difficulty: "easy",
    servings: 4,
    title: "Thai Pineapple Chicken",
    description:
      "A sweet-savory stir-fry of chicken, ripe pineapple, onion, and bell pepper in fish sauce, soy, and palm sugar, finished with roasted cashews.",
    tags: ["chicken", "stir-fry", "sweet-savory", "weeknight"],
    chefTips: [
      "Use ripe, tangy pineapple so the sauce does not taste flat; canned chunks work if you drain them well.",
      "Add the cashews at the end so they stay crunchy against the glossy sauce.",
    ],
    nutrition: {
      protein: 32,
      carbs: 24,
      fat: 20,
      fiber: 3,
      sugar: 16,
      sodium: 920,
      saturatedFat: 4,
      cholesterol: 110,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "500", unit: "g" },
      { name: "Fresh pineapple", amount: "300", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Red bell pepper", amount: "1", unit: "pcs" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Light soy sauce", amount: "1", unit: "tbsp" },
      { name: "Palm sugar", amount: "1", unit: "tbsp" },
      { name: "Thai red curry paste", amount: "1", unit: "tbsp" },
      { name: "Roasted cashews", amount: "50", unit: "g" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Cut the ingredients",
        durationMin: 10,
        text: "Slice the chicken into bite-size strips. Cut the pineapple into chunks, slice the onion into petals, and cut the bell pepper into squares. Stir the fish sauce, soy sauce, and palm sugar together in a small bowl.",
      },
      {
        order: 2,
        title: "Sear the chicken",
        durationMin: 6,
        text: "Heat the oil in a wok over high heat until it shimmers. Add the chicken and stir-fry until the edges brown and the meat is just cooked through, about 4 to 5 minutes. Push it to the side.",
      },
      {
        order: 3,
        title: "Stir-fry the vegetables",
        durationMin: 5,
        text: "Add the curry paste and fry 20 seconds until fragrant. Toss in the onion, bell pepper, and pineapple and stir-fry until the pepper is tender-crisp and the pineapple caramelizes at the edges.",
      },
      {
        order: 4,
        title: "Sauce and finish",
        durationMin: 4,
        text: "Pour in the sauce mixture and toss until everything is glossy. Fold in the cashews, taste for salt and sweetness, and serve immediately with jasmine rice.",
      },
    ],
  },
  {
    slug: "thai-garlic-shrimp",
    cuisineSlug: "thai",
    prepTime: 25,
    calories: 280,
    difficulty: "easy",
    servings: 4,
    title: "Thai Garlic Shrimp",
    description:
      "Goong tod kratiem: plump shrimp flash-fried with a mountain of garlic, fish sauce, oyster sauce, white pepper, and pounded cilantro root.",
    tags: ["shrimp", "garlic", "stir-fry", "quick"],
    chefTips: [
      "Pound the garlic with cilantro roots and white pepper in a mortar so the paste clings to every shrimp.",
      "Cook the shrimp just until they curl and turn opaque; another minute in the wok makes them rubbery.",
    ],
    nutrition: {
      protein: 28,
      carbs: 8,
      fat: 14,
      fiber: 1,
      sugar: 3,
      sodium: 1100,
      saturatedFat: 2,
      cholesterol: 215,
    },
    ingredients: [
      { name: "Large shrimp, peeled and deveined", amount: "500", unit: "g" },
      { name: "Garlic", amount: "12", unit: "cloves" },
      { name: "Cilantro roots or stems", amount: "4", unit: "pcs" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp" },
      { name: "Ground white pepper", amount: "1", unit: "tsp" },
      { name: "Palm sugar", amount: "1", unit: "tsp" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
      { name: "Cilantro leaves", amount: "10", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Pound the garlic paste",
        durationMin: 5,
        text: "Pound the garlic, cilantro roots, and white pepper in a mortar to a coarse paste. Pat the shrimp dry and toss them with half the paste, the fish sauce, oyster sauce, and palm sugar.",
      },
      {
        order: 2,
        title: "Fry the remaining garlic",
        durationMin: 3,
        text: "Heat the oil in a wok over medium heat. Add the rest of the garlic paste and fry until pale gold and fragrant, about 1 minute, without letting it burn.",
      },
      {
        order: 3,
        title: "Cook the shrimp",
        durationMin: 5,
        text: "Raise the heat to high, add the shrimp in a single layer, and stir-fry until they turn pink and curl, 2 to 3 minutes. Spoon the garlicky oil over them as they cook.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Taste for fish sauce. Scatter cilantro leaves over the shrimp and serve hot with jasmine rice and extra white pepper.",
      },
    ],
  },
  {
    slug: "yellow-curry-chicken",
    cuisineSlug: "thai",
    prepTime: 45,
    calories: 540,
    difficulty: "medium",
    servings: 4,
    title: "Yellow Curry Chicken",
    description:
      "Gaeng garee gai: chicken and waxy potatoes simmered in a mild yellow curry of coconut milk, turmeric-rich paste, fish sauce, and palm sugar.",
    tags: ["chicken", "curry", "coconut", "dinner"],
    chefTips: [
      "Fry the yellow curry paste in the thick coconut cream that rises to the top of the can until the oil splits; that is when the paste is cooked.",
      "Use waxy potatoes so they hold their shape in the sauce instead of collapsing.",
    ],
    nutrition: {
      protein: 34,
      carbs: 28,
      fat: 34,
      fiber: 4,
      sugar: 10,
      sodium: 980,
      saturatedFat: 24,
      cholesterol: 120,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "800", unit: "g" },
      { name: "Yellow curry paste", amount: "3", unit: "tbsp" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Waxy potatoes", amount: "400", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Palm sugar", amount: "1", unit: "tbsp" },
      { name: "Chicken stock", amount: "200", unit: "ml" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the curry",
        durationMin: 10,
        text: "Peel and cut the potatoes into large chunks. Slice the onion into wedges. Separate the thick coconut cream from the thinner milk if the can has settled.",
      },
      {
        order: 2,
        title: "Fry the paste",
        durationMin: 6,
        text: "Heat the oil and coconut cream in a pot over medium heat. Add the yellow curry paste and fry, stirring, until fragrant and the oil separates, 3 to 4 minutes.",
      },
      {
        order: 3,
        title: "Brown the chicken",
        durationMin: 8,
        text: "Add the chicken and turn it in the paste until coated and lightly browned. Pour in the remaining coconut milk and the stock. Bring to a gentle simmer.",
      },
      {
        order: 4,
        title: "Simmer with potatoes",
        durationMin: 20,
        text: "Add the potatoes, onion, fish sauce, and palm sugar. Simmer uncovered until the chicken is tender and the potatoes are cooked through, 18 to 20 minutes. Taste and adjust salt and sweetness. Serve with jasmine rice.",
      },
    ],
  },
  {
    slug: "jungle-curry",
    cuisineSlug: "thai",
    prepTime: 40,
    calories: 320,
    difficulty: "medium",
    servings: 4,
    title: "Jungle Curry",
    description:
      "Gaeng pa: a fierce, broth-based northern Thai curry with no coconut milk, built on jungle or red curry paste, stock, long beans, Thai eggplant, baby corn, holy basil, and grachai.",
    tags: ["chicken", "curry", "spicy", "no-coconut"],
    chefTips: [
      "Jungle curry should taste herbal and hot, not creamy. Keep the broth thin and do not add coconut milk.",
      "Add holy basil and makrut lime leaves only at the end so their perfume stays bright.",
    ],
    nutrition: {
      protein: 30,
      carbs: 16,
      fat: 14,
      fiber: 5,
      sugar: 6,
      sodium: 1050,
      saturatedFat: 3,
      cholesterol: 105,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "500", unit: "g" },
      { name: "Jungle curry paste or red curry paste", amount: "3", unit: "tbsp" },
      { name: "Chicken stock", amount: "500", unit: "ml" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Palm sugar", amount: "1", unit: "tsp" },
      { name: "Long beans", amount: "150", unit: "g" },
      { name: "Thai eggplants", amount: "150", unit: "g" },
      { name: "Baby corn", amount: "100", unit: "g" },
      { name: "Holy basil", amount: "20", unit: "g" },
      { name: "Makrut lime leaves", amount: "4", unit: "pcs" },
      { name: "Fresh fingerroot (grachai)", amount: "20", unit: "g" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prepare the vegetables",
        durationMin: 10,
        text: "Cut the chicken into bite-size pieces. Slice the long beans into 4 cm lengths, quarter the Thai eggplants, halve the baby corn, and julienne the grachai. Tear the makrut lime leaves in half.",
      },
      {
        order: 2,
        title: "Fry the paste",
        durationMin: 4,
        text: "Heat the oil in a pot or wok over medium heat. Fry the jungle curry paste with the grachai until the paste is fragrant and a shade darker, about 2 minutes.",
      },
      {
        order: 3,
        title: "Simmer the chicken",
        durationMin: 10,
        text: "Add the chicken and stir to coat. Pour in the stock, fish sauce, and palm sugar. Bring to a boil, then simmer until the chicken is cooked, about 8 minutes.",
      },
      {
        order: 4,
        title: "Add the vegetables",
        durationMin: 8,
        text: "Add the eggplant, long beans, and baby corn. Simmer until the eggplant is tender but still holds its shape, 6 to 8 minutes.",
      },
      {
        order: 5,
        title: "Finish with herbs",
        durationMin: 2,
        text: "Stir in the makrut lime leaves and holy basil just until wilted. Taste for heat and fish sauce. Serve in bowls with jasmine rice.",
      },
    ],
  },
  {
    slug: "thai-beef-salad",
    cuisineSlug: "thai",
    prepTime: 30,
    calories: 340,
    difficulty: "medium",
    servings: 4,
    title: "Thai Beef Salad",
    description:
      "Yam neua: grilled beef sliced thin and tossed with lime, fish sauce, toasted rice powder, chili, shallot, mint, and cilantro.",
    tags: ["beef", "salad", "grilled", "spicy"],
    chefTips: [
      "Rest the steak 5 minutes before slicing against the grain so the juices stay in the meat, not on the board.",
      "Toast raw sticky rice in a dry pan until nutty and grind it coarse; khao khua is what makes the dressing taste Thai.",
    ],
    nutrition: {
      protein: 32,
      carbs: 10,
      fat: 18,
      fiber: 2,
      sugar: 5,
      sodium: 980,
      saturatedFat: 6,
      cholesterol: 90,
    },
    ingredients: [
      { name: "Beef sirloin or flank steak", amount: "500", unit: "g" },
      { name: "Lime juice", amount: "3", unit: "tbsp" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Toasted rice powder (khao khua)", amount: "2", unit: "tbsp" },
      { name: "Thai bird chilies", amount: "3", unit: "pcs" },
      { name: "Shallots", amount: "3", unit: "pcs" },
      { name: "Fresh mint", amount: "20", unit: "g" },
      { name: "Cilantro", amount: "20", unit: "g" },
      { name: "Palm sugar", amount: "1", unit: "tsp" },
      { name: "Cucumber", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Grill the beef",
        durationMin: 10,
        text: "Season the steak lightly with salt. Grill or sear over high heat to medium-rare, about 3 to 4 minutes per side depending on thickness. Rest 5 minutes, then slice thinly against the grain.",
      },
      {
        order: 2,
        title: "Make the dressing",
        durationMin: 5,
        text: "Pound the bird chilies with the palm sugar. Stir in the lime juice and fish sauce until the sugar dissolves. Taste: it should be sour, salty, and hot.",
      },
      {
        order: 3,
        title: "Slice the aromatics",
        durationMin: 5,
        text: "Thinly slice the shallots. Cut the cucumber into half-moons. Pick the mint and cilantro leaves.",
      },
      {
        order: 4,
        title: "Toss and serve",
        durationMin: 5,
        text: "Toss the warm beef with the dressing, shallots, cucumber, herbs, and toasted rice powder. Serve immediately while the beef is still slightly warm.",
      },
    ],
  },
  {
    slug: "nam-tok-beef-salad",
    cuisineSlug: "thai",
    prepTime: 35,
    calories: 360,
    difficulty: "medium",
    servings: 4,
    title: "Nam Tok Beef Salad",
    description:
      "Isaan-style waterfall salad: grilled beef dressed with lime, fish sauce, toasted rice powder, chili powder, shallot, mint, and sawtooth coriander.",
    tags: ["beef", "salad", "isaan", "grilled"],
    chefTips: [
      "Nam tok means waterfall: the dressing should be loose enough that juices run off the beef like a waterfall.",
      "Sawtooth coriander (pak chi farang) is sharper than regular cilantro; use both if you can find it.",
    ],
    nutrition: {
      protein: 34,
      carbs: 8,
      fat: 20,
      fiber: 2,
      sugar: 3,
      sodium: 1020,
      saturatedFat: 7,
      cholesterol: 95,
    },
    ingredients: [
      { name: "Beef sirloin", amount: "500", unit: "g" },
      { name: "Toasted rice powder (khao khua)", amount: "3", unit: "tbsp" },
      { name: "Lime juice", amount: "3", unit: "tbsp" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Shallots", amount: "4", unit: "pcs" },
      { name: "Fresh mint", amount: "20", unit: "g" },
      { name: "Sawtooth coriander or cilantro", amount: "15", unit: "g" },
      { name: "Thai chili powder", amount: "1", unit: "tsp" },
      { name: "Palm sugar", amount: "0.5", unit: "tsp" },
      { name: "Green onions", amount: "2", unit: "stalks" },
    ],
    steps: [
      {
        order: 1,
        title: "Grill the steak",
        durationMin: 12,
        text: "Grill the sirloin over high heat to medium, 4 to 5 minutes per side. Rest 5 minutes so the juices settle, then slice thinly against the grain.",
      },
      {
        order: 2,
        title: "Mix the dressing",
        durationMin: 4,
        text: "Stir the lime juice, fish sauce, chili powder, and palm sugar until the sugar dissolves. The dressing should taste sour and salty first, then hot.",
      },
      {
        order: 3,
        title: "Prepare the herbs",
        durationMin: 5,
        text: "Thinly slice the shallots and green onions. Roughly chop the sawtooth coriander and pick the mint leaves.",
      },
      {
        order: 4,
        title: "Toss while warm",
        durationMin: 4,
        text: "Toss the warm sliced beef with the dressing, shallots, green onions, herbs, and toasted rice powder. The rice powder will thicken the juices slightly. Serve with sticky rice and raw vegetables.",
      },
    ],
  },
  {
    slug: "thai-chicken-wings",
    cuisineSlug: "thai",
    prepTime: 50,
    calories: 480,
    difficulty: "medium",
    servings: 4,
    title: "Thai Chicken Wings",
    description:
      "Crispy fried wings marinated in fish sauce, garlic, white pepper, palm sugar, and coriander root, in the style of Thai street-food stalls.",
    tags: ["chicken", "fried", "appetizer", "street-food"],
    chefTips: [
      "Marinate at least 2 hours so the fish sauce seasons the meat under the skin.",
      "Fry twice: once at 160 C to cook through, then at 190 C to shatter the skin.",
    ],
    nutrition: {
      protein: 28,
      carbs: 10,
      fat: 36,
      fiber: 0,
      sugar: 5,
      sodium: 890,
      saturatedFat: 8,
      cholesterol: 140,
    },
    ingredients: [
      { name: "Chicken wings", amount: "1", unit: "kg" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "6", unit: "cloves" },
      { name: "Ground white pepper", amount: "1", unit: "tsp" },
      { name: "Palm sugar", amount: "1", unit: "tbsp" },
      { name: "Coriander roots", amount: "3", unit: "pcs" },
      { name: "Rice flour", amount: "60", unit: "g" },
      { name: "Neutral oil, for frying", amount: "1", unit: "l" },
      { name: "Lime wedges", amount: "4", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the marinade",
        durationMin: 8,
        text: "Pound the garlic and coriander roots with the white pepper and palm sugar to a paste. Stir in the fish sauce. Toss the wings in the marinade, cover, and refrigerate at least 2 hours.",
      },
      {
        order: 2,
        title: "Dredge the wings",
        durationMin: 5,
        text: "Pat the wings lightly and dust them with rice flour so a thin, even coat clings. Shake off the excess.",
      },
      {
        order: 3,
        title: "First fry",
        durationMin: 12,
        text: "Heat the oil to 160 C. Fry the wings in batches until cooked through and pale gold, 8 to 10 minutes. Drain on a rack.",
      },
      {
        order: 4,
        title: "Second fry and serve",
        durationMin: 8,
        text: "Raise the oil to 190 C and fry the wings again until deep golden and crisp, 2 to 3 minutes. Drain, rest 1 minute, and serve with lime wedges.",
      },
    ],
  },
  {
    slug: "crispy-thai-fish",
    cuisineSlug: "thai",
    prepTime: 35,
    calories: 390,
    difficulty: "medium",
    servings: 4,
    title: "Crispy Thai Fish",
    description:
      "Pan-crisped fish fillets finished with a hot-sour-salty-sweet sauce of fish sauce, lime, garlic, chili, and palm sugar.",
    tags: ["fish", "fried", "spicy", "dinner"],
    chefTips: [
      "Dry the fish thoroughly and score the skin so it stays flat and crisps instead of curling.",
      "The sauce should taste like prik nam pla with extra lime and a touch of palm sugar, not a thick glaze.",
    ],
    nutrition: {
      protein: 36,
      carbs: 8,
      fat: 22,
      fiber: 1,
      sugar: 5,
      sodium: 940,
      saturatedFat: 4,
      cholesterol: 85,
    },
    ingredients: [
      { name: "White fish fillets (snapper or sea bass)", amount: "700", unit: "g" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Lime juice", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Thai bird chilies", amount: "4", unit: "pcs" },
      { name: "Palm sugar", amount: "1", unit: "tbsp" },
      { name: "Rice flour", amount: "40", unit: "g" },
      { name: "Neutral oil", amount: "80", unit: "ml" },
      { name: "Cilantro", amount: "15", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the sauce",
        durationMin: 5,
        text: "Pound the garlic and chilies. Stir in the fish sauce, lime juice, and palm sugar until the sugar dissolves. Taste for a sharp balance of sour, salty, sweet, and hot.",
      },
      {
        order: 2,
        title: "Prep the fish",
        durationMin: 5,
        text: "Pat the fillets very dry. Dust both sides with rice flour and shake off the excess.",
      },
      {
        order: 3,
        title: "Crisp the fish",
        durationMin: 12,
        text: "Heat the oil in a wide skillet over medium-high heat. Fry the fish skin-side down until the skin is shatter-crisp, 5 to 6 minutes. Flip and cook until just opaque, 3 to 4 minutes more.",
      },
      {
        order: 4,
        title: "Sauce and serve",
        durationMin: 3,
        text: "Transfer the fish to a platter. Spoon the garlic-chili-lime sauce over the top and finish with cilantro. Serve with jasmine rice.",
      },
    ],
  },
  {
    slug: "thai-coconut-soup",
    cuisineSlug: "thai",
    prepTime: 35,
    calories: 380,
    difficulty: "easy",
    servings: 4,
    title: "Thai Coconut Soup",
    description:
      "Tom kha gai: chicken simmered in coconut milk with galangal, lemongrass, makrut lime leaves, fish sauce, lime, mushrooms, and chili.",
    tags: ["soup", "chicken", "coconut", "galangal"],
    chefTips: [
      "Bruise the galangal, lemongrass, and makrut lime leaves; do not mince them. They perfume the broth and are not meant to be eaten.",
      "Add lime juice off the heat so the soup stays fragrant instead of turning dull.",
    ],
    nutrition: {
      protein: 26,
      carbs: 12,
      fat: 26,
      fiber: 2,
      sugar: 6,
      sodium: 1080,
      saturatedFat: 20,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "400", unit: "g" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Chicken stock", amount: "400", unit: "ml" },
      { name: "Galangal", amount: "40", unit: "g" },
      { name: "Lemongrass", amount: "2", unit: "stalks" },
      { name: "Makrut lime leaves", amount: "6", unit: "pcs" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Lime juice", amount: "3", unit: "tbsp" },
      { name: "Straw or oyster mushrooms", amount: "200", unit: "g" },
      { name: "Thai bird chilies", amount: "3", unit: "pcs" },
      { name: "Cilantro", amount: "15", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the aromatics",
        durationMin: 8,
        text: "Slice the galangal into coins. Smash the lemongrass and cut into 5 cm lengths. Tear the makrut lime leaves. Slice the chicken into thin strips and the mushrooms into bite-size pieces.",
      },
      {
        order: 2,
        title: "Simmer the broth",
        durationMin: 10,
        text: "Bring the coconut milk and stock to a gentle simmer with the galangal, lemongrass, and makrut lime leaves. Do not boil hard or the coconut milk will split.",
      },
      {
        order: 3,
        title: "Cook the chicken",
        durationMin: 10,
        text: "Add the chicken and mushrooms. Simmer until the chicken is just cooked, 6 to 8 minutes. Stir in the fish sauce.",
      },
      {
        order: 4,
        title: "Finish with lime",
        durationMin: 3,
        text: "Take the pot off the heat. Stir in the lime juice and bruise the chilies into the soup. Taste for sour and salt. Ladle into bowls and top with cilantro.",
      },
    ],
  },
  {
    slug: "pad-see-ew",
    cuisineSlug: "thai",
    prepTime: 25,
    calories: 560,
    difficulty: "medium",
    servings: 2,
    title: "Pad See Ew",
    description:
      "Wide sen yai rice noodles stir-fried with Chinese broccoli, egg, garlic, and chicken in a smoky mix of dark soy, light soy, and oyster sauce.",
    tags: ["noodles", "chicken", "stir-fry", "street-food"],
    chefTips: [
      "Work in a screaming-hot wok and cook one portion at a time so the noodles char instead of steam.",
      "Separate the sen yai gently with your fingers after soaking; tearing them in the wok makes them gummy.",
    ],
    nutrition: {
      protein: 32,
      carbs: 68,
      fat: 18,
      fiber: 4,
      sugar: 8,
      sodium: 1420,
      saturatedFat: 4,
      cholesterol: 195,
    },
    ingredients: [
      { name: "Fresh wide rice noodles (sen yai)", amount: "400", unit: "g" },
      { name: "Chinese broccoli (gai lan)", amount: "200", unit: "g" },
      { name: "Boneless chicken thigh", amount: "200", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Dark soy sauce", amount: "1", unit: "tbsp" },
      { name: "Light soy sauce", amount: "1", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp" },
      { name: "Palm sugar", amount: "1", unit: "tsp" },
      { name: "Neutral oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the noodles",
        durationMin: 8,
        text: "If the noodles are refrigerated, warm them briefly so they loosen. Separate into strands. Slice the chicken thin, chop the garlic, and cut the gai lan into 5 cm lengths, splitting thick stems.",
      },
      {
        order: 2,
        title: "Mix the sauce",
        durationMin: 2,
        text: "Stir the dark soy, light soy, oyster sauce, and palm sugar together.",
      },
      {
        order: 3,
        title: "Stir-fry the chicken and egg",
        durationMin: 5,
        text: "Heat the oil in a wok over high heat. Fry the garlic 10 seconds, then the chicken until just cooked. Push aside, scramble the eggs, and fold them through.",
      },
      {
        order: 4,
        title: "Noodles and gai lan",
        durationMin: 5,
        text: "Add the noodles and sauce. Toss, letting the noodles sit against the wok 20 seconds at a time so they pick up char. Add the gai lan and toss until the stems are tender-crisp. Serve immediately.",
      },
    ],
  },
  {
    slug: "pad-woon-sen",
    cuisineSlug: "thai",
    prepTime: 25,
    calories: 420,
    difficulty: "easy",
    servings: 4,
    title: "Pad Woon Sen",
    description:
      "Glass noodles stir-fried with egg, cabbage, carrot, onion, and chicken in soy, oyster sauce, and fish sauce.",
    tags: ["noodles", "glass-noodles", "stir-fry", "weeknight"],
    chefTips: [
      "Soak woon sen only until pliable, not soft; they finish cooking in the wok and will turn mushy if over-soaked.",
      "Cut the soaked noodles with scissors so they toss evenly with the vegetables.",
    ],
    nutrition: {
      protein: 22,
      carbs: 48,
      fat: 14,
      fiber: 3,
      sugar: 6,
      sodium: 1180,
      saturatedFat: 3,
      cholesterol: 140,
    },
    ingredients: [
      { name: "Dried glass noodles (woon sen)", amount: "150", unit: "g" },
      { name: "Boneless chicken thigh", amount: "250", unit: "g" },
      { name: "Eggs", amount: "2", unit: "pcs" },
      { name: "Green cabbage", amount: "150", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Light soy sauce", amount: "2", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp" },
      { name: "Fish sauce", amount: "1", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Neutral oil", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak the noodles",
        durationMin: 8,
        text: "Soak the glass noodles in room-temperature water until just pliable, 7 to 8 minutes. Drain and cut into shorter lengths. Slice the chicken, cabbage, carrot, and onion.",
      },
      {
        order: 2,
        title: "Stir-fry the protein",
        durationMin: 5,
        text: "Heat the oil in a wok over high heat. Fry the garlic, then the chicken until cooked. Push aside and scramble the eggs.",
      },
      {
        order: 3,
        title: "Add vegetables",
        durationMin: 4,
        text: "Add the onion, cabbage, and carrot. Stir-fry until the cabbage wilts but still has crunch.",
      },
      {
        order: 4,
        title: "Toss the noodles",
        durationMin: 4,
        text: "Add the drained noodles, soy sauce, oyster sauce, and fish sauce. Toss until the noodles turn glossy and have absorbed the sauce. Serve hot.",
      },
    ],
  },
  {
    slug: "thai-fish-cakes",
    cuisineSlug: "thai",
    prepTime: 35,
    calories: 310,
    difficulty: "medium",
    servings: 4,
    title: "Thai Fish Cakes",
    description:
      "Tod mun pla: bouncy white-fish cakes seasoned with red curry paste, fish sauce, egg, shredded makrut lime leaves, and sliced long beans, then fried until golden.",
    tags: ["fish", "fried", "appetizer", "curry-paste"],
    chefTips: [
      "Pound or process the fish until it is sticky and paste-like; that bounce is the hallmark of tod mun.",
      "Wet your hands when shaping so the paste does not stick, and fry in oil that is hot enough to puff the cakes.",
    ],
    nutrition: {
      protein: 26,
      carbs: 8,
      fat: 18,
      fiber: 2,
      sugar: 3,
      sodium: 860,
      saturatedFat: 4,
      cholesterol: 145,
    },
    ingredients: [
      { name: "White fish fillets", amount: "450", unit: "g" },
      { name: "Thai red curry paste", amount: "2", unit: "tbsp" },
      { name: "Egg", amount: "1", unit: "pcs" },
      { name: "Fish sauce", amount: "1", unit: "tbsp" },
      { name: "Makrut lime leaves", amount: "6", unit: "pcs" },
      { name: "Long beans", amount: "80", unit: "g" },
      { name: "Palm sugar", amount: "1", unit: "tsp" },
      { name: "Neutral oil, for frying", amount: "400", unit: "ml" },
      { name: "Cucumber relish, for serving", amount: "100", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the fish paste",
        durationMin: 10,
        text: "Pulse the fish, curry paste, egg, fish sauce, and palm sugar until a sticky, smooth paste forms. Finely shred the makrut lime leaves and thinly slice the long beans, then fold them through.",
      },
      {
        order: 2,
        title: "Shape the cakes",
        durationMin: 6,
        text: "With wet hands, shape the paste into 12 small patties about 1 cm thick.",
      },
      {
        order: 3,
        title: "Fry",
        durationMin: 10,
        text: "Heat the oil to 180 C. Fry the cakes in batches until puffed and deep golden, 3 to 4 minutes per side. Drain on a rack.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 2,
        text: "Serve hot with cucumber relish (ajad) and extra lime if you like.",
      },
    ],
  },
  {
    slug: "thai-omelette",
    cuisineSlug: "thai",
    prepTime: 15,
    calories: 420,
    difficulty: "easy",
    servings: 2,
    title: "Thai Omelette",
    description:
      "Kai jeow: a puffy, crisp-edged omelette seasoned with fish sauce and lime, optionally stuffed with ground pork, fried in plenty of oil and served with rice and prik nam pla.",
    tags: ["eggs", "quick", "street-food", "rice"],
    chefTips: [
      "The oil must be deep and very hot so the omelette inflates and the edges lace and crisp.",
      "Prik nam pla — fish sauce, chopped chili, lime, and garlic — is not optional; it is how kai jeow is eaten.",
    ],
    nutrition: {
      protein: 24,
      carbs: 4,
      fat: 34,
      fiber: 0,
      sugar: 1,
      sodium: 980,
      saturatedFat: 8,
      cholesterol: 410,
    },
    ingredients: [
      { name: "Eggs", amount: "4", unit: "pcs" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Lime juice", amount: "1", unit: "tbsp" },
      { name: "Ground pork", amount: "100", unit: "g" },
      { name: "Neutral oil", amount: "120", unit: "ml" },
      { name: "Thai bird chilies", amount: "3", unit: "pcs" },
      { name: "Garlic", amount: "1", unit: "clove" },
      { name: "Ground white pepper", amount: "0.25", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mix the omelette",
        durationMin: 3,
        text: "Beat the eggs with 1 tablespoon fish sauce, the lime juice, and white pepper until frothy. Stir in the ground pork if using, breaking it up so it is evenly distributed.",
      },
      {
        order: 2,
        title: "Make prik nam pla",
        durationMin: 2,
        text: "Chop the chilies and garlic and stir them into the remaining fish sauce with a squeeze more lime.",
      },
      {
        order: 3,
        title: "Fry the omelette",
        durationMin: 5,
        text: "Heat the oil in a wok or small pot until it shimmers and a drop of egg puffs instantly. Pour in the egg in one motion. It should balloon and crisp at the edges in 1 to 2 minutes. Flip once to set the top.",
      },
      {
        order: 4,
        title: "Drain and serve",
        durationMin: 2,
        text: "Lift the omelette onto a rack or paper to drain briefly. Serve over jasmine rice with prik nam pla spooned on top.",
      },
    ],
  },
  {
    slug: "thai-pumpkin-curry",
    cuisineSlug: "thai",
    prepTime: 35,
    calories: 360,
    difficulty: "easy",
    servings: 4,
    title: "Thai Pumpkin Curry",
    description:
      "Chunks of pumpkin simmered in red curry paste and coconut milk, seasoned with fish sauce and palm sugar, and finished with Thai basil.",
    tags: ["curry", "pumpkin", "coconut", "vegetarian-adaptable"],
    chefTips: [
      "Use kabocha or a dry-fleshed pumpkin so the pieces hold their shape and sweeten the sauce as they cook.",
      "Fry the curry paste in coconut cream until the oil splits before adding the rest of the milk.",
    ],
    nutrition: {
      protein: 6,
      carbs: 28,
      fat: 26,
      fiber: 4,
      sugar: 12,
      sodium: 920,
      saturatedFat: 20,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Kabocha or sugar pumpkin", amount: "600", unit: "g" },
      { name: "Thai red curry paste", amount: "3", unit: "tbsp" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Thai basil", amount: "20", unit: "g" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Palm sugar", amount: "1", unit: "tbsp" },
      { name: "Makrut lime leaves", amount: "3", unit: "pcs" },
      { name: "Neutral oil", amount: "1", unit: "tbsp" },
      { name: "Red spur chili", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Cut the pumpkin",
        durationMin: 8,
        text: "Peel the pumpkin if the skin is tough, scoop out the seeds, and cut the flesh into 3 cm chunks. Slice the chili on the bias.",
      },
      {
        order: 2,
        title: "Fry the paste",
        durationMin: 5,
        text: "Heat the oil and 80 ml of the thick coconut cream in a pot. Fry the red curry paste until fragrant and the oil separates, about 3 minutes.",
      },
      {
        order: 3,
        title: "Simmer the pumpkin",
        durationMin: 16,
        text: "Add the remaining coconut milk, pumpkin, fish sauce, palm sugar, and torn makrut lime leaves. Simmer gently until the pumpkin is tender but not falling apart, 12 to 15 minutes.",
      },
      {
        order: 4,
        title: "Finish with basil",
        durationMin: 2,
        text: "Stir in the Thai basil and chili. Taste for salt and sweetness. Serve with jasmine rice.",
      },
    ],
  },
  {
    slug: "thai-coconut-pancakes",
    cuisineSlug: "thai",
    prepTime: 35,
    calories: 290,
    difficulty: "medium",
    servings: 6,
    title: "Thai Coconut Pancakes",
    description:
      "Khanom khrok-style coconut pancakes: a salty-sweet rice-flour and coconut-milk batter cooked in a dimpled pan until crisp at the rim and custardy in the center, topped with shredded coconut.",
    tags: ["dessert", "coconut", "street-food", "snack"],
    chefTips: [
      "A takoyaki or aebleskiver pan stands in for a khanom khrok pan; the wells should be hot and well oiled so the edges crisp.",
      "The classic batter has two layers: a salty rice base and a sweeter coconut topping. Pour the base first, then the sweet coconut.",
    ],
    nutrition: {
      protein: 4,
      carbs: 38,
      fat: 14,
      fiber: 2,
      sugar: 16,
      sodium: 220,
      saturatedFat: 12,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Rice flour", amount: "150", unit: "g" },
      { name: "Cooked jasmine rice", amount: "80", unit: "g" },
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Granulated sugar", amount: "60", unit: "g" },
      { name: "Salt", amount: "0.75", unit: "tsp" },
      { name: "Shredded unsweetened coconut", amount: "40", unit: "g" },
      { name: "Tapioca starch", amount: "20", unit: "g" },
      { name: "Neutral oil, for the pan", amount: "2", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Blend the base batter",
        durationMin: 8,
        text: "Blend the cooked rice with 200 ml coconut milk until smooth. Whisk in the rice flour, tapioca starch, salt, and 20 g of the sugar. The batter should be pourable.",
      },
      {
        order: 2,
        title: "Make the sweet topping",
        durationMin: 3,
        text: "Stir the remaining coconut milk with the remaining sugar and the shredded coconut.",
      },
      {
        order: 3,
        title: "Heat the pan",
        durationMin: 4,
        text: "Heat a dimpled pan or small skillet over medium heat and brush each well with oil until it shimmers.",
      },
      {
        order: 4,
        title: "Cook the pancakes",
        durationMin: 16,
        text: "Pour the salty rice batter to fill each well two-thirds. Cook 1 minute, then spoon the sweet coconut topping into the center. Cover and cook until the edges are crisp and the centers are set, 3 to 4 minutes. Lift out and repeat. Serve warm.",
      },
    ],
  },
];
