import type { DemoRecipe } from "./types";

export const vietnameseRecipes: DemoRecipe[] = [
  {
    slug: "chicken-pho",
    cuisineSlug: "vietnamese",
    prepTime: 90,
    calories: 420,
    difficulty: "medium",
    servings: 4,
    title: "Chicken Pho",
    description:
      "A northern-leaning pho of whole chicken simmered with charred onion and ginger, coriander seed, and clove, served over rice noodles with cilantro, lime, and chili.",
    tags: ["soup", "chicken", "noodles", "pho"],
    chefTips: [
      "Char the onion and ginger until blackened in spots — that toast is what keeps the broth savory instead of chicken-soupy.",
      "Skim often and do not boil hard; a northern bowl is clear, lightly fish-sauced, and not sweet.",
    ],
    nutrition: {
      protein: 32,
      carbs: 48,
      fat: 10,
      fiber: 2,
      sugar: 3,
      sodium: 980,
      saturatedFat: 3,
      cholesterol: 85,
    },
    ingredients: [
      { name: "Whole chicken", amount: "1.4", unit: "kg" },
      { name: "Pho rice noodles", amount: "400", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Ginger", amount: "80", unit: "g" },
      { name: "Coriander seeds", amount: "1", unit: "tbsp" },
      { name: "Whole cloves", amount: "4", unit: "pcs" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Cilantro", amount: "20", unit: "g" },
      { name: "Limes", amount: "2", unit: "pcs" },
      { name: "Thai chili", amount: "2", unit: "pcs" },
      { name: "Kosher salt", amount: "1", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Char the aromatics",
        durationMin: 10,
        text: "Halve the onions and ginger. Char them in a dry skillet or over a flame until blackened in patches. Toast coriander seeds and cloves until fragrant.",
      },
      {
        order: 2,
        title: "Simmer the broth",
        durationMin: 50,
        text: "Cover the chicken with water, bring to a boil, and skim. Add the charred onion, ginger, and spices. Simmer gently until the chicken is cooked, about 45 minutes. Lift out the chicken, shred the meat, and return the carcass to the pot for another 20 minutes if you have time.",
      },
      {
        order: 3,
        title: "Season and soak noodles",
        durationMin: 15,
        text: "Strain the broth. Season with fish sauce and salt until it tastes savory and clean, not sweet. Soak or boil the pho noodles until just tender and drain.",
      },
      {
        order: 4,
        title: "Assemble the bowls",
        durationMin: 15,
        text: "Divide noodles and shredded chicken among bowls. Ladle boiling broth over. Serve with cilantro, lime wedges, and sliced chili.",
      },
    ],
  },
  {
    slug: "vegetarian-pho",
    cuisineSlug: "vietnamese",
    prepTime: 60,
    calories: 380,
    difficulty: "medium",
    servings: 4,
    title: "Vegetarian Pho",
    description:
      "A meatless pho built on mushroom-kombu stock with charred onion and ginger, star anise, and cinnamon, served with tofu, rice noodles, and herbs.",
    tags: ["soup", "vegetarian", "noodles", "pho"],
    chefTips: [
      "Dried shiitake and a strip of kombu give the broth body that plain vegetable stock lacks.",
      "Toast the star anise and cinnamon briefly so they perfume the pot without turning medicinal.",
    ],
    nutrition: {
      protein: 16,
      carbs: 58,
      fat: 8,
      fiber: 4,
      sugar: 5,
      sodium: 920,
      saturatedFat: 1,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Dried shiitake mushrooms", amount: "20", unit: "g" },
      { name: "Kombu", amount: "10", unit: "g" },
      { name: "Yellow onion", amount: "2", unit: "pcs" },
      { name: "Ginger", amount: "60", unit: "g" },
      { name: "Star anise", amount: "2", unit: "pcs" },
      { name: "Cinnamon stick", amount: "1", unit: "pcs" },
      { name: "Firm tofu", amount: "300", unit: "g" },
      { name: "Pho rice noodles", amount: "400", unit: "g" },
      { name: "Soy sauce", amount: "2", unit: "tbsp" },
      { name: "Thai basil", amount: "20", unit: "g" },
      { name: "Limes", amount: "2", unit: "pcs" },
      { name: "Fresh mushrooms", amount: "200", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak the stock base",
        durationMin: 10,
        text: "Cover dried shiitake and kombu with 1.8 L water and soak 20 minutes. Char halved onion and ginger in a dry pan.",
      },
      {
        order: 2,
        title: "Simmer the broth",
        durationMin: 30,
        text: "Add charred aromatics, toasted star anise, and cinnamon to the pot. Simmer 25 minutes; remove the kombu after 10 minutes so it does not turn slimy. Season with soy sauce.",
      },
      {
        order: 3,
        title: "Prep toppings",
        durationMin: 12,
        text: "Slice tofu and fresh mushrooms; sear the mushrooms until browned. Soak the rice noodles until tender. Strain the broth.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 8,
        text: "Divide noodles, tofu, and mushrooms among bowls. Ladle over boiling broth. Serve with Thai basil, lime, and chili if you like.",
      },
    ],
  },
  {
    slug: "bun-bo-nam-bo",
    cuisineSlug: "vietnamese",
    prepTime: 40,
    calories: 520,
    difficulty: "medium",
    servings: 4,
    title: "Bun Bo Nam Bo",
    description:
      "A Hanoi-style dry vermicelli bowl of stir-fried lemongrass beef over rice noodles, lettuce, cucumber, herbs, roasted peanuts, and nuoc cham.",
    tags: ["beef", "noodles", "hanoi", "bowl"],
    chefTips: [
      "This is a dry bowl — the nuoc cham is the sauce, not a soup. Dress tableside so the noodles stay springy.",
      "Slice the beef thin and cook it hot and fast with the lemongrass so it stays tender.",
    ],
    nutrition: {
      protein: 32,
      carbs: 54,
      fat: 18,
      fiber: 4,
      sugar: 10,
      sodium: 980,
      saturatedFat: 5,
      cholesterol: 75,
    },
    ingredients: [
      { name: "Rice vermicelli", amount: "350", unit: "g" },
      { name: "Beef sirloin", amount: "400", unit: "g" },
      { name: "Lemongrass", amount: "2", unit: "stalks" },
      { name: "Fish sauce", amount: "4", unit: "tbsp" },
      { name: "Roasted peanuts", amount: "50", unit: "g" },
      { name: "Lettuce", amount: "1", unit: "head" },
      { name: "Cucumber", amount: "1", unit: "pcs" },
      { name: "Lime juice", amount: "3", unit: "tbsp" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Granulated sugar", amount: "2", unit: "tbsp" },
      { name: "Thai basil", amount: "20", unit: "g" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak the noodles",
        durationMin: 10,
        text: "Soak or boil the vermicelli until just tender. Drain and rinse. Shred the lettuce and slice the cucumber. Chop herbs and crush the peanuts.",
      },
      {
        order: 2,
        title: "Mix nuoc cham",
        durationMin: 5,
        text: "Stir 3 tablespoons fish sauce with lime juice, sugar, minced garlic, and 80 ml water until the sugar dissolves.",
      },
      {
        order: 3,
        title: "Stir-fry the beef",
        durationMin: 12,
        text: "Slice the beef thin. Mince the tender inner lemongrass. Stir-fry beef with lemongrass, remaining fish sauce, and a pinch of sugar over high heat until just cooked, 3 to 4 minutes.",
      },
      {
        order: 4,
        title: "Build the bowls",
        durationMin: 13,
        text: "Layer lettuce, cucumber, herbs, and noodles. Top with hot beef and peanuts. Spoon nuoc cham over each bowl and toss at the table.",
      },
    ],
  },
  {
    slug: "bun-thit-nuong",
    cuisineSlug: "vietnamese",
    prepTime: 50,
    calories: 560,
    difficulty: "medium",
    servings: 4,
    title: "Bun Thit Nuong",
    description:
      "Lemongrass-grilled pork over rice vermicelli with herbs, pickled carrot and daikon, peanuts, scallion oil, and nuoc cham.",
    tags: ["pork", "noodles", "grill", "bowl"],
    chefTips: [
      "Marinate the pork at least 1 hour so the lemongrass and fish sauce penetrate; overnight is better.",
      "A spoon of scallion oil over the noodles is what makes a street stall bowl smell right.",
    ],
    nutrition: {
      protein: 30,
      carbs: 58,
      fat: 20,
      fiber: 4,
      sugar: 14,
      sodium: 1040,
      saturatedFat: 5,
      cholesterol: 80,
    },
    ingredients: [
      { name: "Pork shoulder", amount: "500", unit: "g" },
      { name: "Lemongrass", amount: "2", unit: "stalks" },
      { name: "Fish sauce", amount: "4", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp" },
      { name: "Honey", amount: "1", unit: "tbsp" },
      { name: "Shallots", amount: "3", unit: "pcs" },
      { name: "Rice vermicelli", amount: "350", unit: "g" },
      { name: "Roasted peanuts", amount: "40", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Daikon", amount: "150", unit: "g" },
      { name: "Scallions", amount: "3", unit: "pcs" },
      { name: "Vegetable oil", amount: "3", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate the pork",
        durationMin: 15,
        text: "Slice the pork thin. Toss with minced lemongrass, 2 tablespoons fish sauce, oyster sauce, honey, and minced shallot. Rest at least 20 minutes.",
      },
      {
        order: 2,
        title: "Pickle and prep",
        durationMin: 12,
        text: "Julienne carrot and daikon and toss with a pinch of salt, sugar, and a splash of vinegar or lime. Soak the vermicelli. Warm oil with sliced scallions until they sizzle, then take off the heat.",
      },
      {
        order: 3,
        title: "Grill the pork",
        durationMin: 12,
        text: "Grill or broil the pork until charred at the edges and just cooked through, 2 to 3 minutes per side.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 11,
        text: "Mix remaining fish sauce with lime, sugar, garlic, and water for nuoc cham. Bowl noodles with herbs, pickles, pork, peanuts, and scallion oil. Dress with nuoc cham.",
      },
    ],
  },
  {
    slug: "vietnamese-caramel-chicken",
    cuisineSlug: "vietnamese",
    prepTime: 40,
    calories: 480,
    difficulty: "medium",
    servings: 4,
    title: "Vietnamese Caramel Chicken",
    description:
      "Ga kho: bone-in chicken simmered in fish sauce and an amber sugar caramel with black pepper, shallot, and a splash of coconut water.",
    tags: ["chicken", "braise", "weeknight", "savory-sweet"],
    chefTips: [
      "Cook the sugar past blonde to a deep amber — if it stays pale the sauce tastes merely sweet, not toasty.",
      "Reduce until the sauce clings to the chicken in a shiny coat; add a splash of coconut water if it threatens to burn.",
    ],
    nutrition: {
      protein: 36,
      carbs: 16,
      fat: 28,
      fiber: 0,
      sugar: 14,
      sodium: 980,
      saturatedFat: 8,
      cholesterol: 140,
    },
    ingredients: [
      { name: "Bone-in chicken thighs", amount: "900", unit: "g" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Granulated sugar", amount: "60", unit: "g" },
      { name: "Black pepper", amount: "1", unit: "tsp" },
      { name: "Shallots", amount: "3", unit: "pcs" },
      { name: "Coconut water", amount: "120", unit: "ml" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Vegetable oil", amount: "1", unit: "tbsp" },
      { name: "Scallions", amount: "2", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the caramel",
        durationMin: 8,
        text: "Melt the sugar with 2 tablespoons water in a clay pot or heavy saucepan over medium heat. Cook without stirring until it turns amber, then take it off the heat so it does not burn.",
      },
      {
        order: 2,
        title: "Sear the chicken",
        durationMin: 10,
        text: "Season the chicken with pepper. Brown it in oil with sliced shallot and minced garlic. Tilt the pot and slide the chicken into the caramel.",
      },
      {
        order: 3,
        title: "Braise",
        durationMin: 18,
        text: "Add fish sauce and coconut water. Simmer, turning the pieces, until the chicken is cooked through and the sauce is glossy and reduced, about 20 minutes.",
      },
      {
        order: 4,
        title: "Finish",
        durationMin: 4,
        text: "Taste for salt and pepper. Scatter scallions and serve with rice to catch the sauce.",
      },
    ],
  },
  {
    slug: "lemongrass-chicken",
    cuisineSlug: "vietnamese",
    prepTime: 35,
    calories: 390,
    difficulty: "easy",
    servings: 4,
    title: "Lemongrass Chicken",
    description:
      "Chicken marinated with minced lemongrass, fish sauce, garlic, shallot, and sugar, then grilled or stir-fried until the edges caramelize.",
    tags: ["chicken", "grill", "lemongrass", "weeknight"],
    chefTips: [
      "Use only the tender inner core of the lemongrass and mince it to a paste so it does not stay woody.",
      "A hot grill or wok gives you the sweet-savory crust; crowding the pan steams the chicken pale.",
    ],
    nutrition: {
      protein: 34,
      carbs: 8,
      fat: 22,
      fiber: 0,
      sugar: 6,
      sodium: 860,
      saturatedFat: 6,
      cholesterol: 125,
    },
    ingredients: [
      { name: "Boneless chicken thighs", amount: "700", unit: "g" },
      { name: "Lemongrass", amount: "3", unit: "stalks" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "4", unit: "cloves" },
      { name: "Shallots", amount: "2", unit: "pcs" },
      { name: "Granulated sugar", amount: "1", unit: "tbsp" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
      { name: "Lime", amount: "1", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Make the marinade",
        durationMin: 10,
        text: "Mince lemongrass, garlic, and shallot to a near paste. Mix with fish sauce, sugar, pepper, and 1 tablespoon oil.",
      },
      {
        order: 2,
        title: "Marinate",
        durationMin: 5,
        text: "Cut the chicken into large pieces and toss with the marinade. Rest 20 minutes, or longer in the fridge.",
      },
      {
        order: 3,
        title: "Cook",
        durationMin: 15,
        text: "Grill over medium-high heat or stir-fry in the remaining oil until the chicken is cooked through and the lemongrass browns, 8 to 12 minutes.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 5,
        text: "Squeeze lime over the chicken. Serve with rice and a simple cucumber salad or nuoc cham.",
      },
    ],
  },
  {
    slug: "vietnamese-garlic-beef",
    cuisineSlug: "vietnamese",
    prepTime: 25,
    calories: 410,
    difficulty: "easy",
    servings: 4,
    title: "Vietnamese Garlic Beef",
    description:
      "Thin-sliced beef stir-fried with a heavy hand of garlic, fish sauce, oyster sauce, black pepper, and onion.",
    tags: ["beef", "stir-fry", "garlic", "weeknight"],
    chefTips: [
      "Slice the beef from the freezer when it is just firm — you will get restaurant-thin pieces.",
      "Add the garlic in two stages: some with the onion, and a last handful at the end so it stays fragrant, not bitter.",
    ],
    nutrition: {
      protein: 32,
      carbs: 10,
      fat: 26,
      fiber: 1,
      sugar: 4,
      sodium: 920,
      saturatedFat: 8,
      cholesterol: 90,
    },
    ingredients: [
      { name: "Beef sirloin", amount: "500", unit: "g" },
      { name: "Garlic", amount: "10", unit: "cloves" },
      { name: "Fish sauce", amount: "1.5", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1.5", unit: "tbsp" },
      { name: "Black pepper", amount: "1", unit: "tsp" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp" },
      { name: "Granulated sugar", amount: "1", unit: "tsp" },
      { name: "Scallions", amount: "2", unit: "pcs" },
    ],
    steps: [
      {
        order: 1,
        title: "Slice and season",
        durationMin: 10,
        text: "Slice the beef thin against the grain. Toss with 1 tablespoon oil, half the minced garlic, pepper, and a pinch of sugar.",
      },
      {
        order: 2,
        title: "Sear the beef",
        durationMin: 6,
        text: "Heat a wok until smoking. Stir-fry the beef in batches until just browned. Set aside.",
      },
      {
        order: 3,
        title: "Cook the aromatics",
        durationMin: 5,
        text: "Add remaining oil, sliced onion, and remaining garlic. Stir-fry until the onion softens and the garlic is gold.",
      },
      {
        order: 4,
        title: "Sauce and finish",
        durationMin: 4,
        text: "Return the beef. Add fish sauce and oyster sauce and toss 1 minute. Shower with scallions and more black pepper. Serve with rice.",
      },
    ],
  },
  {
    slug: "bo-luc-lac-shaking-beef",
    cuisineSlug: "vietnamese",
    prepTime: 30,
    calories: 470,
    difficulty: "medium",
    servings: 4,
    title: "Bo Luc Lac Shaking Beef",
    description:
      "Cubed sirloin tossed in a hot pan with soy, oyster, fish sauce, garlic, and butter, served over watercress and tomato with a lime-pepper-salt dip.",
    tags: ["beef", "stir-fry", "saigon", "dinner"],
    chefTips: [
      "The shake is literal — keep the cubes moving so they brown on all sides without steaming.",
      "The lime-pepper-salt dip (muoi tieu chanh) is not optional; it cuts the butter and soy.",
    ],
    nutrition: {
      protein: 36,
      carbs: 8,
      fat: 32,
      fiber: 1,
      sugar: 3,
      sodium: 890,
      saturatedFat: 12,
      cholesterol: 120,
    },
    ingredients: [
      { name: "Beef sirloin", amount: "600", unit: "g" },
      { name: "Soy sauce", amount: "1.5", unit: "tbsp" },
      { name: "Oyster sauce", amount: "1", unit: "tbsp" },
      { name: "Fish sauce", amount: "1", unit: "tsp" },
      { name: "Garlic", amount: "5", unit: "cloves" },
      { name: "Unsalted butter", amount: "30", unit: "g" },
      { name: "Watercress", amount: "100", unit: "g" },
      { name: "Tomatoes", amount: "2", unit: "pcs" },
      { name: "Lime", amount: "1", unit: "pcs" },
      { name: "Kosher salt", amount: "0.5", unit: "tsp" },
      { name: "Black pepper", amount: "1", unit: "tsp" },
      { name: "Vegetable oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Marinate the cubes",
        durationMin: 10,
        text: "Cut the sirloin into 2.5 cm cubes. Toss with soy sauce, oyster sauce, fish sauce, half the minced garlic, and 0.5 teaspoon pepper. Rest 15 minutes.",
      },
      {
        order: 2,
        title: "Prep the platter",
        durationMin: 6,
        text: "Arrange watercress and sliced tomato on a platter. Mix remaining salt and pepper on a small saucer with lime juice for dipping.",
      },
      {
        order: 3,
        title: "Shake the beef",
        durationMin: 8,
        text: "Heat oil in a wok until smoking. Add the beef in one layer and let it sear, then shake and toss until browned on most sides but still pink inside, about 3 minutes. Add remaining garlic and the butter and toss until the butter foams.",
      },
      {
        order: 4,
        title: "Serve",
        durationMin: 6,
        text: "Tip the beef and butter juices over the watercress. Serve immediately with the lime-pepper-salt dip.",
      },
    ],
  },
  {
    slug: "vietnamese-fried-rice",
    cuisineSlug: "vietnamese",
    prepTime: 25,
    calories: 480,
    difficulty: "easy",
    servings: 4,
    title: "Vietnamese Fried Rice",
    description:
      "Day-old rice wok-fried with egg, Chinese sausage or shrimp, fish sauce, scallion, garlic, and peas.",
    tags: ["rice", "fried-rice", "weeknight", "quick"],
    chefTips: [
      "Cold, dry leftover rice is essential — fresh rice turns gluey in the wok.",
      "Season with fish sauce, not soy, if you want it to taste Vietnamese rather than Chinese-American.",
    ],
    nutrition: {
      protein: 18,
      carbs: 58,
      fat: 18,
      fiber: 3,
      sugar: 3,
      sodium: 820,
      saturatedFat: 5,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Day-old cooked rice", amount: "600", unit: "g" },
      { name: "Eggs", amount: "3", unit: "pcs" },
      { name: "Chinese sausage", amount: "120", unit: "g" },
      { name: "Fish sauce", amount: "1.5", unit: "tbsp" },
      { name: "Scallions", amount: "4", unit: "pcs" },
      { name: "Garlic", amount: "3", unit: "cloves" },
      { name: "Frozen peas", amount: "100", unit: "g" },
      { name: "Vegetable oil", amount: "3", unit: "tbsp" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Prep the mix-ins",
        durationMin: 8,
        text: "Break up the cold rice with wet fingers. Slice the Chinese sausage. Beat the eggs. Mince garlic and slice scallions, whites and greens separated.",
      },
      {
        order: 2,
        title: "Scramble and sear",
        durationMin: 6,
        text: "Heat a wok with 1 tablespoon oil. Scramble the eggs until just set and tip them out. Add sausage and cook until the edges crisp.",
      },
      {
        order: 3,
        title: "Fry the rice",
        durationMin: 7,
        text: "Add remaining oil, garlic, and scallion whites. Add the rice and stir-fry, pressing out clumps, until hot and lightly toasted.",
      },
      {
        order: 4,
        title: "Season",
        durationMin: 4,
        text: "Add peas, eggs, fish sauce, and pepper. Toss until the peas are hot. Finish with scallion greens.",
      },
    ],
  },
  {
    slug: "mi-quang-noodles",
    cuisineSlug: "vietnamese",
    prepTime: 50,
    calories: 540,
    difficulty: "medium",
    servings: 4,
    title: "Mi Quang Noodles",
    description:
      "Central Vietnamese turmeric rice noodles with pork, shrimp, a modest savory broth, peanuts, herbs, and crisp rice crackers.",
    tags: ["noodles", "pork", "shrimp", "central-vietnam"],
    chefTips: [
      "Mi quang is not a deep soup — you want just enough broth to moisten the noodles, about a ladle per bowl.",
      "Turmeric-tinted noodles are traditional; if you only have white rice noodles, bloom 0.5 teaspoon turmeric in the broth.",
    ],
    nutrition: {
      protein: 30,
      carbs: 62,
      fat: 16,
      fiber: 3,
      sugar: 4,
      sodium: 1020,
      saturatedFat: 4,
      cholesterol: 145,
    },
    ingredients: [
      { name: "Turmeric rice noodles", amount: "400", unit: "g" },
      { name: "Pork shoulder", amount: "250", unit: "g" },
      { name: "Shrimp", amount: "200", unit: "g" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Shallots", amount: "3", unit: "pcs" },
      { name: "Roasted peanuts", amount: "40", unit: "g" },
      { name: "Rice crackers (banh trang)", amount: "4", unit: "pcs" },
      { name: "Pork or chicken stock", amount: "600", unit: "ml" },
      { name: "Ground turmeric", amount: "0.5", unit: "tsp" },
      { name: "Mint", amount: "20", unit: "g" },
      { name: "Vegetable oil", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
    ],
    steps: [
      {
        order: 1,
        title: "Cook the pork",
        durationMin: 18,
        text: "Slice the pork thin. Brown it in oil with sliced shallot, garlic, and turmeric. Add stock and 2 tablespoons fish sauce. Simmer 15 minutes. Add shrimp for the last 3 minutes.",
      },
      {
        order: 2,
        title: "Cook the noodles",
        durationMin: 10,
        text: "Boil the turmeric noodles until chewy-tender. Drain well — they should not sit in water.",
      },
      {
        order: 3,
        title: "Prep garnishes",
        durationMin: 8,
        text: "Crush the peanuts. Warm or briefly grill the rice crackers so they blister. Pick the mint.",
      },
      {
        order: 4,
        title: "Assemble the bowls",
        durationMin: 14,
        text: "Divide noodles among shallow bowls. Top with pork and shrimp. Ladle on a modest amount of broth. Finish with peanuts, herbs, a drizzle of remaining fish sauce, and a rice cracker on the side.",
      },
    ],
  },
  {
    slug: "hu-tieu-noodle-soup",
    cuisineSlug: "vietnamese",
    prepTime: 70,
    calories: 490,
    difficulty: "medium",
    servings: 4,
    title: "Hu Tieu Noodle Soup",
    description:
      "A Saigon-style hu tieu of pork-and-seafood broth with hu tieu noodles, shrimp, sliced pork, fried shallot, celery, and herbs.",
    tags: ["soup", "noodles", "pork", "saigon"],
    chefTips: [
      "Saigon hu tieu can be eaten dry or wet — serve extra broth on the side if your table cannot agree.",
      "A handful of Chinese celery (or regular celery leaves) is the herb that makes this taste like a Cho Lon stall, not pho.",
    ],
    nutrition: {
      protein: 32,
      carbs: 56,
      fat: 14,
      fiber: 2,
      sugar: 3,
      sodium: 1100,
      saturatedFat: 4,
      cholesterol: 130,
    },
    ingredients: [
      { name: "Hu tieu noodles", amount: "400", unit: "g" },
      { name: "Pork bones", amount: "600", unit: "g" },
      { name: "Shrimp", amount: "200", unit: "g" },
      { name: "Pork loin", amount: "200", unit: "g" },
      { name: "Fried shallots", amount: "20", unit: "g" },
      { name: "Celery", amount: "2", unit: "stalks" },
      { name: "Fish sauce", amount: "3", unit: "tbsp" },
      { name: "Dried shrimp", amount: "15", unit: "g" },
      { name: "Yellow onion", amount: "1", unit: "pcs" },
      { name: "Cilantro", amount: "15", unit: "g" },
      { name: "Garlic", amount: "3", unit: "cloves" },
    ],
    steps: [
      {
        order: 1,
        title: "Build the broth",
        durationMin: 40,
        text: "Blanch the pork bones, then simmer them with onion, dried shrimp, and smashed garlic for 45 minutes. Add the pork loin for the last 15 minutes, then slice it thin. Season the strained broth with fish sauce.",
      },
      {
        order: 2,
        title: "Cook shrimp and noodles",
        durationMin: 12,
        text: "Poach the shrimp in the broth until just pink. Cook the hu tieu noodles until tender and rinse.",
      },
      {
        order: 3,
        title: "Prep garnishes",
        durationMin: 8,
        text: "Slice celery on a bias. Warm the fried shallots. Chop cilantro.",
      },
      {
        order: 4,
        title: "Assemble",
        durationMin: 10,
        text: "Divide noodles among bowls. Top with pork, shrimp, celery, and herbs. Ladle over boiling broth and finish with fried shallots.",
      },
    ],
  },
  {
    slug: "vietnamese-egg-rolls",
    cuisineSlug: "vietnamese",
    prepTime: 55,
    calories: 360,
    difficulty: "medium",
    servings: 6,
    title: "Vietnamese Egg Rolls",
    description:
      "Cha gio: crisp fried rolls of ground pork, wood ear, glass noodles, and carrot, wrapped in rice paper, served with nuoc cham.",
    tags: ["pork", "fried", "appetizer", "party"],
    chefTips: [
      "Dip rice paper in warm water for only a second — it will soften as you roll. Too wet and the rolls burst in the oil.",
      "Fry at 170°C so the filling cooks through before the wrapper darkens.",
    ],
    nutrition: {
      protein: 16,
      carbs: 28,
      fat: 20,
      fiber: 2,
      sugar: 4,
      sodium: 720,
      saturatedFat: 5,
      cholesterol: 70,
    },
    ingredients: [
      { name: "Ground pork", amount: "300", unit: "g" },
      { name: "Dried wood ear mushrooms", amount: "15", unit: "g" },
      { name: "Glass noodles", amount: "40", unit: "g" },
      { name: "Carrot", amount: "1", unit: "pcs" },
      { name: "Shrimp", amount: "100", unit: "g" },
      { name: "Rice paper", amount: "16", unit: "pcs" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Shallot", amount: "1", unit: "pcs" },
      { name: "Vegetable oil", amount: "1", unit: "L" },
      { name: "Black pepper", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Soak and chop",
        durationMin: 15,
        text: "Soak wood ear and glass noodles in warm water until soft. Drain well and chop. Mince shrimp, grate the carrot, and mince garlic and shallot.",
      },
      {
        order: 2,
        title: "Mix the filling",
        durationMin: 8,
        text: "Combine pork, shrimp, wood ear, noodles, carrot, garlic, shallot, 1 tablespoon fish sauce, and pepper. Mix until sticky.",
      },
      {
        order: 3,
        title: "Roll",
        durationMin: 18,
        text: "Dip a rice paper briefly in warm water. Add 2 tablespoons filling, fold the sides, and roll tight. Repeat. Mix remaining fish sauce with lime, sugar, water, and chili for nuoc cham.",
      },
      {
        order: 4,
        title: "Fry",
        durationMin: 14,
        text: "Fry the rolls in 170°C oil, turning, until blistered and deep gold, 6 to 8 minutes. Drain and serve hot with nuoc cham and lettuce for wrapping.",
      },
    ],
  },
  {
    slug: "vietnamese-green-papaya-salad",
    cuisineSlug: "vietnamese",
    prepTime: 25,
    calories: 210,
    difficulty: "easy",
    servings: 4,
    title: "Vietnamese Green Papaya Salad",
    description:
      "Shredded green papaya tossed with lime, fish sauce, chili, garlic, roasted peanuts, and herbs, with optional dried shrimp.",
    tags: ["salad", "papaya", "appetizer", "fresh"],
    chefTips: [
      "Salt and squeeze the papaya shreds so they stay crunchy and take the dressing.",
      "Dried shrimp or shredded beef jerky is the classic protein; skip them for a lighter bowl.",
    ],
    nutrition: {
      protein: 8,
      carbs: 22,
      fat: 10,
      fiber: 4,
      sugar: 12,
      sodium: 780,
      saturatedFat: 1.5,
      cholesterol: 25,
    },
    ingredients: [
      { name: "Green papaya", amount: "500", unit: "g" },
      { name: "Dried shrimp", amount: "30", unit: "g" },
      { name: "Roasted peanuts", amount: "40", unit: "g" },
      { name: "Lime juice", amount: "3", unit: "tbsp" },
      { name: "Fish sauce", amount: "2", unit: "tbsp" },
      { name: "Thai chili", amount: "2", unit: "pcs" },
      { name: "Garlic", amount: "2", unit: "cloves" },
      { name: "Thai basil", amount: "15", unit: "g" },
      { name: "Granulated sugar", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Shred the papaya",
        durationMin: 10,
        text: "Peel the green papaya, seed it, and julienne into fine shreds. Toss with a pinch of salt, rest 5 minutes, then squeeze dry.",
      },
      {
        order: 2,
        title: "Soften the shrimp",
        durationMin: 5,
        text: "Soak dried shrimp in warm water 5 minutes, then drain and pound or chop them. Crush the peanuts roughly.",
      },
      {
        order: 3,
        title: "Make the dressing",
        durationMin: 5,
        text: "Pound garlic and chili with sugar, then stir in fish sauce and lime juice until the sugar dissolves.",
      },
      {
        order: 4,
        title: "Toss",
        durationMin: 5,
        text: "Toss papaya with dressing, dried shrimp, most of the peanuts, and torn basil. Pile onto a plate and finish with the remaining peanuts.",
      },
    ],
  },
  {
    slug: "vietnamese-banana-cake",
    cuisineSlug: "vietnamese",
    prepTime: 55,
    calories: 280,
    difficulty: "easy",
    servings: 8,
    title: "Vietnamese Banana Cake",
    description:
      "Ripe bananas bound with rice flour and coconut milk, sweetened and steamed or baked until the crumb is moist and coconut-scented.",
    tags: ["dessert", "banana", "coconut", "steamed"],
    chefTips: [
      "Use very ripe, fragrant bananas — the small Vietnamese or apple bananas are ideal if you can find them.",
      "Steaming keeps the cake custardy; baking at 175°C gives a slightly drier, golden top.",
    ],
    nutrition: {
      protein: 3,
      carbs: 48,
      fat: 8,
      fiber: 2,
      sugar: 24,
      sodium: 80,
      saturatedFat: 6,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Ripe bananas", amount: "4", unit: "pcs" },
      { name: "Rice flour", amount: "150", unit: "g" },
      { name: "Tapioca starch", amount: "30", unit: "g" },
      { name: "Coconut milk", amount: "200", unit: "ml" },
      { name: "Granulated sugar", amount: "100", unit: "g" },
      { name: "Kosher salt", amount: "0.25", unit: "tsp" },
      { name: "Vanilla extract", amount: "1", unit: "tsp" },
      { name: "Vegetable oil", amount: "1", unit: "tbsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Mash the bananas",
        durationMin: 8,
        text: "Mash the bananas until mostly smooth with a few chunks. Stir in sugar, salt, vanilla, and coconut milk.",
      },
      {
        order: 2,
        title: "Add the flours",
        durationMin: 7,
        text: "Whisk rice flour and tapioca starch into the banana mixture until no dry pockets remain. Rest 10 minutes so the rice flour hydrates.",
      },
      {
        order: 3,
        title: "Steam or bake",
        durationMin: 35,
        text: "Oil an 18 cm pan or heatproof dish. Pour in the batter. Steam over medium heat until set and a skewer comes out clean, 30 to 35 minutes, or bake at 175°C for the same time.",
      },
      {
        order: 4,
        title: "Cool and slice",
        durationMin: 5,
        text: "Cool until just warm so the crumb firms. Slice into squares or wedges and serve as is or with extra coconut milk.",
      },
    ],
  },
  {
    slug: "vietnamese-coconut-jelly",
    cuisineSlug: "vietnamese",
    prepTime: 25,
    calories: 160,
    difficulty: "easy",
    servings: 6,
    title: "Vietnamese Coconut Jelly",
    description:
      "A chilled coconut-milk and coconut-water jelly set with agar-agar, lightly sweetened, with optional pandan.",
    tags: ["dessert", "coconut", "chilled", "agar"],
    chefTips: [
      "Agar sets at room temperature and stays firm out of the fridge — bloom it fully in the coconut water before you boil or it will grain.",
      "A strip of pandan tied in a knot perfumes the pot; pull it out before pouring.",
    ],
    nutrition: {
      protein: 1,
      carbs: 22,
      fat: 8,
      fiber: 0,
      sugar: 20,
      sodium: 30,
      saturatedFat: 7,
      cholesterol: 0,
    },
    ingredients: [
      { name: "Coconut milk", amount: "400", unit: "ml" },
      { name: "Coconut water", amount: "400", unit: "ml" },
      { name: "Agar-agar powder", amount: "8", unit: "g" },
      { name: "Granulated sugar", amount: "80", unit: "g" },
      { name: "Pandan leaves", amount: "2", unit: "pcs" },
      { name: "Kosher salt", amount: "0.125", unit: "tsp" },
      { name: "Vanilla extract", amount: "0.5", unit: "tsp" },
    ],
    steps: [
      {
        order: 1,
        title: "Bloom the agar",
        durationMin: 8,
        text: "Stir agar-agar into the coconut water and let it sit 5 minutes. Tie the pandan leaves in a knot.",
      },
      {
        order: 2,
        title: "Dissolve",
        durationMin: 8,
        text: "Bring the coconut water and agar to a simmer with the pandan, stirring until the powder fully dissolves and the liquid looks clear, 3 to 5 minutes. Stir in sugar and salt.",
      },
      {
        order: 3,
        title: "Add coconut milk",
        durationMin: 4,
        text: "Pour in the coconut milk and vanilla. Warm just to a gentle simmer — do not boil hard or the milk may split. Remove the pandan.",
      },
      {
        order: 4,
        title: "Set",
        durationMin: 5,
        text: "Pour into a shallow dish or molds. Cool until set, then refrigerate. Cut into cubes or diamonds and serve cold.",
      },
    ],
  },
];
